/**
 * Aldine template (`layouts: ["single"]`).
 *
 * Fine-paper editorial single column with sage accents.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/aldine.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const ALDINE_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F8F4EC",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 29,
    "top": 29,
    "width": 537,
    "height": 784,
    "backgroundColor": "#D7CCB8",
    "borderWidth": 0.7,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 71,
    "top": 36,
    "width": 1,
    "height": 770,
    "backgroundColor": "#E3D9C9",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 523,
    "top": 36,
    "width": 1,
    "height": 770,
    "backgroundColor": "#E3D9C9",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 92,
    "top": 783,
    "width": 408,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 92,
    "top": 796,
    "width": 6,
    "height": 6,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#79776E",
    "left": 485,
    "top": 791,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#2A3028",
    "left": 92,
    "top": 66,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 8.9,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 94,
    "top": 106,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.4,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#79776E",
    "left": 94,
    "top": 132,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 92,
    "top": 157,
    "width": 408,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 446,
    "top": 61,
    "width": 48,
    "height": 48,
    "backgroundColor": "#486151",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "aldine-seal",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "ellipse",
    "left": 458,
    "top": 76,
    "width": 24,
    "height": 10,
    "backgroundColor": "#788068",
    "filled": false,
    "borderWidth": 0.9,
    "zIndex": 3,
    "page": 1,
    "id": "aldine-lozenge",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 465,
    "top": 93,
    "width": 10,
    "height": 10,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "aldine-core",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 437,
    "top": 52,
    "width": 66,
    "height": 66,
    "backgroundColor": "#D7CCB8",
    "borderWidth": 0.7,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "aldine-frame",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 508,
    "top": 96,
    "width": 14,
    "height": 1,
    "backgroundColor": "#486151",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 94,
    "top": 195.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 116,
    "top": 193.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 116,
    "top": 204.34,
    "width": 384,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 116,
    "top": 212.34,
    "width": 384,
    "height": 40,
    "fontSize": 9.3,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 94,
    "top": 275.34000000000003,
    "width": 7,
    "height": 7,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 116,
    "top": 273.34000000000003,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 116,
    "top": 284.68,
    "width": 384,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 116,
    "top": 292.68,
    "width": 384,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b9039b88a756",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 116,
    "top": 311.68,
    "width": 384,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#79776E",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b9039b88a756",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 116,
    "top": 327.68,
    "width": 384,
    "height": 40,
    "fontSize": 9.3,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b9039b88a756",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 116,
    "top": 377.68,
    "width": 384,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f893aaf8bcc1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 116,
    "top": 396.68,
    "width": 384,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#79776E",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f893aaf8bcc1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 116,
    "top": 412.68,
    "width": 384,
    "height": 27,
    "fontSize": 9.3,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f893aaf8bcc1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 116,
    "top": 449.68,
    "width": 384,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c2117f6cb5d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 116,
    "top": 468.68,
    "width": 384,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#79776E",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c2117f6cb5d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 116,
    "top": 484.68,
    "width": 384,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c2117f6cb5d",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 94,
    "top": 521.6800000000001,
    "width": 7,
    "height": 7,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 116,
    "top": 519.6800000000001,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 116,
    "top": 531.0200000000001,
    "width": 384,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 116,
    "top": 539.0200000000001,
    "width": 384,
    "height": 13,
    "fontSize": 10.2,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d998af2ddf52",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 116,
    "top": 556.0200000000001,
    "width": 384,
    "height": 13,
    "fontSize": 10.2,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d998af2ddf52",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 116,
    "top": 573.0200000000001,
    "width": 384,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#79776E",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d998af2ddf52",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 94,
    "top": 608.0200000000001,
    "width": 7,
    "height": 7,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 116,
    "top": 606.0200000000001,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 116,
    "top": 617.3600000000001,
    "width": 384,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 116,
    "top": 625.3600000000001,
    "width": 384,
    "height": 13,
    "fontSize": 9.1,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dab5f20b0d8f",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 94,
    "top": 661.3600000000001,
    "width": 7,
    "height": 7,
    "backgroundColor": "#486151",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#486151",
    "left": 116,
    "top": 659.3600000000001,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 116,
    "top": 670.7000000000002,
    "width": 384,
    "height": 1,
    "backgroundColor": "#D7CCB8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 116.0,
    "top": 678.7000000000002,
    "width": 88.0,
    "height": 13,
    "fontSize": 9.1,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#486151"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-22f9e22b0e41"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 212.0,
    "top": 678.7000000000002,
    "width": 88.0,
    "height": 13,
    "fontSize": 9.1,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#486151"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-22f9e22b0e41"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 308.0,
    "top": 678.7000000000002,
    "width": 88.0,
    "height": 13,
    "fontSize": 9.1,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2A3028",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#486151"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-22f9e22b0e41"
  }
];

export const aldineTemplate = ALDINE_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
