/**
 * Amaranth: bordeaux single column, Playfair Display and Roboto, rounded photo/label chrome and a right-hand date rail.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv/templates/generators/amaranth.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const AMARANTH_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true,
    "appearanceTemplateId": "amaranth",
    "appearanceSettings": {
      "palette": "claret",
      "textSize": "M"
    }
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 796,
    "width": 479.0,
    "height": 0.7,
    "backgroundColor": "#E4D8DC",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.4,
    "fontFamily": "Roboto",
    "color": "#78304A",
    "left": 517.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Aleksandra Nowak",
    "left": 58.0,
    "top": 44.0,
    "width": 344.0,
    "height": 34.0,
    "fontSize": 27.0,
    "lineHeight": 33.0,
    "letterSpacing": 0.4,
    "color": "#2C1A22",
    "fontFamily": "PlayfairDisplay",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "nameFit": {
      "mode": "wrap",
      "baseHeight": 34.0,
      "baseFontSize": 27.0,
      "fittedFontSize": 27.0,
      "baseLineHeight": 33.0,
      "width": 344.0,
      "extraHeight": 0.0
    },
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "textarea",
    "content": "Strategy & Operations Manager",
    "left": 58.0,
    "top": 83.0,
    "width": 344.0,
    "height": 12,
    "fontSize": 8.2,
    "lineHeight": 11.5,
    "letterSpacing": 2.4,
    "color": "#78304A",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/amaranth-claret/phone.png",
    "left": 58.0,
    "top": 106.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "textarea",
    "content": "+48 000 000 000",
    "left": 72.0,
    "top": 106.0,
    "width": 330.0,
    "height": 11,
    "fontSize": 7.0,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "phone",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/amaranth-claret/email.png",
    "left": 58.0,
    "top": 119.6,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "textarea",
    "content": "aleksandra.nowak@example.com",
    "left": 72.0,
    "top": 119.6,
    "width": 330.0,
    "height": 11,
    "fontSize": 7.0,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "email",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/amaranth-claret/linkedin.png",
    "left": 58.0,
    "top": 133.2,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "textarea",
    "content": "linkedin.com/in/aleksandra-nowak-demo",
    "left": 72.0,
    "top": 133.2,
    "width": 330.0,
    "height": 11,
    "fontSize": 7.0,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "linkedin",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/amaranth-claret/location.png",
    "left": 58.0,
    "top": 146.79999999999998,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "textarea",
    "content": "Warszawa, Polska",
    "left": 72.0,
    "top": 146.79999999999998,
    "width": 330.0,
    "height": 11,
    "fontSize": 7.0,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "location",
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "line",
    "left": 104.0,
    "top": 178.0,
    "width": 313.0,
    "height": 0.8,
    "backgroundColor": "#E4D8DC",
    "zIndex": 2,
    "page": 1,
    "id": "amaranth-masthead-divider",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 176.8,
    "width": 40.0,
    "height": 3.2,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 1.6,
    "zIndex": 3,
    "page": 1,
    "id": "amaranth-masthead-accent",
    "appearanceColorRole": "accent",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 429.0,
    "top": 34.0,
    "width": 112.0,
    "height": 130.0,
    "backgroundColor": "#9A5568",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 18.0,
    "zIndex": 2,
    "page": 1,
    "photoSlot": "ornament",
    "appearanceColorRole": "ornament",
    "fixedToPage": true,
    "repeatOnContinuation": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 433.0,
    "top": 38.0,
    "width": 104.0,
    "height": 122.0,
    "backgroundColor": "#EFE4E8",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 14.0,
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "appearanceColorRole": "photo",
    "fixedToPage": true,
    "repeatOnContinuation": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/amaranth-claret/portrait.png",
    "left": 462.0,
    "top": 76.0,
    "width": 46.0,
    "height": 46.0,
    "zIndex": 4,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "amaranth-photo-glyph",
    "photoSlot": "glyph",
    "photoShape": "rect",
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "rectangle",
    "left": 433.0,
    "top": 38.0,
    "width": 104.0,
    "height": 122.0,
    "backgroundColor": "#EFE4E8",
    "borderWidth": 1.0,
    "filled": false,
    "borderRadius": 14.0,
    "zIndex": 5,
    "page": 1,
    "id": "amaranth-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "fixedToPage": true,
    "repeatOnContinuation": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "amaranth-contact",
      "mode": "bounded-stack",
      "anchor": {
        "startX": 58.0,
        "startY": 106.0,
        "maxWidth": 344.0
      },
      "text": {
        "fontFamily": "Roboto",
        "fontSizePt": 7.0,
        "colorHex": "#7E6870",
        "lineHeightPt": 10.4
      },
      "icon": {
        "sizePt": 11.0,
        "theme": "amaranth-claret"
      },
      "metrics": {
        "iconGap": 14.0,
        "itemPad": 0.0,
        "lineStep": 13.0,
        "charWidth": 3.64
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ],
      "flow": {
        "dividerId": "amaranth-masthead-divider",
        "dividerGap": 22.0,
        "accentBarId": "amaranth-masthead-accent",
        "accentBarDeltaTop": -1.2,
        "bodyGap": 14.0,
        "minimumRows": 2,
        "minimumBodyTop": 178.0,
        "bodyTop": 192.0,
        "spacing": {
          "stack": 4.0,
          "record": 10.0,
          "section": 21.0,
          "after_rule": 8.0
        }
      }
    },
    "contactBandId": "amaranth-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Strategy & Operations Manager",
          "left": 58.0,
          "top": 83.0,
          "width": 344.0,
          "height": 12,
          "fontSizePt": 8.2,
          "lineHeight": 11.5,
          "fontFamily": "Roboto",
          "colorHex": "#78304A",
          "letterSpacing": 2.4,
          "align": "left",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "uppercase",
          "bold": false,
          "italic": false,
          "underline": false,
          "zIndex": 3
        },
        "blockPt": 23.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "amaranth-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 192.0,
    "width": 166.4703125,
    "height": 17.0,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 7.6,
    "fontFamily": "Roboto",
    "color": "#FFFFFF",
    "left": 69.0,
    "top": 203.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.0,
    "flowRole": "section-chrome",
    "appearanceColorRole": "headingOnAccent"
  },
  {
    "category": "rectangle",
    "left": 46.0,
    "top": 211.0,
    "width": 503.0,
    "height": 49.0,
    "backgroundColor": "#F5EDEF",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 12.0,
    "zIndex": 1,
    "page": 1,
    "id": "amaranth-summary-field",
    "flowRole": "section-background",
    "appearanceColorRole": "field",
    "flowGroup": "record-2b8f3f1994ed"
  },
  {
    "category": "textarea",
    "content": "Managerka strategii i operacji z ponad 7-letnim doświadczeniem w doradztwie oraz transformacji biznesowej. Specjalizuję się w analizie procesów, projektowaniu modeli operacyjnych i prowadzeniu inicjatyw zwiększających efektywność organizacji. Łączę analityczne podejście z umiejętnością przekładania danych na konkretne decyzje biznesowe.",
    "left": 58.0,
    "top": 217.0,
    "width": 479.0,
    "height": 34,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2b8f3f1994ed",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 272.0,
    "width": 97.1740234375,
    "height": 17.0,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Roboto",
    "color": "#FFFFFF",
    "left": 69.0,
    "top": 283.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.0,
    "flowRole": "section-chrome",
    "appearanceColorRole": "headingOnAccent"
  },
  {
    "category": "textarea",
    "content": "Strategia biznesowa  ·  Business Analysis  ·  Optymalizacja procesów  ·  Operating Model  ·  Analiza danych  ·  Financial Modeling  ·  Power BI  ·  Excel  ·  SQL  ·  Stakeholder Management",
    "left": 58.0,
    "top": 297.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b11a87bdff80",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 341.0,
    "width": 167.7578125,
    "height": 17.0,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 7.6,
    "fontFamily": "Roboto",
    "color": "#FFFFFF",
    "left": 69.0,
    "top": 352.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.0,
    "flowRole": "section-chrome",
    "appearanceColorRole": "headingOnAccent"
  },
  {
    "category": "textarea",
    "content": "Strategy & Operations Manager",
    "left": 58.0,
    "top": 366.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 10.0,
    "lineHeight": 12.8,
    "letterSpacing": 0,
    "color": "#2C1A22",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9255d1ee8e5c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Advisory",
    "left": 58.0,
    "top": 383.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9255d1ee8e5c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę projekty transformacyjne dla klientów z sektora finansowego, technologicznego i usług profesjonalnych.\n• Projektuję modele operacyjne, identyfikuję obszary optymalizacji i przygotowuję rekomendacje dla kadry zarządzającej.\n• Koordynuję zespoły projektowe oraz odpowiadam za prezentację wyników i wdrożenie uzgodnionych działań.",
    "left": 58.0,
    "top": 398.0,
    "width": 479.0,
    "height": 34,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9255d1ee8e5c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "01/2023 – obecnie",
    "left": 407.0,
    "top": 366.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-9255d1ee8e5c"
  },
  {
    "category": "textarea",
    "content": "Senior Business Analyst",
    "left": 58.0,
    "top": 442.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 10.0,
    "lineHeight": 12.8,
    "letterSpacing": 0,
    "color": "#2C1A22",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-615c53d5ad96",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Vantage Partners",
    "left": 58.0,
    "top": 459.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-615c53d5ad96",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Analizowałam procesy biznesowe i dane operacyjne, identyfikując możliwości automatyzacji oraz redukcji kosztów.\n• Tworzyłam modele finansowe, dashboardy KPI i materiały decyzyjne dla klientów oraz zespołów projektowych.",
    "left": 58.0,
    "top": 474.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-615c53d5ad96",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "06/2020 – 12/2022",
    "left": 407.0,
    "top": 442.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-615c53d5ad96"
  },
  {
    "category": "textarea",
    "content": "Business Analyst",
    "left": 58.0,
    "top": 507.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 10.0,
    "lineHeight": 12.8,
    "letterSpacing": 0,
    "color": "#2C1A22",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0bc1035ecfa6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Orion Consulting Group",
    "left": 58.0,
    "top": 524.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0bc1035ecfa6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam projekty strategiczne poprzez analizę rynku, benchmarking konkurencji i przygotowywanie rekomendacji.\n• Opracowywałam raporty zarządcze oraz prezentacje wykorzystywane podczas warsztatów z klientami.",
    "left": 58.0,
    "top": 539.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0bc1035ecfa6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "09/2017 – 05/2020",
    "left": 407.0,
    "top": 507.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-0bc1035ecfa6"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 583.0,
    "width": 105.8017578125,
    "height": 17.0,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Roboto",
    "color": "#FFFFFF",
    "left": 69.0,
    "top": 594.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.0,
    "flowRole": "section-chrome",
    "appearanceColorRole": "headingOnAccent"
  },
  {
    "category": "textarea",
    "content": "Magister zarządzania",
    "left": 58.0,
    "top": 608.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.2,
    "letterSpacing": 0,
    "color": "#2C1A22",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-479e2b5ef090",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Uniwersytet Ekonomiczny w Krakowie",
    "left": 58.0,
    "top": 625.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-479e2b5ef090",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Specjalizacja: strategia przedsiębiorstwa i zarządzanie zmianą.",
    "left": 58.0,
    "top": 640.0,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-479e2b5ef090",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2015 – 2017",
    "left": 407.0,
    "top": 608.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-479e2b5ef090"
  },
  {
    "category": "textarea",
    "content": "Licencjat ekonomii",
    "left": 58.0,
    "top": 662.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.2,
    "letterSpacing": 0,
    "color": "#2C1A22",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b246d76fa67e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Uniwersytet Ekonomiczny w Krakowie",
    "left": 58.0,
    "top": 679.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b246d76fa67e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2015",
    "left": 407.0,
    "top": 662.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#7E6870",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-b246d76fa67e"
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 711.0,
    "width": 56.4662109375,
    "height": 17.0,
    "backgroundColor": "#78304A",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Roboto",
    "color": "#FFFFFF",
    "left": 69.0,
    "top": 722.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.0,
    "flowRole": "section-chrome",
    "appearanceColorRole": "headingOnAccent",
    "editorSectionLayout": "grid",
    "editorGridColumns": 4,
    "editorGridRecordWidth": 479.0,
    "editorGridBodyLeft": 58.0,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0,
    "gridKind": "languages"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 58.0,
    "top": 736.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-d6b03280a0b4",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 177.75,
    "top": 736.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-d6b03280a0b4",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 736.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3A2E33",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-d6b03280a0b4",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  }
];

export const amaranthTemplate = AMARANTH_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
