/**
 * Atrium template (`layouts: ["single", "icons"]`).
 *
 * Architectural editorial with original travertine, white, dark, and three saturated Appearance editions.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/atrium.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const ATRIUM_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FBFAF7",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true,
    "appearanceColorRole": "paper",
    "appearanceTemplateId": "atrium",
    "appearanceSettings": {
      "palette": "sage",
      "textSize": "M"
    }
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 291.5,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true,
    "appearanceColorRole": "folio",
    "appearanceTypographyRole": "folio"
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 82,
    "top": 54.0,
    "width": 431,
    "height": 35,
    "fontSize": 31,
    "lineHeight": 35,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "PlayfairDisplay",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "appearanceColorRole": "ink",
    "appearanceTypographyRole": "display",
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/portrait.png",
    "left": 462.0,
    "top": 19.0,
    "width": 60.0,
    "height": 80.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "atrium-photo-glyph",
    "photoSlot": "glyph",
    "photoShape": "direct",
    "appearanceColorRole": "photo"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 82,
    "top": 97.0,
    "width": 431,
    "height": 13,
    "fontSize": 9.2,
    "lineHeight": 13,
    "letterSpacing": 2.1,
    "color": "#556158",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "job",
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/phone.png",
    "left": 128.0006,
    "top": 126.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 140.5006,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/email.png",
    "left": 225.12099999999998,
    "top": 126.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 237.62099999999998,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/linkedin.png",
    "left": 355.83299999999997,
    "top": 126.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 368.33299999999997,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/github.png",
    "left": 170.19379999999998,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 182.69379999999998,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/website.png",
    "left": 283.123,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 295.623,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/atrium-sage/location.png",
    "left": 368.9622,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 381.4622,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "line",
    "left": 251.5,
    "top": 168.0,
    "width": 34.0,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "appearanceColorRole": "rule",
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 292.5,
    "top": 168.0,
    "width": 10.0,
    "height": 1,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "appearanceColorRole": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 309.5,
    "top": 168.0,
    "width": 34.0,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "appearanceColorRole": "rule",
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 126.0,
        "maxWidth": 431.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 8.4,
        "colorHex": "#78796F"
      },
      "icon": {
        "sizePt": 10.5,
        "theme": "atrium-sage"
      },
      "metrics": {
        "iconGap": 12.5,
        "itemPad": 18.0,
        "lineStep": 16.0,
        "charWidth": 5.0
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 82,
          "top": 97.0,
          "width": 431,
          "height": 13,
          "fontSizePt": 9.2,
          "lineHeight": 13,
          "fontFamily": "Montserrat",
          "colorHex": "#556158",
          "letterSpacing": 2.1,
          "align": "center",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "none",
          "bold": false,
          "italic": false,
          "underline": false,
          "zIndex": 3
        },
        "blockPt": 29.0,
        "present": true,
        "decorations": [],
        "reclaimPt": 16.0
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 198.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "heading"
  },
  {
    "category": "line",
    "left": 82,
    "top": 212.2,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "ornament"
  },
  {
    "category": "line",
    "left": 108,
    "top": 212.2,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "rule"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz.",
    "left": 82,
    "top": 221.39999999999998,
    "width": 431,
    "height": 29,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 271.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "heading"
  },
  {
    "category": "line",
    "left": 82,
    "top": 285.59999999999997,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "ornament"
  },
  {
    "category": "line",
    "left": 108,
    "top": 285.59999999999997,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "rule"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 82,
    "top": 294.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4b9fb0a99a7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 82,
    "top": 313.79999999999995,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4b9fb0a99a7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.",
    "left": 82,
    "top": 329.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4b9fb0a99a7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 82,
    "top": 354.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d27ceb4e21e0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 82,
    "top": 373.79999999999995,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d27ceb4e21e0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.",
    "left": 82,
    "top": 389.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d27ceb4e21e0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 82,
    "top": 414.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8fe6832c59fb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 82,
    "top": 433.79999999999995,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8fe6832c59fb",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 466.79999999999995,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "heading"
  },
  {
    "category": "line",
    "left": 82,
    "top": 480.99999999999994,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "ornament"
  },
  {
    "category": "line",
    "left": 108,
    "top": 480.99999999999994,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "rule"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 82,
    "top": 490.19999999999993,
    "width": 431,
    "height": 14,
    "fontSize": 10.2,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-fcae48ae5720",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 82,
    "top": 508.19999999999993,
    "width": 431,
    "height": 14,
    "fontSize": 10.2,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-fcae48ae5720",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 82,
    "top": 526.1999999999999,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-fcae48ae5720",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 559.1999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "heading"
  },
  {
    "category": "line",
    "left": 82,
    "top": 573.4,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "ornament"
  },
  {
    "category": "line",
    "left": 108,
    "top": 573.4,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "rule"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 82,
    "top": 582.6,
    "width": 431,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0334233da465",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 618.6,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome",
    "appearanceColorRole": "accent",
    "appearanceTypographyRole": "heading"
  },
  {
    "category": "line",
    "left": 82,
    "top": 632.8000000000001,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "ornament"
  },
  {
    "category": "line",
    "left": 108,
    "top": 632.8000000000001,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome",
    "appearanceColorRole": "rule"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 82.0,
    "top": 642.0000000000001,
    "width": 99.75,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-334aa5ecb6ed"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 189.75,
    "top": 642.0000000000001,
    "width": 99.75,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-334aa5ecb6ed"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 642.0000000000001,
    "width": 99.75,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-334aa5ecb6ed"
  }
];

export const atriumTemplate = ATRIUM_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
