import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { applyFlowSpacing, listDocumentSections, sectionElementIds } from "../utils/sectionStructure.js";

// A real two-page Atrium document, dumped from the backend generator with
// element ids assigned (the loader does that in the app). Regression guard for
// the reported bug: Atrium section headings (Wykształcenie / Umiejętności /
// Języki) detached from their bodies and any spacing change scrambled the
// rhythm, because the headings were authored as wide centered textareas the
// shared section packer does not treat as chrome. They are now plain centered
// `text` chrome — identical in kind to every other template's headings.
const FIXTURE = JSON.parse(
    readFileSync(new URL("./atrium.multipage.fixture.json", import.meta.url), "utf8"),
);

const PAGE_HEIGHT = 842;
const EXPECTED_ORDER = [
    "PODSUMOWANIE ZAWODOWE",
    "DOŚWIADCZENIE ZAWODOWE",
    "WYKSZTAŁCENIE",
    "UMIEJĘTNOŚCI",
    "JĘZYKI",
];

const absTop = (element) => ((element.page || 1) - 1) * PAGE_HEIGHT + (element.top || 0);

/**
 * Every section heading must sit directly above its own body — never orphaned
 * onto an earlier page. `sectionElementIds` groups a section's members; the
 * heading's top must precede its first body block by only the chrome band
 * (heading + broken rule + under-rule gap), well under a section's worth of
 * space. A detached heading (the bug) would show a gap of hundreds of px.
 */
function assertHeadingsGlued(elements, label) {
    const sections = listDocumentSections(elements);
    assert.deepEqual(
        sections.map((section) => section.title),
        EXPECTED_ORDER,
        `${label}: sections detected in document order`,
    );
    for (const section of sections) {
        const ids = sectionElementIds(elements, section.headingId);
        const heading = elements.find((element) => element.element_id === section.headingId);
        const bodies = [...ids]
            .map((id) => elements.find((element) => element.element_id === id))
            .filter(
                (element) =>
                    element &&
                    element.element_id !== section.headingId &&
                    element.flowRole !== "section-chrome" &&
                    element.flowRole !== "masthead" &&
                    element.category !== "image" &&
                    element.category !== "line",
            );
        assert.ok(bodies.length > 0, `${label}: ${section.title} has a body`);
        const firstBodyTop = Math.min(...bodies.map(absTop));
        const gap = firstBodyTop - absTop(heading);
        assert.ok(
            gap > 0 && gap < 80,
            `${label}: ${section.title} heading stays glued to its body (gap ${gap.toFixed(1)}px)`,
        );
    }
}

test("Atrium keeps every section heading glued to its body across pages and spacing changes", () => {
    // As generated by the backend.
    assertHeadingsGlued(FIXTURE, "as-generated");
    // After the Układ CV panel's rhythm packing at the default rhythm…
    assertHeadingsGlued(
        applyFlowSpacing(FIXTURE, { stack: 4, record: 10, section: 21, after_rule: 8 }),
        "default rhythm",
    );
    // …and at a compact rhythm (the "regulacja odstępów" the user hit).
    assertHeadingsGlued(
        applyFlowSpacing(FIXTURE, { stack: 3, record: 7, section: 15, after_rule: 6 }),
        "compact rhythm",
    );
});
