/**
 * Atrium template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/atrium.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const ATRIUM_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FBFAF7",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 291.5,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Weronika Sikora",
    "left": 82,
    "top": 54.0,
    "width": 431,
    "height": 35,
    "fontSize": 31,
    "lineHeight": 35,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "PlayfairDisplay",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/portrait.png",
    "left": 429,
    "top": 44.0,
    "width": 84,
    "height": 84,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "atrium-photo-glyph",
    "photoSlot": "glyph"
  },
  {
    "category": "textarea",
    "content": "Junior Penetration Tester",
    "left": 82,
    "top": 97.0,
    "width": 431,
    "height": 13,
    "fontSize": 9.2,
    "lineHeight": 13,
    "letterSpacing": 2.1,
    "color": "#556158",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/phone.png",
    "left": 166.3926,
    "top": 126.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 733 908 261",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 178.8926,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/email.png",
    "left": 262.6142,
    "top": 126.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "weronika.sikora.pentest@gmail.com",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 275.1142,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/linkedin.png",
    "left": 110.36899999999997,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/weronika-sikora",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 122.86899999999997,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/github.png",
    "left": 276.24339999999995,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/wsikora",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 288.74339999999995,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/website.png",
    "left": 391.0458,
    "top": 142.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "weronikasikora.dev",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 403.5458,
    "top": 142.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/atrium/location.png",
    "left": 278.566,
    "top": 158.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Kielce",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#78796F",
    "left": 291.066,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 251.5,
    "top": 177.0,
    "width": 34.0,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 292.5,
    "top": 177.0,
    "width": 10.0,
    "height": 1,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 309.5,
    "top": 177.0,
    "width": 34.0,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 214.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 82,
    "top": 228.2,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 108,
    "top": 228.2,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Junior Penetration Tester z pasją do bezpieczeństwa aplikacji webowych. Ukończyłam ponad 70 pokoi na TryHackMe i aktywnie rozwiązuję zadania CTF. Poszukuję pierwszej pełnoetatowej roli w zespole ofensywnego bezpieczeństwa.",
    "left": 82,
    "top": 237.39999999999998,
    "width": 431,
    "height": 43,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 301.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 82,
    "top": 315.59999999999997,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 108,
    "top": 315.59999999999997,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Junior Penetration Tester",
    "left": 82,
    "top": 324.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a9eb33333adf"
  },
  {
    "category": "textarea",
    "content": "Bastion CyberSec   ·   Kielce   ·   Luty 2024 – obecnie",
    "left": 82,
    "top": 343.79999999999995,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a9eb33333adf"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę testy penetracyjne aplikacji webowych pod nadzorem starszych testerów.\n• Identyfikuję i dokumentuję podatności zgodnie z metodyką OWASP.\n• Przygotowuję raporty z testów wraz z rekomendacjami naprawczymi.",
    "left": 82,
    "top": 359.79999999999995,
    "width": 431,
    "height": 43,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a9eb33333adf"
  },
  {
    "category": "textarea",
    "content": "Praktykantka ds. Bezpieczeństwa",
    "left": 82,
    "top": 412.79999999999995,
    "width": 431,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-627d0a40afdc"
  },
  {
    "category": "textarea",
    "content": "Meridian IT Services   ·   Kielce   ·   Czerwiec 2023 – Styczeń 2024",
    "left": 82,
    "top": 431.79999999999995,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-627d0a40afdc"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam zespół bezpieczeństwa w skanowaniu podatności infrastruktury.\n• Uczestniczyłam w przeglądach kodu pod kątem podstawowych błędów bezpieczeństwa.",
    "left": 82,
    "top": 447.79999999999995,
    "width": 431,
    "height": 29,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-627d0a40afdc"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 497.79999999999995,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 82,
    "top": 511.99999999999994,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 108,
    "top": 511.99999999999994,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Inżynier informatyki — specjalność: Bezpieczeństwo aplikacji",
    "left": 82,
    "top": 521.1999999999999,
    "width": 431,
    "height": 14,
    "fontSize": 10.2,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5eacc5ca448"
  },
  {
    "category": "textarea",
    "content": "Politechnika Świętokrzyska",
    "left": 82,
    "top": 539.1999999999999,
    "width": 431,
    "height": 14,
    "fontSize": 10.2,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#242521",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5eacc5ca448"
  },
  {
    "category": "textarea",
    "content": "Kielce   ·   ukończono lipiec 2023",
    "left": 82,
    "top": 557.1999999999999,
    "width": 431,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#78796F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5eacc5ca448"
  },
  {
    "category": "textarea",
    "content": "• Praca inżynierska: automatyzacja testów bezpieczeństwa aplikacji webowych.",
    "left": 82,
    "top": 573.1999999999999,
    "width": 431,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5eacc5ca448"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 608.1999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 82,
    "top": 622.4,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 108,
    "top": 622.4,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "OWASP Top 10  ·  Burp Suite  ·  SQLi/XSS  ·  Nmap  ·  Metasploit  ·  Python  ·  Bash  ·  Linux  ·  Git",
    "left": 82,
    "top": 631.6,
    "width": 431,
    "height": 29,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-763c000df652"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#556158",
    "left": 82,
    "top": 681.6,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 82,
    "top": 695.8000000000001,
    "width": 18,
    "height": 1.2,
    "backgroundColor": "#556158",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 108,
    "top": 695.8000000000001,
    "width": 405,
    "height": 1,
    "backgroundColor": "#E5E3DB",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — B2",
    "left": 82.0,
    "top": 705.0000000000001,
    "width": 99.75,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#556158"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-cac34e96cf9a"
  },
  {
    "category": "textarea",
    "content": "niemiecki — A2",
    "left": 189.75,
    "top": 705.0000000000001,
    "width": 99.75,
    "height": 15,
    "fontSize": 9.6,
    "lineHeight": 14.1,
    "letterSpacing": 0,
    "color": "#2C2C29",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#556158"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-cac34e96cf9a"
  }
];

export const atriumTemplate = ATRIUM_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
