/**
 * Aurelia template (`layouts: ["single", "icons"]`).
 *
 * Olive-gold single-column editorial with an outlined identity frame,
 * centered contact band, and exact-anchor record metadata.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/aurelia.py`) for
 * representative demo content (Julia Bernat — four roles, two degrees, eight skills, and four languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const AURELIA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true,
    "appearanceTemplateId": "aurelia",
    "appearanceSettings": {
      "palette": "gilded",
      "textSize": "M"
    }
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 796,
    "width": 479.0,
    "height": 0.75,
    "backgroundColor": "#D6D1BC",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 292.5,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 58.0,
    "top": 38.0,
    "width": 479.0,
    "height": 104.0,
    "backgroundColor": "#98884D",
    "borderWidth": 1.15,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "id": "aurelia-masthead-frame",
    "flowRole": "masthead",
    "mastheadFrame": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 74.0,
    "top": 57.0,
    "width": 447.0,
    "height": 33,
    "fontSize": 29.0,
    "lineHeight": 33.0,
    "letterSpacing": 2.4,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "aurelia-masthead",
    "textTransform": "uppercase"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 82.0,
    "top": 105.0,
    "width": 431.0,
    "height": 11,
    "fontSize": 7.8,
    "lineHeight": 10.8,
    "letterSpacing": 2.3,
    "color": "#353632",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "aurelia-masthead",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/phone.png",
    "left": 75.22199999999998,
    "top": 158.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 85.72199999999998,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/email.png",
    "left": 155.23899999999998,
    "top": 158.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 165.73899999999998,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/linkedin.png",
    "left": 263.24899999999997,
    "top": 158.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 273.74899999999997,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/github.png",
    "left": 369.971,
    "top": 158.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 380.471,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/website.png",
    "left": 463.16200000000003,
    "top": 158.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 473.66200000000003,
    "top": 158.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/aurelia-gilded/location.png",
    "left": 274.19,
    "top": 171.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.0,
    "fontFamily": "Montserrat",
    "color": "#6A6C66",
    "left": 284.69,
    "top": 171.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 195.0,
    "width": 479.0,
    "height": 0.85,
    "backgroundColor": "#D6D1BC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead",
    "mastheadDivider": true
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "aurelia-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 158.0,
        "maxWidth": 479.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 7.0,
        "colorHex": "#6A6C66"
      },
      "icon": {
        "sizePt": 9.0,
        "theme": "aurelia-gilded"
      },
      "metrics": {
        "iconGap": 10.5,
        "itemPad": 14.0,
        "lineStep": 13.0,
        "charWidth": 4.4
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "aurelia-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "aurelia-masthead",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 82.0,
          "top": 105.0,
          "width": 431.0,
          "height": 11,
          "fontSizePt": 7.8,
          "lineHeight": 10.8,
          "fontFamily": "Montserrat",
          "colorHex": "#353632",
          "letterSpacing": 2.3,
          "align": "center",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "uppercase",
          "bold": false,
          "italic": false,
          "underline": false,
          "zIndex": 3
        },
        "blockPt": 11.0,
        "present": true,
        "decorations": [],
        "reclaimPt": 0.0
      },
      "contactBandId": "aurelia-contact"
    },
    "mastheadBandId": "aurelia-masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 58.0,
    "top": 213.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.9,
    "width": 479.0,
    "align": "center",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 227.5,
    "width": 479.0,
    "height": 0.9,
    "backgroundColor": "#98884D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 58.0,
    "top": 236.4,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 58.0,
    "top": 280.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.9,
    "width": 479.0,
    "align": "center",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 294.9,
    "width": 479.0,
    "height": 0.9,
    "backgroundColor": "#98884D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 58.0,
    "top": 303.79999999999995,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.3,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92fa1289ea6c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory",
    "left": 58.0,
    "top": 320.79999999999995,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92fa1289ea6c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.",
    "left": 58.0,
    "top": 335.79999999999995,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92fa1289ea6c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2022 – obecnie",
    "left": 407.0,
    "top": 303.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-92fa1289ea6c"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 320.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-92fa1289ea6c"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 58.0,
    "top": 357.79999999999995,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.3,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3922ff97dc67",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank",
    "left": 58.0,
    "top": 374.79999999999995,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3922ff97dc67",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.",
    "left": 58.0,
    "top": 389.79999999999995,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3922ff97dc67",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2019 – 2022",
    "left": 407.0,
    "top": 357.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-3922ff97dc67"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 374.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-3922ff97dc67"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 58.0,
    "top": 411.79999999999995,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.3,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1a98c8d4a4cf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services",
    "left": 58.0,
    "top": 428.79999999999995,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1a98c8d4a4cf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 58.0,
    "top": 443.79999999999995,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1a98c8d4a4cf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2016 – 2019",
    "left": 407.0,
    "top": 411.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-1a98c8d4a4cf"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 428.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-1a98c8d4a4cf"
  },
  {
    "category": "textarea",
    "content": "Asystentka ds. zgodności",
    "left": 58.0,
    "top": 465.79999999999995,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.3,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b398495fabd9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Operations",
    "left": 58.0,
    "top": 482.79999999999995,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b398495fabd9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Przygotowywała dokumentację klientów i wspierała kontrole jakości danych.",
    "left": 58.0,
    "top": 497.79999999999995,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b398495fabd9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2014 – 2016",
    "left": 407.0,
    "top": 465.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-b398495fabd9"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 482.79999999999995,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-b398495fabd9"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 58.0,
    "top": 530.8,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.9,
    "width": 479.0,
    "align": "center",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 545.3,
    "width": 479.0,
    "height": 0.9,
    "backgroundColor": "#98884D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 58.0,
    "top": 554.1999999999999,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.4,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-58fc45c3092d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 58.0,
    "top": 570.1999999999999,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.4,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-58fc45c3092d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 407.0,
    "top": 570.1999999999999,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-58fc45c3092d"
  },
  {
    "category": "textarea",
    "content": "ACAMS Academy",
    "left": 58.0,
    "top": 592.1999999999999,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.4,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2a779377e6ed",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Certyfikat AML Foundations",
    "left": 58.0,
    "top": 608.1999999999999,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.4,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#31312F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2a779377e6ed",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021",
    "left": 407.0,
    "top": 608.1999999999999,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#6A6C66",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-2a779377e6ed"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 58.0,
    "top": 641.1999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.9,
    "width": 479.0,
    "align": "center",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 655.6999999999999,
    "width": 479.0,
    "height": 0.9,
    "backgroundColor": "#98884D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna  ·  Screening PEP  ·  Sanctions  ·  SQL",
    "left": 58.0,
    "top": 664.5999999999999,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a89e9fe12ab8",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#353632",
    "left": 58.0,
    "top": 697.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.9,
    "width": 479.0,
    "align": "center",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 712.0999999999999,
    "width": 479.0,
    "height": 0.9,
    "backgroundColor": "#98884D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 58.0,
    "top": 720.9999999999999,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#98884D"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9f042356524e"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 177.75,
    "top": 720.9999999999999,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#98884D"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9f042356524e"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 720.9999999999999,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#98884D"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9f042356524e"
  },
  {
    "category": "textarea",
    "content": "Francuski — A2",
    "left": 417.25,
    "top": 720.9999999999999,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#4A4B47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#98884D"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9f042356524e"
  }
];

export const aureliaTemplate = AURELIA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
