/**
 * Aurelia template (`layouts: ["single"]`).
 *
 * Quiet-luxury single column with contrasting Bézier brushstrokes.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/aurelia.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const AURELIA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FEFDF9",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 58,
    "top": 42,
    "width": 1,
    "height": 756,
    "backgroundColor": "#DCD8CE",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 63,
    "top": 42,
    "width": 3,
    "height": 54,
    "backgroundColor": "#B3924F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 63,
    "top": 744,
    "width": 3,
    "height": 54,
    "backgroundColor": "#B3924F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 80,
    "top": 778,
    "width": 435,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 80,
    "top": 787,
    "width": 54,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "AURELIA  /  01",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#77736B",
    "left": 437,
    "top": 788,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "fixedToPage": true
  },
  {
    "category": "path",
    "pathKind": "flourish",
    "curves": [
      {
        "type": "M",
        "x": 0.72,
        "y": 0.02
      },
      {
        "type": "C",
        "x1": 1,
        "y1": 0.27,
        "x2": 0.08,
        "y2": 0.66,
        "x": 0.34,
        "y": 0.98
      }
    ],
    "left": 320.2712,
    "top": 24,
    "width": 90,
    "height": 132,
    "backgroundColor": "#D6D6D3",
    "borderWidth": 22,
    "filled": false,
    "zIndex": 1,
    "page": 1,
    "id": "aurelia-name-backdrop",
    "flowRole": "masthead"
  },
  {
    "category": "path",
    "pathKind": "wave",
    "curves": [
      {
        "type": "M",
        "x": 0.03,
        "y": 0.55
      },
      {
        "type": "C",
        "x1": 0.25,
        "y1": 0.23,
        "x2": 0.68,
        "y2": 0.78,
        "x": 0.97,
        "y": 0.46
      }
    ],
    "left": 72,
    "top": 36,
    "width": 291.56000000000006,
    "height": 52,
    "backgroundColor": "#3A3A36",
    "borderWidth": 44,
    "filled": false,
    "zIndex": 2,
    "page": 1,
    "id": "aurelia-nameplate",
    "flowRole": "masthead"
  },
  {
    "category": "path",
    "pathKind": "wave",
    "curves": [
      {
        "type": "M",
        "x": 0.02,
        "y": 0.52
      },
      {
        "type": "C",
        "x1": 0.28,
        "y1": 0.16,
        "x2": 0.72,
        "y2": 0.84,
        "x": 0.98,
        "y": 0.48
      }
    ],
    "left": 78,
    "top": 86,
    "width": 188,
    "height": 36,
    "backgroundColor": "#5A5A54",
    "borderWidth": 30,
    "filled": false,
    "zIndex": 2,
    "page": 1,
    "id": "aurelia-titleplate",
    "flowRole": "masthead"
  },
  {
    "category": "path",
    "pathKind": "arc",
    "curves": [
      {
        "type": "M",
        "x": 0.02,
        "y": 0.65
      },
      {
        "type": "C",
        "x1": 0.28,
        "y1": 0.05,
        "x2": 0.72,
        "y2": 0.95,
        "x": 0.98,
        "y": 0.25
      }
    ],
    "left": 80,
    "top": 28,
    "width": 129.55800000000002,
    "height": 12,
    "backgroundColor": "#B3924F",
    "borderWidth": 6,
    "filled": false,
    "zIndex": 3,
    "page": 1,
    "id": "aurelia-name-ink",
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 31,
    "fontFamily": "PlayfairDisplay",
    "color": "#FFFFFF",
    "left": 80,
    "top": 55,
    "zIndex": 4,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 82,
    "top": 100,
    "zIndex": 4,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa · linkedin.com/in/jkowalski ·…",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#77736B",
    "left": 82,
    "top": 128,
    "zIndex": 4,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 76,
    "top": 211.0,
    "width": 28,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#272724",
    "left": 116,
    "top": 204.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 271.97,
    "top": 213.0,
    "width": 243.02999999999997,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 116,
    "top": 228.0,
    "width": 399,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 76,
    "top": 297.0,
    "width": 28,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#272724",
    "left": 116,
    "top": 290.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 278.54,
    "top": 299.0,
    "width": 236.45999999999998,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 116,
    "top": 318.0,
    "width": 399,
    "height": 12,
    "fontSize": 8.2,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#77736B",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1595956ddfa2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 116,
    "top": 334.0,
    "width": 399,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1595956ddfa2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 116,
    "top": 389.0,
    "width": 399,
    "height": 12,
    "fontSize": 8.2,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#77736B",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-de792ba1d2db",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 116,
    "top": 405.0,
    "width": 399,
    "height": 28,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-de792ba1d2db",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 116,
    "top": 447.0,
    "width": 399,
    "height": 12,
    "fontSize": 8.2,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#77736B",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0efe80c11cd1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 116,
    "top": 463.0,
    "width": 399,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0efe80c11cd1",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 76,
    "top": 505.0,
    "width": 28,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#272724",
    "left": 116,
    "top": 498.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 219.41,
    "top": 507.0,
    "width": 295.59000000000003,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 116,
    "top": 522.0,
    "width": 399,
    "height": 14,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#272724",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db7ebd97b2d1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 116,
    "top": 540.0,
    "width": 399,
    "height": 14,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#272724",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db7ebd97b2d1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 116,
    "top": 558.0,
    "width": 399,
    "height": 12,
    "fontSize": 8.2,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#77736B",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db7ebd97b2d1",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 76,
    "top": 598.0,
    "width": 28,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#272724",
    "left": 116,
    "top": 591.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 212.84,
    "top": 600.0,
    "width": 302.15999999999997,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 116,
    "top": 615.0,
    "width": 399,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-706c79a0ca3a",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 76,
    "top": 657.0,
    "width": 28,
    "height": 4,
    "backgroundColor": "#B3924F",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#272724",
    "left": 116,
    "top": 650.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 173.42000000000002,
    "top": 659.0,
    "width": 341.58,
    "height": 1,
    "backgroundColor": "#DCD8CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 116,
    "top": 674.0,
    "width": 399,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.6,
    "letterSpacing": 0,
    "color": "#464540",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const aureliaTemplate = AURELIA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
