/**
 * Axis template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/axis.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const AXIS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 54,
    "top": 806,
    "width": 487,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#8A8A8A",
    "left": 526,
    "top": 812,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "DAWID SZYMAŃSKI",
    "fontSize": 23,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 50,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.4,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Specjalista ds. Bezpieczeństwa OT/ICS",
    "fontSize": 11.5,
    "fontFamily": "Inter",
    "color": "#E2740C",
    "left": 54,
    "top": 82,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.3,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/phone.png",
    "left": 54.0,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 662 415 730",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 69.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/email.png",
    "left": 154.49287109375,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "dawid.szymanski.ot@gmail.com",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 169.49287109375,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/linkedin.png",
    "left": 315.99619140625,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/dawid-szymanski",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 330.99619140625,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/github.png",
    "left": 54.0,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/dszymanski",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 69.0,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/website.png",
    "left": 181.9599609375,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "dawidszymanski.pl",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 196.9599609375,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/axis/location.png",
    "left": 290.1751953125,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Rzeszów",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 305.1751953125,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 54,
    "top": 139.0,
    "width": 487,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 176.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Specjalista ds. bezpieczeństwa systemów przemysłowych łączący doświadczenie inżynierskie w automatyce z wiedzą z zakresu cyberbezpieczeństwa OT/ICS. Wspieram segmentację sieci przemysłowych i ocenę podatności protokołów sterowania.",
    "left": 54,
    "top": 196.96,
    "width": 487,
    "height": 41,
    "fontSize": 9.0,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 258.96000000000004,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Specjalista ds. Bezpieczeństwa OT/ICS",
    "left": 182,
    "top": 279.92,
    "width": 359,
    "height": 14,
    "fontSize": 11.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "textarea",
    "content": "Trident Industrial Sp.J",
    "left": 182,
    "top": 297.92,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "textarea",
    "content": "• Oceniam podatności protokołów przemysłowych (Modbus, Profinet) w sieciach klientów.\n• Wspieram wdrożenie segmentacji sieci OT od IT zgodnie z normą IEC 62443.\n• Monitoruję anomalie w ruchu sieciowym systemów SCADA.\n• Przygotowuję rekomendacje bezpieczeństwa dla działów utrzymania ruchu.",
    "left": 182,
    "top": 314.92,
    "width": 359,
    "height": 67,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "textarea",
    "content": "Marzec 2023 – obecnie",
    "left": 54,
    "top": 279.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "textarea",
    "content": "Rzeszów",
    "left": 54,
    "top": 291.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 282.92,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "line",
    "left": 161,
    "top": 289.92,
    "width": 1,
    "height": 102.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-3cbc085f57bd"
  },
  {
    "category": "textarea",
    "content": "Inżynier Automatyk",
    "left": 182,
    "top": 391.92,
    "width": 359,
    "height": 14,
    "fontSize": 11.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "textarea",
    "content": "Polbryt Przemysł Sp. z o.o.",
    "left": 182,
    "top": 409.92,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "textarea",
    "content": "• Programowałem i serwisowałem sterowniki PLC linii produkcyjnych.\n• Projektowałem szafy sterownicze i dokumentację techniczną.",
    "left": 182,
    "top": 426.92,
    "width": 359,
    "height": 27,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "textarea",
    "content": "Sierpień 2020 – Luty 2023",
    "left": 54,
    "top": 391.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "textarea",
    "content": "Rzeszów",
    "left": 54,
    "top": 403.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 394.92,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "line",
    "left": 161,
    "top": 401.92,
    "width": 1,
    "height": 52.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-8f490173a005"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 474.92,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister inżynier automatyki i robotyki",
    "left": 182,
    "top": 495.88,
    "width": 359,
    "height": 14,
    "fontSize": 10.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-542170526755"
  },
  {
    "category": "textarea",
    "content": "Politechnika Rzeszowska",
    "left": 182,
    "top": 513.88,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-542170526755"
  },
  {
    "category": "textarea",
    "content": "• Praca magisterska dotycząca bezpieczeństwa protokołów komunikacji przemysłowej.",
    "left": 182,
    "top": 530.88,
    "width": 359,
    "height": 27,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-542170526755"
  },
  {
    "category": "textarea",
    "content": "ukończono czerwiec 2020",
    "left": 54,
    "top": 495.88,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-542170526755"
  },
  {
    "category": "textarea",
    "content": "Rzeszów",
    "left": 54,
    "top": 507.88,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-542170526755"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 498.88,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-542170526755"
  },
  {
    "category": "line",
    "left": 161,
    "top": 505.88,
    "width": 1,
    "height": 52.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-542170526755"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 578.88,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "IEC 62443",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 54.0,
    "top": 599.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 54.0,
    "top": 612.84,
    "width": 49.18896484375001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "Modbus",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 121.18896484375,
    "top": 599.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 121.18896484375,
    "top": 612.84,
    "width": 38.62011718750001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "Profinet",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 177.80908203125,
    "top": 599.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 177.80908203125,
    "top": 612.84,
    "width": 37.55224609375001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "systemy SCADA",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 233.361328125,
    "top": 599.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 233.361328125,
    "top": 612.84,
    "width": 73.48632812500001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "programowanie PLC",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 324.84765625,
    "top": 599.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 324.84765625,
    "top": 612.84,
    "width": 90.64257812500001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "segmentacja sieci OT/IT",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 54.0,
    "top": 623.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 54.0,
    "top": 636.84,
    "width": 107.06054687500001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "Wireshark",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 179.060546875,
    "top": 623.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 179.060546875,
    "top": 636.84,
    "width": 47.13671875000001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "Python",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 244.197265625,
    "top": 623.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "line",
    "left": 244.197265625,
    "top": 636.84,
    "width": 33.7861328125,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-93aeec21db0c"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 668.84,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — B2",
    "left": 54.0,
    "top": 689.8000000000001,
    "width": 113.75,
    "height": 13,
    "fontSize": 9.0,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E7391"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-31f2d0503773"
  },
  {
    "category": "textarea",
    "content": "niemiecki — B1",
    "left": 175.75,
    "top": 689.8000000000001,
    "width": 113.75,
    "height": 13,
    "fontSize": 9.0,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E7391"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-31f2d0503773"
  }
];

export const axisTemplate = AXIS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
