/**
 * Axis template (`layouts: ["single"]`).
 *
 * Timeline single column with date gutter, skill chips, and a
 * four-column languages grid.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/axis.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const AXIS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 54,
    "top": 806,
    "width": 487,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#8A8A8A",
    "left": 526,
    "top": 812,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "JAN KOWALSKI",
    "fontSize": 23,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 50,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.4,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 11.5,
    "fontFamily": "Inter",
    "color": "#E2740C",
    "left": 54,
    "top": 82,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.3,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/phone.png",
    "left": 54.0,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 69.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/email.png",
    "left": 157.55830078125,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 172.55830078125,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/linkedin.png",
    "left": 288.1259765625,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 303.1259765625,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/github.png",
    "left": 421.22998046875,
    "top": 104.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 436.22998046875,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/website.png",
    "left": 54.0,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 69.0,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/axis/location.png",
    "left": 141.98759765625,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.6,
    "fontFamily": "Inter",
    "color": "#3D3D3D",
    "left": 156.98759765625,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 54,
    "top": 139.0,
    "width": 487,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 176.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 54,
    "top": 196.96,
    "width": 487,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 244.96,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 182,
    "top": 265.92,
    "width": 359,
    "height": 14,
    "fontSize": 11.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aacbc731a582",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners",
    "left": 182,
    "top": 283.92,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aacbc731a582",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 182,
    "top": 300.92,
    "width": 359,
    "height": 54,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aacbc731a582",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021 – obecnie",
    "left": 54,
    "top": 265.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-aacbc731a582"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 54,
    "top": 277.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-aacbc731a582"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 268.92,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-aacbc731a582"
  },
  {
    "category": "line",
    "left": 161,
    "top": 275.92,
    "width": 1,
    "height": 89.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-aacbc731a582"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 182,
    "top": 364.92,
    "width": 359,
    "height": 14,
    "fontSize": 11.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-510fe28d94f6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group",
    "left": 182,
    "top": 382.92,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-510fe28d94f6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 182,
    "top": 399.92,
    "width": 359,
    "height": 27,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-510fe28d94f6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2016 – 2021",
    "left": 54,
    "top": 364.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-510fe28d94f6"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 54,
    "top": 376.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-510fe28d94f6"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 367.92,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-510fe28d94f6"
  },
  {
    "category": "line",
    "left": 161,
    "top": 374.92,
    "width": 1,
    "height": 62.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-510fe28d94f6"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 182,
    "top": 436.92,
    "width": 359,
    "height": 14,
    "fontSize": 11.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92f626cef583",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting",
    "left": 182,
    "top": 454.92,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92f626cef583",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 182,
    "top": 471.92,
    "width": 359,
    "height": 14,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92f626cef583",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2013 – 2016",
    "left": 54,
    "top": 436.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-92f626cef583"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 54,
    "top": 448.92,
    "width": 100,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 10.5,
    "letterSpacing": 0,
    "color": "#8A8A8A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-92f626cef583"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 439.92,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-92f626cef583"
  },
  {
    "category": "line",
    "left": 161,
    "top": 446.92,
    "width": 1,
    "height": 39.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-92f626cef583"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 506.92,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 182,
    "top": 527.88,
    "width": 359,
    "height": 14,
    "fontSize": 10.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2E7391",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1cc8be9aaa94",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 182,
    "top": 545.88,
    "width": 359,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#E2740C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1cc8be9aaa94",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 54,
    "top": 527.88,
    "width": 100,
    "height": 11,
    "fontSize": 8.4,
    "lineHeight": 11,
    "letterSpacing": 0,
    "color": "#1B3357",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-1cc8be9aaa94"
  },
  {
    "category": "circle",
    "left": 158,
    "top": 530.88,
    "width": 7,
    "height": 7,
    "backgroundColor": "#1B3357",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-1cc8be9aaa94"
  },
  {
    "category": "line",
    "left": 161,
    "top": 537.88,
    "width": 1,
    "height": 21.0,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "record-overlay",
    "flowGroup": "record-1cc8be9aaa94"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 579.88,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "Strategia",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 54.0,
    "top": 600.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 54.0,
    "top": 613.84,
    "width": 42.10498046875001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Leadership",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 114.10498046875,
    "top": 600.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 114.10498046875,
    "top": 613.84,
    "width": 51.29833984375001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "P&L",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 183.4033203125,
    "top": 600.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 183.4033203125,
    "top": 613.84,
    "width": 20.633300781250004,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Negocjacje",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 222.03662109375,
    "top": 600.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 222.03662109375,
    "top": 613.84,
    "width": 51.88720703125001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Transformacja organizacyjna",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#2E7391",
    "left": 291.923828125,
    "top": 600.84,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 291.923828125,
    "top": 613.84,
    "width": 127.90820312500001,
    "height": 1,
    "backgroundColor": "#D7DBE0",
    "zIndex": 2,
    "page": 1,
    "flowGroup": "record-f4592e610f70",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.6,
    "fontFamily": "Inter",
    "color": "#1B3357",
    "left": 54,
    "top": 645.84,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 54.0,
    "top": 666.8000000000001,
    "width": 113.75,
    "height": 13,
    "fontSize": 9.0,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#2E7391"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-11cdf3e720a2"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 175.75,
    "top": 666.8000000000001,
    "width": 113.75,
    "height": 13,
    "fontSize": 9.0,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E7391"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-11cdf3e720a2"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 297.5,
    "top": 666.8000000000001,
    "width": 113.75,
    "height": 13,
    "fontSize": 9.0,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#3D3D3D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E7391"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-11cdf3e720a2"
  }
];

export const axisTemplate = AXIS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
