/**
 * Blueprint template (`layouts: ["single"]`).
 *
 * Technical-schematic single column with steel-blue registration marks.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/blueprint.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const BLUEPRINT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F2F2F3",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 76,
    "top": 783,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#5D5D60",
    "left": 505,
    "top": 791,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 96.0,
    "top": 66.0,
    "width": 403.0,
    "height": 31,
    "fontSize": 27.0,
    "lineHeight": 31.0,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "left": 96.0,
    "top": 101.0,
    "width": 403.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 1.8,
    "color": "#416180",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa · linkedin.com/in/jkowalski · github.com/jkowalski · jankowalski.pl",
    "left": 96.0,
    "top": 126.0,
    "width": 403.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#424244",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 76,
    "top": 48.0,
    "width": 443,
    "height": 123.0,
    "backgroundColor": "#B5D9FD",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 207.71,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 76,
    "top": 216.71,
    "width": 443,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 265.71000000000004,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 280.42,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 76,
    "top": 289.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e1d5d2bd19f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 76,
    "top": 308.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e1d5d2bd19f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 76,
    "top": 324.42,
    "width": 443,
    "height": 42,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e1d5d2bd19f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 76,
    "top": 376.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-091e0ee3bdb0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 76,
    "top": 395.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-091e0ee3bdb0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 76,
    "top": 411.42,
    "width": 443,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-091e0ee3bdb0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 76,
    "top": 449.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-107775d34b23",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 76,
    "top": 468.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-107775d34b23",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 76,
    "top": 484.42,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-107775d34b23",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 519.4200000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 534.1300000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 76,
    "top": 543.1300000000001,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d7e8b66d0afe",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 76,
    "top": 561.1300000000001,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d7e8b66d0afe",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 76,
    "top": 579.1300000000001,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d7e8b66d0afe",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 612.1300000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 626.8400000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 76,
    "top": 635.8400000000001,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4046a3246a03",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 670.8400000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 685.5500000000002,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 76.0,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7fdcd2fbc989"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 186.75,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7fdcd2fbc989"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 297.5,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7fdcd2fbc989"
  }
];

export const blueprintTemplate = BLUEPRINT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
