/**
 * Blueprint template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/blueprint.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const BLUEPRINT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F2F2F3",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 76,
    "top": 783,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#5D5D60",
    "left": 505,
    "top": 791,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Bartosz Wojciechowski",
    "left": 96.0,
    "top": 66.0,
    "width": 403.0,
    "height": 31,
    "fontSize": 27.0,
    "lineHeight": 31.0,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "ANALITYK SOC",
    "left": 96.0,
    "top": 101.0,
    "width": 403.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 1.8,
    "color": "#416180",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "bartosz.wojciechowski@mail.com · +48 795 340 128 · Białystok · linkedin.com/in/bartosz-woj… · github.com/bwojciechowski · bartoszw.dev",
    "left": 96.0,
    "top": 126.0,
    "width": 403.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#424244",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 76,
    "top": 48.0,
    "width": 443,
    "height": 123.0,
    "backgroundColor": "#B5D9FD",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 207.71,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityk SOC z doświadczeniem w monitorowaniu infrastruktury krytycznej i obsłudze alertów bezpieczeństwa. Wcześniejsze doświadczenie w utrzymaniu sieci przemysłowych daje mi praktyczne zrozumienie środowisk OT.",
    "left": 76,
    "top": 216.71,
    "width": 443,
    "height": 42,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 279.71000000000004,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 294.42,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityk SOC",
    "left": 76,
    "top": 303.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65d2ef156a85"
  },
  {
    "category": "textarea",
    "content": "GridWorks Automatyka   ·   Białystok   ·   Styczeń 2023 – obecnie",
    "left": 76,
    "top": 322.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65d2ef156a85"
  },
  {
    "category": "textarea",
    "content": "• Monitoruję alerty bezpieczeństwa w systemie SIEM dla infrastruktury klienta.\n• Prowadzę triage incydentów i eskalację zgodnie z ustalonymi procedurami.\n• Analizuję logi sieciowe i systemowe w poszukiwaniu wskaźników kompromitacji.",
    "left": 76,
    "top": 338.42,
    "width": 443,
    "height": 42,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65d2ef156a85"
  },
  {
    "category": "textarea",
    "content": "Technik Sieci",
    "left": 76,
    "top": 390.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-714b158b33b0"
  },
  {
    "category": "textarea",
    "content": "Northgate Logistics   ·   Białystok   ·   Wrzesień 2021 – Grudzień 2022",
    "left": 76,
    "top": 409.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-714b158b33b0"
  },
  {
    "category": "textarea",
    "content": "• Konfigurowałem i utrzymywałem urządzenia sieciowe w oddziałach firmy.",
    "left": 76,
    "top": 425.42,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-714b158b33b0"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 460.42,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 475.13,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Inżynier informatyki — specjalność: Sieci i bezpieczeństwo",
    "left": 76,
    "top": 484.13,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5745879576d"
  },
  {
    "category": "textarea",
    "content": "Politechnika Białostocka",
    "left": 76,
    "top": 502.13,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5745879576d"
  },
  {
    "category": "textarea",
    "content": "Białystok   ·   ukończono czerwiec 2021",
    "left": 76,
    "top": 520.13,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5745879576d"
  },
  {
    "category": "textarea",
    "content": "• Praca inżynierska dotycząca detekcji anomalii w ruchu sieciowym.",
    "left": 76,
    "top": 536.13,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5745879576d"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 571.13,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 585.84,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "analiza SIEM/logów  ·  triage alertów  ·  Wireshark  ·  Tcpdump  ·  Nmap  ·  MITRE ATT&CK  ·  podstawy IDS/firewall  ·  Python  ·  SQL  ·  Linux",
    "left": 76,
    "top": 594.84,
    "width": 443,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-62dfa0b6b1a6"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 643.84,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 658.5500000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — B2",
    "left": 76.0,
    "top": 667.5500000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-56a5a9de5fe2"
  },
  {
    "category": "textarea",
    "content": "rosyjski — B1",
    "left": 186.75,
    "top": 667.5500000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 11,
        "end": 13,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-56a5a9de5fe2"
  },
  {
    "category": "textarea",
    "content": "ukraiński — A2",
    "left": 297.5,
    "top": 667.5500000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-56a5a9de5fe2"
  }
];

export const blueprintTemplate = BLUEPRINT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
