/**
 * Blueprint template (`layouts: ["single"]`).
 *
 * Technical-schematic single column with steel-blue registration marks.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/blueprint.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const BLUEPRINT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F2F2F3",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 76,
    "top": 783,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#5D5D60",
    "left": 505,
    "top": 791,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 96.0,
    "top": 66.0,
    "width": 403.0,
    "height": 31,
    "fontSize": 27.0,
    "lineHeight": 31.0,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "ANALITYCZKA AML I COMPLIANCE",
    "left": 96.0,
    "top": 101.0,
    "width": 403.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 1.8,
    "color": "#416180",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "julia.bernat@email.com · +48 512 340 780 · Warszawa · linkedin.com/in/jbernat · github.com/jbernat · juliabernat.pl",
    "left": 96.0,
    "top": 126.0,
    "width": 403.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#424244",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 76,
    "top": 48.0,
    "width": 443,
    "height": 123.0,
    "backgroundColor": "#B5D9FD",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 43.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 47.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 75.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 71.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 518.5,
    "top": 166.0,
    "width": 1.0,
    "height": 10.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514.0,
    "top": 170.5,
    "width": 10.0,
    "height": 1.0,
    "backgroundColor": "#5D5D60",
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 207.71,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 76,
    "top": 216.71,
    "width": 443,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 265.71000000000004,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 280.42,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 76,
    "top": 289.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-39016bbadd39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 76,
    "top": 308.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-39016bbadd39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 76,
    "top": 324.42,
    "width": 443,
    "height": 42,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-39016bbadd39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 76,
    "top": 376.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-039a79e35bbb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 76,
    "top": 395.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-039a79e35bbb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 76,
    "top": 411.42,
    "width": 443,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-039a79e35bbb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 76,
    "top": 449.42,
    "width": 443,
    "height": 15,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d23b7df46ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 76,
    "top": 468.42,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d23b7df46ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 76,
    "top": 484.42,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d23b7df46ba",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 519.4200000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 534.1300000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 76,
    "top": 543.1300000000001,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f9a7226be704",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 76,
    "top": 561.1300000000001,
    "width": 443,
    "height": 14,
    "fontSize": 10.8,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f9a7226be704",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 76,
    "top": 579.1300000000001,
    "width": 443,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#5D5D60",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f9a7226be704",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 612.1300000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 626.8400000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 76,
    "top": 635.8400000000001,
    "width": 443,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-605cc959dc71",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 10.2,
    "fontFamily": "Inter",
    "color": "#416180",
    "left": 76,
    "top": 670.8400000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 685.5500000000002,
    "width": 443,
    "height": 1,
    "backgroundColor": "#B5D9FD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 76.0,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-53e0db2fa588"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 186.75,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-53e0db2fa588"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 694.5500000000002,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#1D1F20",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#416180"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-53e0db2fa588"
  }
];

export const blueprintTemplate = BLUEPRINT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
