/**
 * Cadenza template (`layouts: ["sidebar", "icons"]`).
 *
 * Swiss-inspired cream editorial layout with a white information rail
 * and fixed rectangle, circle, and ellipse page furniture.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cadenza.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CADENZA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F5F1E8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 210.0,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 0,
    "width": 1.0,
    "height": 842,
    "backgroundColor": "#B38B6D",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 160.5,
    "backgroundColor": "#FFFFFF",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#808080",
    "left": 531.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 67.5,
    "top": 46.0,
    "width": 460.0,
    "height": 34,
    "fontSize": 30.0,
    "lineHeight": 34.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "ANALITYCZKA AML I COMPLIANCE",
    "left": 67.5,
    "top": 86.0,
    "width": 460.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 2.0,
    "color": "#B38B6D",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/sterling/phone.png",
    "left": 110.9471,
    "top": 111.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "sterling-contact",
    "alt": "Contact icon"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#808080",
    "left": 126.9471,
    "top": 111.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "sterling-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/sterling/email.png",
    "left": 215.4985,
    "top": 111.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "sterling-contact",
    "alt": "Contact icon"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#808080",
    "left": 231.4985,
    "top": 111.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "sterling-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/sterling/linkedin.png",
    "left": 357.6405,
    "top": 111.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "sterling-contact",
    "alt": "Contact icon"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#808080",
    "left": 373.6405,
    "top": 111.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "sterling-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/sterling/location.png",
    "left": 265.248,
    "top": 127.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "sterling-contact",
    "alt": "Contact icon"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#808080",
    "left": 281.248,
    "top": 127.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "sterling-contact"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 160.5,
    "width": 511.0,
    "height": 1,
    "backgroundColor": "#B38B6D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "sterling-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 111.0,
        "maxWidth": 460.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 9.4,
        "colorHex": "#6B7684"
      },
      "icon": {
        "sizePt": 13.0,
        "theme": "sterling"
      },
      "metrics": {
        "iconGap": 16.0,
        "itemPad": 14.0,
        "lineStep": 16.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ]
    },
    "contactBandId": "sterling-contact"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 34.0,
    "top": 190.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 206.78,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 34.0,
    "top": 218.18,
    "width": 152.0,
    "height": 73,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 34.0,
    "top": 317.18,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 333.46,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• AML/KYC\n• Monitoring\n• CDD/EDD\n• Raporty SAR\n• Analiza transakcyjna\n• Screening PEP\n• Sanctions\n• SQL",
    "left": 34.0,
    "top": 338.18,
    "width": 152.0,
    "height": 97.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 34.0,
    "top": 447.18,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 463.46,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nNiemiecki - B2\nFrancuski - A2",
    "left": 34.0,
    "top": 468.18,
    "width": 152.0,
    "height": 49.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "CERTYFIKATY",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 34.0,
    "top": 529.18,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 545.4599999999999,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• ACAMS AML Foundations\n• ICA Certificate in Compliance\n• Szkolenie CDD/EDD",
    "left": 34.0,
    "top": 550.18,
    "width": 152.0,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "ZAINTERESOWANIA",
    "fontSize": 9.4,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 34.0,
    "top": 599.18,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 615.4599999999999,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Automatyzacja procesów\n• Prawo finansowe\n• Analiza danych",
    "left": 34.0,
    "top": 620.18,
    "width": 152.0,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 12.0,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 245.0,
    "top": 190.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 209.1,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 245.0,
    "top": 218.1,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-121b745d5bca",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 245.0,
    "top": 237.1,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-121b745d5bca",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 245.0,
    "top": 253.1,
    "width": 300.0,
    "height": 83,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-121b745d5bca",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 245.0,
    "top": 346.1,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5e6042659df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 245.0,
    "top": 365.1,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5e6042659df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 245.0,
    "top": 381.1,
    "width": 300.0,
    "height": 56,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5e6042659df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 245.0,
    "top": 447.1,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5f50855849f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 245.0,
    "top": 466.1,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5f50855849f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 245.0,
    "top": 482.1,
    "width": 300.0,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a5f50855849f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Asystentka ds. zgodności",
    "left": 245.0,
    "top": 520.1,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c05ec894c4",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Operations   ·   Kraków   ·   2014 – 2016",
    "left": 245.0,
    "top": 539.1,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c05ec894c4",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Przygotowywała dokumentację klientów i wspierała kontrole jakości danych.\n• Koordynowała odpowiedzi na zapytania operacyjne zespołów sprzedaży i ryzyka.",
    "left": 245.0,
    "top": 555.1,
    "width": 300.0,
    "height": 56,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c05ec894c4",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 12.0,
    "fontFamily": "Inter",
    "color": "#000000",
    "left": 245.0,
    "top": 632.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 650.7,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 245.0,
    "top": 659.7,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91adc72105b8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 245.0,
    "top": 677.7,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91adc72105b8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 245.0,
    "top": 695.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91adc72105b8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Certyfikat AML Foundations",
    "left": 245.0,
    "top": 717.7,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c34e50375f64",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "ACAMS Academy",
    "left": 245.0,
    "top": 735.7,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#000000",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c34e50375f64",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021",
    "left": 245.0,
    "top": 753.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#808080",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c34e50375f64",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 20,
    "top": 22,
    "width": 36,
    "height": 36,
    "backgroundColor": "#B38B6D",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 33,
    "top": 35,
    "width": 10,
    "height": 10,
    "backgroundColor": "#B38B6D",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 468,
    "top": 27,
    "width": 84,
    "height": 19,
    "backgroundColor": "#B38B6D",
    "filled": false,
    "borderWidth": 1.1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 468,
    "top": 55,
    "width": 84,
    "height": 1.0,
    "backgroundColor": "#B38B6D",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 548,
    "top": 772,
    "width": 18,
    "height": 18,
    "backgroundColor": "#B38B6D",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 553,
    "top": 777,
    "width": 8,
    "height": 8,
    "backgroundColor": "#F5F1E8",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  }
];

export const cadenzaTemplate = CADENZA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
