/**
 * Cadenza template (`layouts: ["single", "icons"]`).
 *
 * Warm editorial single column with centered serif identity, pale section
 * bands, and an exact-anchor date rail shared with Meridian.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cadenza.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CADENZA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFEFB",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 796,
    "width": 479.0,
    "height": 0.7,
    "backgroundColor": "#CCD4D5",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#9B735A",
    "left": 292.5,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 58.0,
    "top": 47.0,
    "width": 479.0,
    "height": 32,
    "fontSize": 27.5,
    "lineHeight": 32.0,
    "letterSpacing": 3.6,
    "color": "#263238",
    "fontFamily": "PlayfairDisplay",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 58.0,
    "top": 84.0,
    "width": 479.0,
    "height": 11,
    "fontSize": 8.2,
    "lineHeight": 11.0,
    "letterSpacing": 2.1,
    "color": "#9B735A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/phone.png",
    "left": 70.42119999999997,
    "top": 107.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 80.92119999999997,
    "top": 107.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/email.png",
    "left": 152.02439999999999,
    "top": 107.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 162.52439999999999,
    "top": 107.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/linkedin.png",
    "left": 262.4204,
    "top": 107.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 272.9204,
    "top": 107.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/github.png",
    "left": 371.49159999999995,
    "top": 107.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 381.99159999999995,
    "top": 107.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/website.png",
    "left": 466.64519999999993,
    "top": 107.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 477.14519999999993,
    "top": 107.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cadenza/location.png",
    "left": 273.674,
    "top": 120.0,
    "width": 9.0,
    "height": 9.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#72797B",
    "left": 284.174,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 144.0,
    "width": 479.0,
    "height": 0.8,
    "backgroundColor": "#CCD4D5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "cadenza-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 107.0,
        "maxWidth": 479.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 7.2,
        "colorHex": "#72797B"
      },
      "icon": {
        "sizePt": 9.0,
        "theme": "cadenza"
      },
      "metrics": {
        "iconGap": 10.5,
        "itemPad": 14.0,
        "lineStep": 13.0,
        "charWidth": 4.5
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "cadenza-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 58.0,
          "top": 84.0,
          "width": 479.0,
          "height": 11,
          "fontSizePt": 8.2,
          "lineHeight": 11.0,
          "fontFamily": "Montserrat",
          "colorHex": "#9B735A",
          "letterSpacing": 2.1,
          "align": "center",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "uppercase",
          "bold": false,
          "italic": false,
          "underline": false,
          "zIndex": 3
        },
        "blockPt": 23.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "cadenza-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 163.0,
    "width": 479.0,
    "height": 18.0,
    "backgroundColor": "#E8EDEE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 163.0,
    "width": 3.0,
    "height": 18.0,
    "backgroundColor": "#9B735A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263238",
    "left": 219.4823,
    "top": 168.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 58.0,
    "top": 189.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 233.0,
    "width": 479.0,
    "height": 18.0,
    "backgroundColor": "#E8EDEE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 233.0,
    "width": 3.0,
    "height": 18.0,
    "backgroundColor": "#9B735A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263238",
    "left": 219.12619999999998,
    "top": 238.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 58.0,
    "top": 259.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a6e326767893",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory",
    "left": 58.0,
    "top": 276.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a6e326767893",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 58.0,
    "top": 291.0,
    "width": 479.0,
    "height": 34,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a6e326767893",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2022 – obecnie",
    "left": 407.0,
    "top": 259.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-a6e326767893"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 276.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-a6e326767893"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 58.0,
    "top": 335.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bc707e2c5d08",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank",
    "left": 58.0,
    "top": 352.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bc707e2c5d08",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 58.0,
    "top": 367.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bc707e2c5d08",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2019 – 2022",
    "left": 407.0,
    "top": 335.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-bc707e2c5d08"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 352.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-bc707e2c5d08"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 58.0,
    "top": 400.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b296297b0f34",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services",
    "left": 58.0,
    "top": 417.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b296297b0f34",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 58.0,
    "top": 432.0,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b296297b0f34",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2016 – 2019",
    "left": 407.0,
    "top": 400.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-b296297b0f34"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 417.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-b296297b0f34"
  },
  {
    "category": "textarea",
    "content": "Asystentka ds. zgodności",
    "left": 58.0,
    "top": 454.0,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.6,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9c8995190f1a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Operations",
    "left": 58.0,
    "top": 471.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9c8995190f1a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Przygotowywała dokumentację klientów i wspierała kontrole jakości danych.\n• Koordynowała odpowiedzi na zapytania operacyjne zespołów sprzedaży i ryzyka.",
    "left": 58.0,
    "top": 486.0,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9c8995190f1a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2014 – 2016",
    "left": 407.0,
    "top": 454.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-9c8995190f1a"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 471.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-9c8995190f1a"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 530.0,
    "width": 479.0,
    "height": 18.0,
    "backgroundColor": "#E8EDEE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 530.0,
    "width": 3.0,
    "height": 18.0,
    "backgroundColor": "#9B735A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263238",
    "left": 254.251,
    "top": 535.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 58.0,
    "top": 556.0,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-de5802332fa4",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 58.0,
    "top": 572.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-de5802332fa4",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 407.0,
    "top": 556.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-de5802332fa4"
  },
  {
    "category": "textarea",
    "content": "Certyfikat AML Foundations",
    "left": 58.0,
    "top": 593.0,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#263238",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6b770a323f33",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "ACAMS Academy",
    "left": 58.0,
    "top": 609.0,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6b770a323f33",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021",
    "left": 407.0,
    "top": 593.0,
    "width": 130.0,
    "height": 10.4,
    "fontSize": 7.7,
    "lineHeight": 10.4,
    "letterSpacing": 0,
    "color": "#72797B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-6b770a323f33"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 641.0,
    "width": 479.0,
    "height": 18.0,
    "backgroundColor": "#E8EDEE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 641.0,
    "width": 3.0,
    "height": 18.0,
    "backgroundColor": "#9B735A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263238",
    "left": 258.962,
    "top": 646.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna  ·  Screening PEP  ·  Sanctions  ·  SQL",
    "left": 58.0,
    "top": 667.0,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e1a9ed1c8c5",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 700.0,
    "width": 479.0,
    "height": 18.0,
    "backgroundColor": "#E8EDEE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 700.0,
    "width": 3.0,
    "height": 18.0,
    "backgroundColor": "#9B735A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263238",
    "left": 280.16470000000004,
    "top": 705.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 58.0,
    "top": 726.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#9B735A"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bbff19361c90"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 177.75,
    "top": 726.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9B735A"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bbff19361c90"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 726.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9B735A"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bbff19361c90"
  },
  {
    "category": "textarea",
    "content": "Francuski — A2",
    "left": 417.25,
    "top": 726.0,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.4,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#42494B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9B735A"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bbff19361c90"
  }
];

export const cadenzaTemplate = CADENZA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
