/**
 * Cardinal template (`layouts: ["icons"]`).
 *
 * Oxblood accent with icon-in-gutter section headings.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cardinal.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CARDINAL_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF9",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 72,
    "top": 800,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Helvetica",
    "color": "#6E6E6E",
    "left": 522,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#24201E",
    "left": 72,
    "top": 50,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 0.15,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 72,
    "top": 92,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/phone.png",
    "left": 72.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/email.png",
    "left": 189.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 205.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/linkedin.png",
    "left": 343.8,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 359.8,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/github.png",
    "left": 72.0,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/website.png",
    "left": 205.2,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 221.2,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/location.png",
    "left": 316.8,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 332.8,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 72,
    "top": 158.0,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/summary.png",
    "left": 72,
    "top": 195.0,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 195.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 266.466,
    "top": 194.33378125,
    "width": 278.534,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 72,
    "top": 224.2,
    "width": 473,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/experience.png",
    "left": 72,
    "top": 273.2,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 273.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 274.012,
    "top": 272.53378125,
    "width": 270.988,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 72,
    "top": 302.4,
    "width": 473,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2b3678fb60b1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 72,
    "top": 321.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2b3678fb60b1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 72,
    "top": 337.4,
    "width": 473,
    "height": 42,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2b3678fb60b1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 72,
    "top": 389.4,
    "width": 473,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e27302218178",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 72,
    "top": 408.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e27302218178",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 72,
    "top": 424.4,
    "width": 473,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e27302218178",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 72,
    "top": 462.4,
    "width": 473,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91d902467901",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 72,
    "top": 481.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91d902467901",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 72,
    "top": 497.4,
    "width": 473,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-91d902467901",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/education.png",
    "left": 72,
    "top": 532.4,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 532.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 206.09799999999998,
    "top": 531.73378125,
    "width": 338.90200000000004,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 72,
    "top": 561.6,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5f13a95763b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 72,
    "top": 578.6,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5f13a95763b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 72,
    "top": 595.6,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5f13a95763b",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/skills.png",
    "left": 72,
    "top": 628.6,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 628.6,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 198.552,
    "top": 627.93378125,
    "width": 346.448,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 72.0,
    "top": 657.8000000000001,
    "width": 64.16093749999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "text",
    "content": "AML/KYC",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 82.0,
    "top": 667.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "rectangle",
    "left": 144.1609375,
    "top": 657.8000000000001,
    "width": 68.8203125,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "text",
    "content": "Monitoring",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 154.1609375,
    "top": 667.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "rectangle",
    "left": 220.98125,
    "top": 657.8000000000001,
    "width": 63.9546875,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "text",
    "content": "CDD/EDD",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 230.98125,
    "top": 667.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "rectangle",
    "left": 292.9359375,
    "top": 657.8000000000001,
    "width": 77.0140625,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "text",
    "content": "Raporty SAR",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 302.9359375,
    "top": 667.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "rectangle",
    "left": 377.95,
    "top": 657.8000000000001,
    "width": 113.53906249999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "text",
    "content": "Analiza transakcyjna",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 387.95,
    "top": 667.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-73f3417d6dc5"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/languages.png",
    "left": 72,
    "top": 698.4000000000001,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 698.4000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 153.276,
    "top": 697.7337812500001,
    "width": 391.724,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 72.0,
    "top": 727.6000000000001,
    "width": 110.25,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#9E2532"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-33bb673a1a1e"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 190.25,
    "top": 727.6000000000001,
    "width": 110.25,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9E2532"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-33bb673a1a1e"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 308.5,
    "top": 727.6000000000001,
    "width": 110.25,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9E2532"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-33bb673a1a1e"
  }
];

export const cardinalTemplate = CARDINAL_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
