/**
 * Cardinal template (`layouts: ["icons"]`).
 *
 * Oxblood accent with icon-in-gutter section headings.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cardinal.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CARDINAL_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF9",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 72,
    "top": 800,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Helvetica",
    "color": "#6E6E6E",
    "left": 522,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#24201E",
    "left": 72,
    "top": 50,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 0.15,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 72,
    "top": 92,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/phone.png",
    "left": 72.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/email.png",
    "left": 189.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 205.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/linkedin.png",
    "left": 343.8,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 359.8,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/github.png",
    "left": 72.0,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/website.png",
    "left": 216.0,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 232.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/location.png",
    "left": 327.6,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 343.6,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 72,
    "top": 158.0,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/summary.png",
    "left": 72,
    "top": 195.0,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 195.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 266.466,
    "top": 194.33378125,
    "width": 278.534,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 72,
    "top": 224.2,
    "width": 473,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/experience.png",
    "left": 72,
    "top": 273.2,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 273.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 274.012,
    "top": 272.53378125,
    "width": 270.988,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 72,
    "top": 306.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2a5f603c6e74",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 72,
    "top": 322.4,
    "width": 473,
    "height": 42,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2a5f603c6e74",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 72,
    "top": 378.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-79043e873e18",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 72,
    "top": 394.4,
    "width": 473,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-79043e873e18",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 72,
    "top": 436.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8140c77d09a2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 72,
    "top": 452.4,
    "width": 473,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8140c77d09a2",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/education.png",
    "left": 72,
    "top": 487.4,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 487.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 206.09799999999998,
    "top": 486.73378125,
    "width": 338.90200000000004,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 72,
    "top": 516.5999999999999,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a45054783564",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 72,
    "top": 533.5999999999999,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a45054783564",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 72,
    "top": 550.5999999999999,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a45054783564",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/skills.png",
    "left": 72,
    "top": 583.5999999999999,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 583.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 198.552,
    "top": 582.9337812499999,
    "width": 346.448,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 72,
    "top": 612.8,
    "width": 473,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-63721fc148c7",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/cardinal/languages.png",
    "left": 72,
    "top": 647.8,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 647.8,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 153.276,
    "top": 647.13378125,
    "width": 391.724,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 72,
    "top": 677.0,
    "width": 473,
    "height": 42,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const cardinalTemplate = CARDINAL_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
