/**
 * Cardinal template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/cardinal.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CARDINAL_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF9",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 72,
    "top": 800,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Helvetica",
    "color": "#6E6E6E",
    "left": 522,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Piotr Zieliński",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#24201E",
    "left": 72,
    "top": 50,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 0.15,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Specjalista ds. Cyberbezpieczeństwa",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 72,
    "top": 92,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/phone.png",
    "left": 72.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 574 812 306",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/email.png",
    "left": 189.0,
    "top": 118.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "piotr.zielinski.cyber@outlook.com",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 205.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/linkedin.png",
    "left": 72.0,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/piotr-zielinski",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/github.png",
    "left": 275.4,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/pzielinski",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 291.4,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/website.png",
    "left": 424.79999999999995,
    "top": 134.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "pzielinski.dev",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 440.79999999999995,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/location.png",
    "left": 72.0,
    "top": 150.0,
    "width": 13.0,
    "height": 13.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Poznań",
    "fontSize": 8.6,
    "fontFamily": "Helvetica",
    "color": "#333333",
    "left": 88.0,
    "top": 150.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 72,
    "top": 174.0,
    "width": 473,
    "height": 1,
    "backgroundColor": "#8A8A8A",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/summary.png",
    "left": 72,
    "top": 211.0,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 211.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 266.466,
    "top": 210.33378125,
    "width": 278.534,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Specjalista ds. cyberbezpieczeństwa z doświadczeniem w utrzymaniu systemów IDS/IPS oraz reagowaniu na incydenty w środowisku produkcyjnym.",
    "left": 72,
    "top": 240.2,
    "width": 473,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/experience.png",
    "left": 72,
    "top": 289.2,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 289.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 274.012,
    "top": 288.53378125,
    "width": 270.988,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Specjalista ds. Bezpieczeństwa IT/OT",
    "left": 72,
    "top": 318.4,
    "width": 473,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a736229ca763"
  },
  {
    "category": "textarea",
    "content": "Trident Industrial Sp.J   ·   Poznań   ·   Luty 2024 – obecnie",
    "left": 72,
    "top": 337.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a736229ca763"
  },
  {
    "category": "textarea",
    "content": "• Utrzymuję systemy IDS/IPS i monitoruję ruch sieciowy w segmencie produkcyjnym.",
    "left": 72,
    "top": 353.4,
    "width": 473,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a736229ca763"
  },
  {
    "category": "textarea",
    "content": "Technik Automatyk",
    "left": 72,
    "top": 377.4,
    "width": 473,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4655fb9f2e5d"
  },
  {
    "category": "textarea",
    "content": "Polbryt Przemysł Sp. z o.o.   ·   Poznań   ·   Czerwiec 2022 – Styczeń 2024",
    "left": 72,
    "top": 396.4,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4655fb9f2e5d"
  },
  {
    "category": "textarea",
    "content": "• Konfigurowałem i serwisowałem sterowniki PLC oraz szafy sterownicze.",
    "left": 72,
    "top": 412.4,
    "width": 473,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4655fb9f2e5d"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/education.png",
    "left": 72,
    "top": 447.4,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 447.4,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 206.09799999999998,
    "top": 446.73378125,
    "width": 338.90200000000004,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister inżynier automatyki i robotyki",
    "left": 72,
    "top": 476.59999999999997,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e693b9190558"
  },
  {
    "category": "textarea",
    "content": "Politechnika Poznańska",
    "left": 72,
    "top": 493.59999999999997,
    "width": 473,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#24201E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e693b9190558"
  },
  {
    "category": "textarea",
    "content": "Poznań   ·   ukończono lipiec 2024",
    "left": 72,
    "top": 510.59999999999997,
    "width": 473,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6E6E6E",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e693b9190558"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/skills.png",
    "left": 72,
    "top": 543.5999999999999,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 543.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 198.552,
    "top": 542.9337812499999,
    "width": 346.448,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Bezpieczeństwo",
    "left": 72,
    "top": 572.8,
    "width": 473,
    "height": 12,
    "fontSize": 9.6,
    "lineHeight": 11.6,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "rectangle",
    "left": 72.0,
    "top": 588.8,
    "width": 53.99375,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "text",
    "content": "IDS/IPS",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 82.0,
    "top": 598.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "rectangle",
    "left": 133.99375,
    "top": 588.8,
    "width": 82.0765625,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "text",
    "content": "analiza logów",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 143.99375,
    "top": 598.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "rectangle",
    "left": 224.0703125,
    "top": 588.8,
    "width": 101.43124999999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "text",
    "content": "triage incydentów",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 234.0703125,
    "top": 598.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "rectangle",
    "left": 333.5015625,
    "top": 588.8,
    "width": 66.01249999999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "text",
    "content": "Wireshark",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 343.5015625,
    "top": 598.5999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-2c5df040d126"
  },
  {
    "category": "textarea",
    "content": "Przemysł / OT",
    "left": 72,
    "top": 618.4,
    "width": 473,
    "height": 12,
    "fontSize": 9.6,
    "lineHeight": 11.6,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ca349acd2e52"
  },
  {
    "category": "rectangle",
    "left": 72.0,
    "top": 634.4,
    "width": 112.41874999999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-ca349acd2e52"
  },
  {
    "category": "text",
    "content": "programowanie PLC",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 82.0,
    "top": 644.1999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-ca349acd2e52"
  },
  {
    "category": "rectangle",
    "left": 192.41875,
    "top": 634.4,
    "width": 94.11874999999999,
    "height": 19.6,
    "backgroundColor": "#9E2532",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 9.8,
    "zIndex": 2,
    "page": 1,
    "flowRole": "grid-member",
    "flowGroup": "record-ca349acd2e52"
  },
  {
    "category": "text",
    "content": "systemy SCADA",
    "fontSize": 9.6,
    "fontFamily": "Helvetica",
    "color": "#FCFBF9",
    "left": 202.41875,
    "top": 644.1999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "grid-member",
    "flowGroup": "record-ca349acd2e52"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/cardinal/languages.png",
    "left": 72,
    "top": 675.0,
    "width": 16.5,
    "height": 16.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 11.2,
    "fontFamily": "Helvetica",
    "color": "#9E2532",
    "left": 94,
    "top": 675.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.05,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 153.276,
    "top": 674.33378125,
    "width": 391.724,
    "height": 0.8,
    "backgroundColor": "#8A8A8A",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — B2",
    "left": 72.0,
    "top": 704.2,
    "width": 110.25,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#333333",
    "fontFamily": "Helvetica",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#9E2532"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-ac560f5b3bba"
  }
];

export const cardinalTemplate = CARDINAL_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
