/**
 * Cinder template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/cinder.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CINDER_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F4F3F1",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 5,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 490,
    "height": 1,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 64,
    "height": 3,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#62686D",
    "left": 522,
    "top": 801,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 170,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1
  },
  {
    "category": "line",
    "left": 52,
    "top": 36,
    "width": 5,
    "height": 99,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1
  },
  {
    "category": "text",
    "content": "Michał Baran",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#FFFFFF",
    "left": 76,
    "top": 43,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false
  },
  {
    "category": "text",
    "content": "Incident Response Analyst",
    "fontSize": 9.5,
    "fontFamily": "Inter",
    "color": "#E06B67",
    "left": 78,
    "top": 86,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.65
  },
  {
    "category": "text",
    "content": "michal.baran@securemail.pl · +48 601 224 887 · Kraków ·…",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#B8BCC0",
    "left": 78,
    "top": 119,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 34,
    "width": 72,
    "height": 72,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-one",
    "photoSlot": "frame",
    "photoShape": "ornament-frame"
  },
  {
    "category": "rectangle",
    "left": 455,
    "top": 63,
    "width": 78,
    "height": 78,
    "backgroundColor": "#767B80",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-two",
    "photoSlot": "ornament"
  },
  {
    "category": "rectangle",
    "left": 482,
    "top": 39,
    "width": 12,
    "height": 12,
    "backgroundColor": "#FFFFFF",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-node",
    "photoSlot": "ornament"
  },
  {
    "category": "line",
    "left": 497,
    "top": 45,
    "width": 18,
    "height": 1,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 204.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 202.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 213.745,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityk reagowania na incydenty z doświadczeniem w obsłudze naruszeń bezpieczeństwa dla firm z sektora e-commerce i produkcji. Prowadzę analizę powłamaniową, koordynuję działania naprawcze i dokumentuję incydenty zgodnie z wymogami compliance. Ukończyłem ścieżkę Incident Response na TryHackMe.",
    "left": 76,
    "top": 222.745,
    "width": 466,
    "height": 54,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 299.745,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 297.745,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 309.49,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Incident Response Analyst",
    "left": 76,
    "top": 318.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-05148f6f0e7b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Bastion CyberSec   ·   Kraków   ·   Styczeń 2023 – obecnie",
    "left": 76,
    "top": 337.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-05148f6f0e7b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę analizę powłamaniową i zabezpieczam materiał dowodowy (chain of custody).\n• Koordynuję działania naprawcze między zespołami IT a interesariuszami biznesowymi.\n• Dokumentuję incydenty i przygotowuję raporty post-mortem.\n• Rozwijam playbooki reagowania na najczęstsze scenariusze ataków.",
    "left": 76,
    "top": 353.49,
    "width": 466,
    "height": 54,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-05148f6f0e7b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Administrator Systemów",
    "left": 76,
    "top": 417.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d7329079ed9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "OrbitTrade E-commerce   ·   Kraków   ·   Sierpień 2021 – Grudzień 2022",
    "left": 76,
    "top": 436.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d7329079ed9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Utrzymywałem infrastrukturę serwerową sklepu internetowego (Linux, Docker).\n• Wdrożyłem monitoring dostępności i alerting dla kluczowych usług.",
    "left": 76,
    "top": 452.49,
    "width": 466,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d7329079ed9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Technik IT (Praktyka)",
    "left": 76,
    "top": 489.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3a3d68ebfc42",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Ferrotech Automatyka   ·   Kraków   ·   Czerwiec 2020 – Lipiec 2021",
    "left": 76,
    "top": 508.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3a3d68ebfc42",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałem dział IT w konfiguracji stacji roboczych i sieci lokalnej.",
    "left": 76,
    "top": 524.49,
    "width": 466,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3a3d68ebfc42",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 561.49,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 559.49,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 571.235,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Inżynier teleinformatyki",
    "left": 76,
    "top": 580.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8206750b710",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "AGH Akademia Górniczo-Hutnicza",
    "left": 76,
    "top": 597.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8206750b710",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Kraków   ·   ukończono lipiec 2021",
    "left": 76,
    "top": 614.235,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8206750b710",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Specjalizacja w bezpieczeństwie sieci komputerowych.",
    "left": 76,
    "top": 630.235,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8206750b710",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 665.235,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 663.235,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 674.98,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "analiza powłamaniowa  ·  digital forensics  ·  SIEM  ·  Wireshark  ·  Volatility  ·  MITRE ATT&CK  ·  zarządzanie incydentami  ·  Linux  ·  Docker  ·  Python  ·  Bash",
    "left": 76,
    "top": 683.98,
    "width": 466,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ccb59cb1a53",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 733.98,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 731.98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 743.725,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — C1",
    "left": 76.0,
    "top": 752.725,
    "width": 108.5,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#C93F3F"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-42d4f75be42e"
  }
];

export const cinderTemplate = CINDER_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
