/**
 * Cinder template (`layouts: ["single"]`).
 *
 * Dark, high-contrast single column with ember-red accents.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cinder.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CINDER_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F4F3F1",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 5,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 490,
    "height": 1,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 64,
    "height": 3,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#62686D",
    "left": 522,
    "top": 801,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 170,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 36,
    "width": 5,
    "height": 99,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#FFFFFF",
    "left": 76,
    "top": 43,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 9.5,
    "fontFamily": "Inter",
    "color": "#E06B67",
    "left": 78,
    "top": 86,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.65,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com · +48 512 340 780 · Warszawa ·…",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#B8BCC0",
    "left": 78,
    "top": 119,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 34,
    "width": 72,
    "height": 72,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-one",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 455,
    "top": 63,
    "width": 78,
    "height": 78,
    "backgroundColor": "#767B80",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-two",
    "photoSlot": "ornament",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 482,
    "top": 39,
    "width": 12,
    "height": 12,
    "backgroundColor": "#FFFFFF",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-node",
    "photoSlot": "ornament",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 497,
    "top": 45,
    "width": 18,
    "height": 1,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 204.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 202.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 213.745,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 76,
    "top": 222.745,
    "width": 466,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 272.745,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 270.745,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 282.49,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 76,
    "top": 291.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1b33d76dca5a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 76,
    "top": 310.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1b33d76dca5a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 76,
    "top": 326.49,
    "width": 466,
    "height": 41,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1b33d76dca5a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 76,
    "top": 377.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bbe830b8420d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 76,
    "top": 396.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bbe830b8420d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 76,
    "top": 412.49,
    "width": 466,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bbe830b8420d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 76,
    "top": 449.49,
    "width": 466,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-105779bc744a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 76,
    "top": 468.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-105779bc744a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 76,
    "top": 484.49,
    "width": 466,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-105779bc744a",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 521.49,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 519.49,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 531.235,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 76,
    "top": 540.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cf5b80c65d94",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 76,
    "top": 557.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cf5b80c65d94",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 76,
    "top": 574.235,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cf5b80c65d94",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 609.235,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 607.235,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 618.98,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 76,
    "top": 627.98,
    "width": 466,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-02eee5067744",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 664.98,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 662.98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 674.725,
    "width": 466,
    "height": 1.0,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 76.0,
    "top": 683.725,
    "width": 108.5,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#C93F3F"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-febb8797dc02"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 192.5,
    "top": 683.725,
    "width": 108.5,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#C93F3F"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-febb8797dc02"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 309.0,
    "top": 683.725,
    "width": 108.5,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#C93F3F"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-febb8797dc02"
  }
];

export const cinderTemplate = CINDER_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
