/**
 * Cinder template (`layouts: ["single"]`).
 *
 * Dark, high-contrast single column with ember-red accents.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/cinder.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const CINDER_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F4F3F1",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 5,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 490,
    "height": 1,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 52,
    "top": 786,
    "width": 64,
    "height": 3,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#62686D",
    "left": 522,
    "top": 801,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 170,
    "backgroundColor": "#111315",
    "zIndex": 1,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 36,
    "width": 5,
    "height": 99,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#FFFFFF",
    "left": 76,
    "top": 43,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9.5,
    "fontFamily": "Inter",
    "color": "#E06B67",
    "left": 78,
    "top": 86,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.65,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#B8BCC0",
    "left": 78,
    "top": 119,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 34,
    "width": 72,
    "height": 72,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-one",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 455,
    "top": 63,
    "width": 78,
    "height": 78,
    "backgroundColor": "#767B80",
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-frame-two",
    "photoSlot": "ornament",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 482,
    "top": 39,
    "width": 12,
    "height": 12,
    "backgroundColor": "#FFFFFF",
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "cinder-node",
    "photoSlot": "ornament",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 497,
    "top": 45,
    "width": 18,
    "height": 1,
    "backgroundColor": "#C93F3F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 204.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 202.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 213.745,
    "width": 466,
    "height": 1,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 76,
    "top": 221.745,
    "width": 466,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 271.745,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 269.745,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 281.49,
    "width": 466,
    "height": 1,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 76,
    "top": 293.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-fff2287a5625",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 76,
    "top": 309.49,
    "width": 466,
    "height": 41,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-fff2287a5625",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 76,
    "top": 364.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ab996a1001c3",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 76,
    "top": 380.49,
    "width": 466,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ab996a1001c3",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 76,
    "top": 421.49,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-439781e3eae9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 76,
    "top": 437.49,
    "width": 466,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-439781e3eae9",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 474.49,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 472.49,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 484.235,
    "width": 466,
    "height": 1,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 76,
    "top": 492.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4f6befde5287",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 76,
    "top": 509.235,
    "width": 466,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111315",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4f6befde5287",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 76,
    "top": 526.235,
    "width": 466,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#62686D",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4f6befde5287",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 561.235,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 559.235,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 570.98,
    "width": 466,
    "height": 1,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 76,
    "top": 578.98,
    "width": 466,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a72a141d74dc",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 526,
    "top": 615.98,
    "width": 16,
    "height": 16,
    "backgroundColor": "#C93F3F",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#C93F3F",
    "left": 76,
    "top": 613.98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 625.725,
    "width": 466,
    "height": 1,
    "backgroundColor": "#D5D6D6",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 76,
    "top": 633.725,
    "width": 466,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#292D31",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const cinderTemplate = CINDER_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
