/**
 * Harbor template (`layouts: ["sidebar", "icons"]`).
 *
 * Two-column teal layout with circular photo slot and diamond list widgets.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/harbor.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const HARBOR_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 44,
    "top": 806,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#7A7A7A",
    "left": 535,
    "top": 812,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "JAN KOWALSKI",
    "fontSize": 23,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 44,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.3,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 11,
    "fontFamily": "Inter",
    "color": "#17A2B8",
    "left": 44,
    "top": 80,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/phone.png",
    "left": 44.0,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/email.png",
    "left": 143.5,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 158.5,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/linkedin.png",
    "left": 275.9,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 290.9,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/github.png",
    "left": 422.4,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 437.4,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/website.png",
    "left": 44.0,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 138.8,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 153.8,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 493,
    "top": 36,
    "width": 58,
    "height": 58,
    "backgroundColor": "#ECEEF1",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead",
    "id": "harbor-photo-frame",
    "photoSlot": "frame",
    "photoShape": "circle"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/references.png",
    "left": 507,
    "top": 50,
    "width": 30,
    "height": 30,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "harbor-photo-glyph",
    "photoSlot": "glyph"
  },
  {
    "category": "line",
    "left": 44,
    "top": 142.0,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 173.88,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 364,
    "top": 181.88,
    "width": 187,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ececa0afa7f",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 364,
    "top": 196.88,
    "width": 187,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ececa0afa7f",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 380,
    "top": 208.88,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ececa0afa7f",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 364,
    "top": 209.13,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-0ececa0afa7f",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 253.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 265.76,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Strategia",
    "left": 380,
    "top": 273.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-9",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 274.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-9",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Leadership",
    "left": 380,
    "top": 287.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-11",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 288.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-11",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "P&L",
    "left": 380,
    "top": 301.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-13",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 302.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-13",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Negocjacje",
    "left": 380,
    "top": 315.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-15",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 316.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-15",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Transformacja organizacyjna",
    "left": 380,
    "top": 329.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-17",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 330.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-17",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 364.76,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 376.64,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty",
    "left": 380,
    "top": 384.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-21",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 384.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-21",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Angielski - C1",
    "left": 380,
    "top": 398.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-23",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 398.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-23",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Francuski - B2",
    "left": 380,
    "top": 412.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-25",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 412.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-25",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 173.88,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 44,
    "top": 181.88,
    "width": 292,
    "height": 41,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 243.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 255.76,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 44,
    "top": 263.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-491820851122",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners",
    "left": 44,
    "top": 282.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-491820851122",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 297.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-491820851122"
  },
  {
    "category": "textarea",
    "content": "2021 – obecnie",
    "left": 59.0,
    "top": 296.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-491820851122",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 297.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-491820851122"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 194.0,
    "top": 296.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-491820851122"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 44,
    "top": 312.76,
    "width": 292,
    "height": 81,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-491820851122",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 44,
    "top": 403.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f8d8240ae470",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group",
    "left": 44,
    "top": 422.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f8d8240ae470",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 437.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f8d8240ae470"
  },
  {
    "category": "textarea",
    "content": "2016 – 2021",
    "left": 59.0,
    "top": 436.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f8d8240ae470",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 437.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f8d8240ae470"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 194.0,
    "top": 436.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-f8d8240ae470"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 44,
    "top": 452.76,
    "width": 292,
    "height": 41,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f8d8240ae470",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 44,
    "top": 503.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dee18a3b0aaa",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting",
    "left": 44,
    "top": 522.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dee18a3b0aaa",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 537.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-dee18a3b0aaa"
  },
  {
    "category": "textarea",
    "content": "2013 – 2016",
    "left": 59.0,
    "top": 536.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dee18a3b0aaa",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 537.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-dee18a3b0aaa"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 194.0,
    "top": 536.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-dee18a3b0aaa"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 44,
    "top": 552.76,
    "width": 292,
    "height": 27,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dee18a3b0aaa",
    "flowRole": "content"
  }
];

export const harborTemplate = HARBOR_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
