/**
 * Harbor template (`layouts: ["sidebar", "icons"]`).
 *
 * Two-column teal layout with circular photo slot and diamond list widgets.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/harbor.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const HARBOR_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 44,
    "top": 806,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#7A7A7A",
    "left": 535,
    "top": 812,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 23,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 44,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.3,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 11,
    "fontFamily": "Inter",
    "color": "#17A2B8",
    "left": 44,
    "top": 80,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/phone.png",
    "left": 44.0,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/email.png",
    "left": 143.5,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 158.5,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/linkedin.png",
    "left": 275.9,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 290.9,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/github.png",
    "left": 413.0,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 428.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/website.png",
    "left": 44.0,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 138.8,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 153.8,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "circle",
    "left": 493,
    "top": 36,
    "width": 58,
    "height": 58,
    "backgroundColor": "#ECEEF1",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead",
    "id": "harbor-photo-frame",
    "photoSlot": "frame",
    "photoShape": "circle"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/references.png",
    "left": 507,
    "top": 50,
    "width": 30,
    "height": 30,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "harbor-photo-glyph",
    "photoSlot": "glyph"
  },
  {
    "category": "line",
    "left": 44,
    "top": 142.0,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "wrapping",
      "anchor": {
        "startX": 44.0,
        "startY": 104.0,
        "rightLimit": 551.0
      },
      "text": {
        "fontFamily": "Inter",
        "fontSizePt": 8.4,
        "colorHex": "#3A3A3A"
      },
      "icon": {
        "sizePt": 11,
        "theme": "harbor"
      },
      "metrics": {
        "iconGap": 15,
        "itemPad": 14,
        "lineStep": 16,
        "charWidth": 4.7
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ],
      "downstream": {
        "ruleElementId": null,
        "sectionStartOffsetPt": 42.0
      }
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "text",
          "content": "Analityczka AML i Compliance",
          "left": 44,
          "top": 80.0,
          "width": null,
          "height": null,
          "fontSizePt": 11,
          "lineHeight": null,
          "fontFamily": "Inter",
          "colorHex": "#17A2B8",
          "letterSpacing": null,
          "align": null,
          "autoHeight": false,
          "textTransform": "none",
          "bold": false
        },
        "blockPt": 24.0,
        "present": true
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 173.88,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 364,
    "top": 181.88,
    "width": 187,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20eebf507758",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 364,
    "top": 196.88,
    "width": 187,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20eebf507758",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 380,
    "top": 208.88,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20eebf507758",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 364,
    "top": 209.13,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-20eebf507758",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 253.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 265.76,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "AML/KYC",
    "left": 380,
    "top": 273.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-9",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 274.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-9",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Monitoring",
    "left": 380,
    "top": 287.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-11",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 288.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-11",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "CDD/EDD",
    "left": 380,
    "top": 301.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-13",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 302.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-13",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Raporty SAR",
    "left": 380,
    "top": 315.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-15",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 316.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-15",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Analiza transakcyjna",
    "left": 380,
    "top": 329.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-17",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 330.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-17",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 364.76,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 376.64,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty",
    "left": 380,
    "top": 384.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-21",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 384.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-21",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Angielski - C1",
    "left": 380,
    "top": 398.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-23",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 398.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-23",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Niemiecki - B2",
    "left": 380,
    "top": 412.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-25",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 412.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-25",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 173.88,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 44,
    "top": 181.88,
    "width": 292,
    "height": 41,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 243.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 255.76,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 44,
    "top": 263.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-18813102c9ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory",
    "left": 44,
    "top": 282.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-18813102c9ba",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 297.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-18813102c9ba"
  },
  {
    "category": "textarea",
    "content": "2022 – obecnie",
    "left": 59.0,
    "top": 296.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-18813102c9ba",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 297.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-18813102c9ba"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 194.0,
    "top": 296.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-18813102c9ba"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 44,
    "top": 312.76,
    "width": 292,
    "height": 81,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-18813102c9ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 44,
    "top": 403.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e0541414779",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank",
    "left": 44,
    "top": 422.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e0541414779",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 437.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-1e0541414779"
  },
  {
    "category": "textarea",
    "content": "2019 – 2022",
    "left": 59.0,
    "top": 436.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e0541414779",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 437.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-1e0541414779"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 194.0,
    "top": 436.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-1e0541414779"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 44,
    "top": 452.76,
    "width": 292,
    "height": 54,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1e0541414779",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 44,
    "top": 516.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-26bddb80b01a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services",
    "left": 44,
    "top": 535.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-26bddb80b01a",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 550.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-26bddb80b01a"
  },
  {
    "category": "textarea",
    "content": "2016 – 2019",
    "left": 59.0,
    "top": 549.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-26bddb80b01a",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 550.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-26bddb80b01a"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 194.0,
    "top": 549.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-26bddb80b01a"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 44,
    "top": 565.76,
    "width": 292,
    "height": 27,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-26bddb80b01a",
    "flowRole": "content"
  }
];

export const harborTemplate = HARBOR_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
