/**
 * Harbor template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/harbor.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const HARBOR_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 44,
    "top": 806,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#7A7A7A",
    "left": 535,
    "top": 812,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "NATALIA DĄBROWSKA",
    "fontSize": 23,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 44,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.3,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "SOC Analyst (L1)",
    "fontSize": 11,
    "fontFamily": "Inter",
    "color": "#17A2B8",
    "left": 44,
    "top": 80,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/phone.png",
    "left": 44.0,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 505 118 962",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/email.png",
    "left": 143.5,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "natalia.dabrowska@mail.com",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 158.5,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/linkedin.png",
    "left": 294.7,
    "top": 104.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/natalia-dabrowska",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 309.7,
    "top": 104.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/github.png",
    "left": 44.0,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/ndabrowska",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 59.0,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/website.png",
    "left": 171.7,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "nataliadabrowska.pl",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 186.7,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/location.png",
    "left": 290.0,
    "top": 120.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Gdańsk",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#3A3A3A",
    "left": 305.0,
    "top": 120.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 493,
    "top": 36,
    "width": 58,
    "height": 58,
    "backgroundColor": "#ECEEF1",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead",
    "id": "harbor-photo-frame",
    "photoSlot": "frame",
    "photoShape": "circle"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/references.png",
    "left": 507,
    "top": 50,
    "width": 30,
    "height": 30,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "harbor-photo-glyph",
    "photoSlot": "glyph"
  },
  {
    "category": "line",
    "left": 44,
    "top": 142.0,
    "width": 507,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 173.88,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Inżynier informatyki — specjalność: Systemy i sieci komputerowe",
    "left": 364,
    "top": 181.88,
    "width": 187,
    "height": 26,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f463d2ced918",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Politechnika Gdańska",
    "left": 364,
    "top": 209.88,
    "width": 187,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f463d2ced918",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "ukończono czerwiec 2021",
    "left": 380,
    "top": 221.88,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f463d2ced918",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/calendar.png",
    "left": 364,
    "top": 222.13,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f463d2ced918",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Gdańsk",
    "left": 380,
    "top": 235.88,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f463d2ced918",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/location.png",
    "left": 364,
    "top": 236.13,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f463d2ced918",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 280.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 292.76,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "analiza SIEM/logów",
    "left": 380,
    "top": 300.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-11",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 301.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-11",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "triage alertów",
    "left": 380,
    "top": 314.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-13",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 315.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-13",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Wireshark",
    "left": 380,
    "top": 328.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-15",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 329.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-15",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Nmap",
    "left": 380,
    "top": 342.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-17",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 343.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-17",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Active Directory",
    "left": 380,
    "top": 356.76,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-19",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 357.01,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-19",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 364,
    "top": 391.76,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 364,
    "top": 403.64,
    "width": 187,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty",
    "left": 380,
    "top": 411.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-23",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 411.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-23",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "angielski - B2",
    "left": 380,
    "top": 425.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-25",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 425.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-25",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "hiszpański - A2",
    "left": 380,
    "top": 439.64,
    "width": 171,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-harbor-side-27",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor-accent/diamond.png",
    "left": 364,
    "top": 439.89,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-harbor-side-27",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 162.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 173.88,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "SOC Analyst L1 z doświadczeniem w analizie alertów bezpieczeństwa dla klientów z branży logistycznej. Praktyczna znajomość SIEM, analizy PCAP i podstaw threat huntingu. Ukończyłam ścieżkę SOC Level 1 na TryHackMe.",
    "left": 44,
    "top": 181.88,
    "width": 292,
    "height": 54,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#2B2B2B",
    "left": 44,
    "top": 256.88,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 44,
    "top": 268.76,
    "width": 292,
    "height": 1,
    "backgroundColor": "#C4C9CE",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "SOC Analyst (L1)",
    "left": 44,
    "top": 276.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "textarea",
    "content": "Northgate Logistics",
    "left": 44,
    "top": 295.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 310.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "textarea",
    "content": "Maj 2023 – obecnie",
    "left": 59.0,
    "top": 309.76,
    "width": 110.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 310.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "textarea",
    "content": "Gdańsk",
    "left": 194.0,
    "top": 309.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "textarea",
    "content": "• Analizuję alerty bezpieczeństwa w SIEM i klasyfikuję ich istotność.\n• Prowadzę wstępną analizę plików PCAP przy podejrzeniu incydentu sieciowego.\n• Piszę raporty eskalacyjne dla zespołu L2 zgodnie z ustalonymi SLA.",
    "left": 44,
    "top": 325.76,
    "width": 292,
    "height": 67,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f2fd51578d4d"
  },
  {
    "category": "textarea",
    "content": "Specjalistka ds. Wsparcia IT",
    "left": 44,
    "top": 402.76,
    "width": 292,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B2B2B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "textarea",
    "content": "Cascade Retail Group",
    "left": 44,
    "top": 421.76,
    "width": 292,
    "height": 12,
    "fontSize": 9.2,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#17A2B8",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/calendar.png",
    "left": 44.0,
    "top": 436.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "textarea",
    "content": "Wrzesień 2021 – Kwiecień 2023",
    "left": 59.0,
    "top": 435.76,
    "width": 110.0,
    "height": 23,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/harbor/location.png",
    "left": 179.0,
    "top": 436.01,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "record-overlay",
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "textarea",
    "content": "Gdańsk",
    "left": 194.0,
    "top": 435.76,
    "width": 142.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A7A7A",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-9b668665fdb5"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwałam zgłoszenia użytkowników i zarządzałam kontami w Active Directory.\n• Wspierałam wdrożenie polityki haseł i uwierzytelniania dwuskładnikowego.",
    "left": 44,
    "top": 462.76,
    "width": 292,
    "height": 54,
    "fontSize": 9,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b668665fdb5"
  }
];

export const harborTemplate = HARBOR_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
