/**
 * Icon-driven static layouts (Nova, Volt).
 *
 * Both starters are the backend generators' own output for representative demo
 * content (Julia Bernat — three roles, one degree, five skills, and three
 * languages), so the picker preview matches `/ai/fill_template` pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. Icons live under `/template-assets/iconic/<theme>/`.
 */
import API_BASE_URL from "../services/api.js";

const NOVA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F1E8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 6,
    "backgroundColor": "#C45C26",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 48,
    "top": 800,
    "width": 499,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 522,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 34.0,
    "fontFamily": "PlayfairDisplay",
    "color": "#1A1612",
    "left": 32.0,
    "top": 36.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 9.0,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 32.0,
    "top": 77.7,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/phone.png",
    "left": 34.0,
    "top": 101.85000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 101.85000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/email.png",
    "left": 34.0,
    "top": 118.85000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 118.85000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/linkedin.png",
    "left": 34.0,
    "top": 135.85000000000002,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 135.85000000000002,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/github.png",
    "left": 34.0,
    "top": 152.85000000000002,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 152.85000000000002,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/website.png",
    "left": 34.0,
    "top": 169.85000000000002,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 169.85000000000002,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/location.png",
    "left": 34.0,
    "top": 186.85000000000002,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 50.0,
    "top": 186.85000000000002,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 447.0,
    "top": 30.0,
    "width": 100.0,
    "height": 124.0,
    "backgroundColor": "#EDE4D8",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "id": "nova-photo-well",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 447.0,
    "top": 30.0,
    "width": 100.0,
    "height": 124.0,
    "backgroundColor": "#E0D2C0",
    "borderWidth": 1.0,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "nova-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/portrait.png",
    "left": 476.0,
    "top": 71.0,
    "width": 42,
    "height": 42,
    "zIndex": 4,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "nova-photo-glyph",
    "photoSlot": "glyph"
  },
  {
    "category": "line",
    "left": 48,
    "top": 215.35000000000002,
    "width": 499,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "stacked",
      "anchor": {
        "startX": 34.0,
        "startY": 101.85000000000001
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 8.4,
        "colorHex": "#7A6550"
      },
      "icon": {
        "sizePt": 14.0,
        "theme": "nova"
      },
      "metrics": {
        "iconGap": 16.0,
        "itemPad": 14.0,
        "lineStep": 17.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "text",
          "content": "Analityczka AML i Compliance",
          "left": 32.0,
          "top": 77.7,
          "width": null,
          "height": null,
          "fontSizePt": 9.0,
          "lineHeight": null,
          "fontFamily": "Montserrat",
          "colorHex": "#7A6550",
          "letterSpacing": 1.6,
          "align": null,
          "autoHeight": false,
          "textTransform": "none",
          "bold": false
        },
        "blockPt": 24.150000000000006,
        "present": true,
        "decorations": []
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/summary.png",
    "left": 64.0,
    "top": 252.35000000000002,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 84.0,
    "top": 252.35000000000002,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 84.0,
    "top": 265.82500000000005,
    "width": 463.0,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 84.0,
    "top": 273.82500000000005,
    "width": 463.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/experience.png",
    "left": 64.0,
    "top": 321.82500000000005,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 84.0,
    "top": 321.82500000000005,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 84.0,
    "top": 335.30000000000007,
    "width": 463.0,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 84.0,
    "top": 343.30000000000007,
    "width": 463.0,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35109274b8ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 84.0,
    "top": 362.30000000000007,
    "width": 463.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35109274b8ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 84.0,
    "top": 378.30000000000007,
    "width": 463.0,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35109274b8ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 84.0,
    "top": 429.30000000000007,
    "width": 463.0,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6ca86e32efaa",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 84.0,
    "top": 448.30000000000007,
    "width": 463.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6ca86e32efaa",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 84.0,
    "top": 464.30000000000007,
    "width": 463.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6ca86e32efaa",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 84.0,
    "top": 501.30000000000007,
    "width": 463.0,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e0d63f36ea29",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 84.0,
    "top": 520.3000000000001,
    "width": 463.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e0d63f36ea29",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 84.0,
    "top": 536.3000000000001,
    "width": 463.0,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e0d63f36ea29",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/education.png",
    "left": 64.0,
    "top": 571.3000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 84.0,
    "top": 571.3000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 84.0,
    "top": 584.7750000000001,
    "width": 463.0,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 84.0,
    "top": 592.7750000000001,
    "width": 463.0,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6d64817e03f6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 84.0,
    "top": 609.7750000000001,
    "width": 463.0,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6d64817e03f6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 84.0,
    "top": 626.7750000000001,
    "width": 463.0,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6d64817e03f6",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/skills.png",
    "left": 64.0,
    "top": 659.7750000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 84.0,
    "top": 659.7750000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 84.0,
    "top": 673.2500000000001,
    "width": 463.0,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 84.0,
    "top": 681.2500000000001,
    "width": 463.0,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e4609bee7d2e",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/languages.png",
    "left": 64.0,
    "top": 716.2500000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 84.0,
    "top": 716.2500000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 84.0,
    "top": 729.7250000000001,
    "width": 463.0,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 84.0,
    "top": 737.7250000000001,
    "width": 107.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#C45C26"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d8d374fccc93"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 199.75,
    "top": 737.7250000000001,
    "width": 107.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#C45C26"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d8d374fccc93"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 315.5,
    "top": 737.7250000000001,
    "width": 107.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#C45C26"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d8d374fccc93"
  }
];

const VOLT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#0F1218",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 4,
    "backgroundColor": "#E8A838",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 48,
    "top": 800,
    "width": 499,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "JetBrainsMono",
    "color": "#8B93A0",
    "left": 522,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 32,
    "fontFamily": "Montserrat",
    "color": "#E8ECF0",
    "left": 48,
    "top": 36,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 9,
    "fontFamily": "JetBrainsMono",
    "color": "#E8A838",
    "left": 50,
    "top": 78,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "rectangle",
    "left": 48.0,
    "top": 108.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/phone.png",
    "left": 54.0,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 75.0,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 176.0,
    "top": 108.0,
    "width": 142.4,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/email.png",
    "left": 182.0,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 203.0,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 326.4,
    "top": 108.0,
    "width": 147.60000000000002,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/linkedin.png",
    "left": 332.4,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 353.4,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 48.0,
    "top": 136.0,
    "width": 121.60000000000001,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/github.png",
    "left": 54.0,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 75.0,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 177.60000000000002,
    "top": 136.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/website.png",
    "left": 183.60000000000002,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 204.60000000000002,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "rectangle",
    "left": 305.6,
    "top": 136.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/location.png",
    "left": 311.6,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 332.6,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "chip",
      "anchor": {
        "startX": 48.0,
        "startY": 108.0,
        "rightLimit": 547.0
      },
      "text": {
        "fontFamily": "JetBrainsMono",
        "fontSizePt": 7.8,
        "colorHex": "#C5CCD6"
      },
      "icon": {
        "sizePt": 15.0,
        "theme": "volt"
      },
      "chipColor": "#1A2030",
      "metrics": {
        "chipH": 20.0,
        "iconSize": 15.0,
        "padLeft": 6.0,
        "labelOffset": 27.0,
        "widthBase": 28.0,
        "widthPerChar": 5.2,
        "minWidth": 120.0,
        "maxWidth": 168.0,
        "chipGap": 8.0,
        "lineStep": 28.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "text",
          "content": "Analityczka AML i Compliance",
          "left": 50,
          "top": 78.0,
          "width": null,
          "height": null,
          "fontSizePt": 9,
          "lineHeight": null,
          "fontFamily": "JetBrainsMono",
          "colorHex": "#E8A838",
          "letterSpacing": 1.2,
          "align": null,
          "autoHeight": false,
          "textTransform": "none",
          "bold": false
        },
        "blockPt": 30.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 188.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/summary.png",
    "left": 50.5,
    "top": 193.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 193.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 210.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 78,
    "top": 218.0,
    "width": 469,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 266.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/experience.png",
    "left": 50.5,
    "top": 271.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 271.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 288.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 78,
    "top": 296.0,
    "width": 469,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6e4511afa894",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 78,
    "top": 315.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6e4511afa894",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 78,
    "top": 331.0,
    "width": 469,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6e4511afa894",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 78,
    "top": 382.0,
    "width": 469,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7636a86b0b63",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 78,
    "top": 401.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7636a86b0b63",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 78,
    "top": 417.0,
    "width": 469,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7636a86b0b63",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 78,
    "top": 454.0,
    "width": 469,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aa6a089fded7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 78,
    "top": 473.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aa6a089fded7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 78,
    "top": 489.0,
    "width": 469,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aa6a089fded7",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 524.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/education.png",
    "left": 50.5,
    "top": 529.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 529.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 546.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 78,
    "top": 554.0,
    "width": 469,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0411e01f9c20",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 78,
    "top": 571.0,
    "width": 469,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0411e01f9c20",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 78,
    "top": 588.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0411e01f9c20",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 621.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/skills.png",
    "left": 50.5,
    "top": 626.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 626.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 643.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 78,
    "top": 651.0,
    "width": 469,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-537d8510b771",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 686.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/languages.png",
    "left": 50.5,
    "top": 691.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 691.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 708.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 78.0,
    "top": 716.0,
    "width": 109.25,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#E8A838"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9eb3c3dd3a0a"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 195.25,
    "top": 716.0,
    "width": 109.25,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#E8A838"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9eb3c3dd3a0a"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 312.5,
    "top": 716.0,
    "width": 109.25,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#E8A838"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-9eb3c3dd3a0a"
  }
];

const withAbsoluteAssets = (elements) => elements.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));

export const novaTemplate = withAbsoluteAssets(NOVA_ELEMENTS);
export const voltTemplate = withAbsoluteAssets(VOLT_ELEMENTS);
