/**
 * Icon-driven static layouts (Nova, Volt).
 *
 * Both starters are the backend generators' own output for representative demo
 * content (Jan Kowalski — three roles, one degree, five skills, and three
 * languages), so the picker preview matches `/ai/fill_template` pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. Icons live under `/template-assets/iconic/<theme>/`.
 */
import API_BASE_URL from "../services/api.js";

const NOVA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F1E8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 6,
    "backgroundColor": "#C45C26",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 48,
    "top": 800,
    "width": 499,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 522,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 34,
    "fontFamily": "PlayfairDisplay",
    "color": "#1A1612",
    "left": 48,
    "top": 42,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9.2,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 50,
    "top": 88,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.8,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/phone.png",
    "left": 50.0,
    "top": 118.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 66.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/email.png",
    "left": 158.0,
    "top": 118.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 174.0,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/linkedin.png",
    "left": 302.4,
    "top": 118.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 318.4,
    "top": 118.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/github.png",
    "left": 50.0,
    "top": 134.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 66.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/website.png",
    "left": 184.0,
    "top": 134.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 200.0,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/location.png",
    "left": 286.8,
    "top": 134.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#7A6550",
    "left": 302.8,
    "top": 134.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 48,
    "top": 160.0,
    "width": 499,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/summary.png",
    "left": 48,
    "top": 197.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 68,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 68,
    "top": 210.475,
    "width": 479,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 68,
    "top": 218.475,
    "width": 479,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/experience.png",
    "left": 48,
    "top": 266.475,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 68,
    "top": 266.475,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 68,
    "top": 279.95000000000005,
    "width": 479,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 68,
    "top": 291.95000000000005,
    "width": 479,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f83f135d0712",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 68,
    "top": 307.95000000000005,
    "width": 479,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f83f135d0712",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 68,
    "top": 362.95000000000005,
    "width": 479,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b700776d65ea",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 68,
    "top": 378.95000000000005,
    "width": 479,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b700776d65ea",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 68,
    "top": 419.95000000000005,
    "width": 479,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-42e92f26b639",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 68,
    "top": 435.95000000000005,
    "width": 479,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-42e92f26b639",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/education.png",
    "left": 48,
    "top": 470.95000000000005,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 68,
    "top": 470.95000000000005,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 68,
    "top": 484.42500000000007,
    "width": 479,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 68,
    "top": 492.42500000000007,
    "width": 479,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d826f27d434",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 68,
    "top": 509.42500000000007,
    "width": 479,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#1A1612",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d826f27d434",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 68,
    "top": 526.4250000000001,
    "width": 479,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#7A6550",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1d826f27d434",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/skills.png",
    "left": 48,
    "top": 559.4250000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 68,
    "top": 559.4250000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 68,
    "top": 572.9000000000001,
    "width": 479,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 68,
    "top": 580.9000000000001,
    "width": 479,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-eb525d8b242a",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/nova/languages.png",
    "left": 48,
    "top": 615.9000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.5,
    "fontFamily": "Montserrat",
    "color": "#C45C26",
    "left": 68,
    "top": 615.9000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 68,
    "top": 629.3750000000001,
    "width": 479,
    "height": 1,
    "backgroundColor": "#E0D2C0",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 68,
    "top": 637.3750000000001,
    "width": 479,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2C241C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

const VOLT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#0F1218",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 4,
    "backgroundColor": "#E8A838",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 48,
    "top": 800,
    "width": 499,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "JetBrainsMono",
    "color": "#8B93A0",
    "left": 522,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 32,
    "fontFamily": "Montserrat",
    "color": "#E8ECF0",
    "left": 48,
    "top": 36,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9,
    "fontFamily": "JetBrainsMono",
    "color": "#E8A838",
    "left": 50,
    "top": 78,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.2,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 48.0,
    "top": 108.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/phone.png",
    "left": 54.0,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 75.0,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 176.0,
    "top": 108.0,
    "width": 142.4,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/email.png",
    "left": 182.0,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 203.0,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 326.4,
    "top": 108.0,
    "width": 158.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/linkedin.png",
    "left": 332.4,
    "top": 114.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 353.4,
    "top": 114.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 48.0,
    "top": 136.0,
    "width": 132.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/github.png",
    "left": 54.0,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 75.0,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 188.0,
    "top": 136.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/website.png",
    "left": 194.0,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 215.0,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 316.0,
    "top": 136.0,
    "width": 120.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/location.png",
    "left": 322.0,
    "top": 142.1,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.8,
    "fontFamily": "JetBrainsMono",
    "color": "#C5CCD6",
    "left": 343.0,
    "top": 142.1,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 188.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/summary.png",
    "left": 50.5,
    "top": 193.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 193.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 210.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 78,
    "top": 218.0,
    "width": 469,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 266.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/experience.png",
    "left": 50.5,
    "top": 271.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 271.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 288.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 78,
    "top": 300.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6ee6c0dbc008",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 78,
    "top": 316.0,
    "width": 469,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6ee6c0dbc008",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 78,
    "top": 371.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aaacb5cfa54f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 78,
    "top": 387.0,
    "width": 469,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-aaacb5cfa54f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 78,
    "top": 428.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "JetBrainsMono",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-887aa97b65d1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 78,
    "top": 444.0,
    "width": 469,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-887aa97b65d1",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 479.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/education.png",
    "left": 50.5,
    "top": 484.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 484.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 501.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 78,
    "top": 509.0,
    "width": 469,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cdd3c032cb72",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 78,
    "top": 526.0,
    "width": 469,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#E8ECF0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cdd3c032cb72",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 78,
    "top": 543.0,
    "width": 469,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#8B93A0",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cdd3c032cb72",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 576.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/skills.png",
    "left": 50.5,
    "top": 581.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 581.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 598.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 78,
    "top": 606.0,
    "width": 469,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-71217494176b",
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 48,
    "top": 641.0,
    "width": 20.0,
    "height": 20.0,
    "backgroundColor": "#1A2030",
    "borderWidth": 1,
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/volt/languages.png",
    "left": 50.5,
    "top": 646.8,
    "width": 15.0,
    "height": 15.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#E8A838",
    "left": 78,
    "top": 646.8,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 78,
    "top": 663.0,
    "width": 469,
    "height": 1,
    "backgroundColor": "#2A3140",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 78,
    "top": 671.0,
    "width": 469,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#C5CCD6",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

const withAbsoluteAssets = (elements) => elements.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));

export const novaTemplate = withAbsoluteAssets(NOVA_ELEMENTS);
export const voltTemplate = withAbsoluteAssets(VOLT_ELEMENTS);
