/**
 * Kernel template (`layouts: ["single"]`).
 *
 * Systems-architecture single column with amber technical chrome.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/kernel.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const KERNEL_ELEMENTS = [
  {
    "category": "image",
    "src": "/template-assets/kernel-it-architecture.png",
    "width": 595,
    "height": 842,
    "left": 0,
    "top": 0,
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 167,
    "top": 784,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 167,
    "top": 797,
    "width": 7,
    "height": 7,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#526A83",
    "left": 507,
    "top": 792,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 137,
    "top": 48,
    "width": 4,
    "height": 104,
    "backgroundColor": "#173A76",
    "zIndex": 3,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 42,
    "width": 105,
    "height": 52,
    "backgroundColor": "#ACC5D8",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#173A76",
    "left": 167,
    "top": 51,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.15,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 8.9,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 94,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#526A83",
    "left": 167,
    "top": 121,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "ellipse",
    "left": 435,
    "top": 54,
    "width": 75,
    "height": 34,
    "backgroundColor": "#6FB9B4",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "id": "kernel-orbit",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 456,
    "top": 64,
    "width": 15,
    "height": 15,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "kernel-core",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 494,
    "top": 64,
    "width": 15,
    "height": 15,
    "backgroundColor": "#2462B7",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "id": "kernel-node",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 471,
    "top": 70,
    "width": 23,
    "height": 1,
    "backgroundColor": "#D69B22",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 143,
    "top": 186.0,
    "width": 12,
    "height": 12,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 159,
    "top": 192.0,
    "width": 11,
    "height": 1,
    "backgroundColor": "#2462B7",
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 184.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 167,
    "top": 195.475,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 1,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 167,
    "top": 203.475,
    "width": 355,
    "height": 40,
    "fontSize": 9.4,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 143,
    "top": 266.475,
    "width": 12,
    "height": 12,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 159,
    "top": 272.475,
    "width": 11,
    "height": 1,
    "backgroundColor": "#2462B7",
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 264.475,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 167,
    "top": 275.95000000000005,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 1,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 167,
    "top": 283.95000000000005,
    "width": 355,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#173A76",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a823fc7c69e6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 167,
    "top": 302.95000000000005,
    "width": 355,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#526A83",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a823fc7c69e6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 167,
    "top": 318.95000000000005,
    "width": 355,
    "height": 54,
    "fontSize": 9.4,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a823fc7c69e6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 167,
    "top": 382.95000000000005,
    "width": 355,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#173A76",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-528539a3c051",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 167,
    "top": 401.95000000000005,
    "width": 355,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#526A83",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-528539a3c051",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 167,
    "top": 417.95000000000005,
    "width": 355,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-528539a3c051",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 167,
    "top": 454.95000000000005,
    "width": 355,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#173A76",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7db4b397b1fc",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 167,
    "top": 473.95000000000005,
    "width": 355,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#526A83",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7db4b397b1fc",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 167,
    "top": 489.95000000000005,
    "width": 355,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7db4b397b1fc",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 143,
    "top": 539.95,
    "width": 12,
    "height": 12,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 159,
    "top": 545.95,
    "width": 11,
    "height": 1,
    "backgroundColor": "#2462B7",
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 537.95,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 167,
    "top": 549.4250000000001,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 1,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 167,
    "top": 557.4250000000001,
    "width": 355,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#173A76",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65f071900796",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 167,
    "top": 574.4250000000001,
    "width": 355,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#173A76",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65f071900796",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 167,
    "top": 591.4250000000001,
    "width": 355,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#526A83",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-65f071900796",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 143,
    "top": 626.4250000000001,
    "width": 12,
    "height": 12,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 159,
    "top": 632.4250000000001,
    "width": 11,
    "height": 1,
    "backgroundColor": "#2462B7",
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 624.4250000000001,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 167,
    "top": 635.9000000000001,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 1,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 167,
    "top": 643.9000000000001,
    "width": 355,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c78ba21157dd",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 143,
    "top": 680.9000000000001,
    "width": 12,
    "height": 12,
    "backgroundColor": "#D69B22",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 159,
    "top": 686.9000000000001,
    "width": 11,
    "height": 1,
    "backgroundColor": "#2462B7",
    "zIndex": 3,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#2462B7",
    "left": 167,
    "top": 678.9000000000001,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 167,
    "top": 690.3750000000001,
    "width": 355,
    "height": 1,
    "backgroundColor": "#ACC5D8",
    "zIndex": 1,
    "page": 1,
    "locked": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 167.0,
    "top": 698.3750000000001,
    "width": 80.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#2462B7"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bec89ea23e5c"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 255.75,
    "top": 698.3750000000001,
    "width": 80.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2462B7"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bec89ea23e5c"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 344.5,
    "top": 698.3750000000001,
    "width": 80.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.3,
    "letterSpacing": 0,
    "color": "#253D54",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2462B7"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-bec89ea23e5c"
  }
];

export const kernelTemplate = KERNEL_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
