/**
 * Ledger template (`layouts: ["single"]`).
 *
 * Institutional finance CV with navy hierarchy and a market accent image.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/ledger.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const LEDGER_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 146,
    "backgroundColor": "#102A43",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 0,
    "top": 146,
    "width": 595,
    "height": 5,
    "backgroundColor": "#2E5E86",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 416,
    "top": 24,
    "width": 122,
    "height": 126,
    "backgroundColor": "#AEBECC",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/ledger-finance-accent.png",
    "width": 110,
    "height": 118,
    "left": 422,
    "top": 28,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 400,
    "top": 30,
    "width": 2,
    "height": 102,
    "backgroundColor": "#2E5E86",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 30,
    "fontFamily": "Times-Roman",
    "color": "#FFFFFF",
    "left": 52,
    "top": 58,
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 10,
    "fontFamily": "Inter",
    "color": "#C7D7E2",
    "left": 52,
    "top": 98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "letterSpacing": 1.05
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.8,
    "fontFamily": "Inter",
    "color": "#C7D7E2",
    "left": 52,
    "top": 120,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#2E5E86",
    "left": 52,
    "top": 183.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 52,
    "top": 195.15,
    "width": 490,
    "height": 1,
    "backgroundColor": "#AEBECC",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 52,
    "top": 203.15,
    "width": 490,
    "height": 27,
    "fontSize": 9.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#2E5E86",
    "left": 52,
    "top": 251.15,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 52,
    "top": 263.3,
    "width": 490,
    "height": 1,
    "backgroundColor": "#AEBECC",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 52,
    "top": 271.3,
    "width": 490,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#102A43",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-582d6e8788de",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 52,
    "top": 290.3,
    "width": 490,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#607789",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-582d6e8788de",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 52,
    "top": 306.3,
    "width": 490,
    "height": 41,
    "fontSize": 9.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-582d6e8788de",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 52,
    "top": 357.3,
    "width": 490,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#102A43",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-32872460e0b2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 52,
    "top": 376.3,
    "width": 490,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#607789",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-32872460e0b2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 52,
    "top": 392.3,
    "width": 490,
    "height": 27,
    "fontSize": 9.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-32872460e0b2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 52,
    "top": 429.3,
    "width": 490,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#102A43",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a73b0db4ec8d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 52,
    "top": 448.3,
    "width": 490,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#607789",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a73b0db4ec8d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 52,
    "top": 464.3,
    "width": 490,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a73b0db4ec8d",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#2E5E86",
    "left": 52,
    "top": 499.3,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 52,
    "top": 511.45,
    "width": 490,
    "height": 1,
    "backgroundColor": "#AEBECC",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 52,
    "top": 519.45,
    "width": 490,
    "height": 13,
    "fontSize": 10.6,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#102A43",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-29cc3366361b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 52,
    "top": 536.45,
    "width": 490,
    "height": 13,
    "fontSize": 10.6,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#102A43",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-29cc3366361b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 52,
    "top": 553.45,
    "width": 490,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#607789",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-29cc3366361b",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#2E5E86",
    "left": 52,
    "top": 586.45,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 52,
    "top": 598.6,
    "width": 490,
    "height": 1,
    "backgroundColor": "#AEBECC",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 52,
    "top": 606.6,
    "width": 490,
    "height": 14,
    "fontSize": 9.8,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3eb6fe6acf6c",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9,
    "fontFamily": "Inter",
    "color": "#2E5E86",
    "left": 52,
    "top": 641.6,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 52,
    "top": 653.75,
    "width": 490,
    "height": 1,
    "backgroundColor": "#AEBECC",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 52.0,
    "top": 661.75,
    "width": 114.5,
    "height": 14,
    "fontSize": 9.8,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#2E5E86"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-644f6f2611b4"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 174.5,
    "top": 661.75,
    "width": 114.5,
    "height": 14,
    "fontSize": 9.8,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E5E86"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-644f6f2611b4"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 297.0,
    "top": 661.75,
    "width": 114.5,
    "height": 14,
    "fontSize": 9.8,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#17212B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#2E5E86"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-644f6f2611b4"
  }
];

export const ledgerTemplate = LEDGER_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
