/**
 * Linden template (`layouts: ["sidebar", "icons"]`).
 *
 * Botanical editorial layout with a rectangular portrait, forest-green
 * identity system, and a measured contact rail.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/linden.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const LINDEN_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FBFAF6",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true,
    "appearanceTemplateId": "linden",
    "appearanceSettings": {
      "palette": "botanical",
      "textSize": "M"
    }
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 210.0,
    "height": 842,
    "backgroundColor": "#F2EFE6",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 0,
    "width": 1.0,
    "height": 842,
    "backgroundColor": "#D3CCBC",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#666C65",
    "left": 531.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.4,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 34.0,
    "top": 304.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 320.28,
    "width": 22,
    "height": 1.0,
    "backgroundColor": "#285548",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 34.0,
    "top": 325.0,
    "width": 152.0,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a363bd071ab2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 34.0,
    "top": 342.0,
    "width": 152.0,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a363bd071ab2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 34.0,
    "top": 359.0,
    "width": 152.0,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a363bd071ab2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Certyfikat AML Foundations",
    "left": 34.0,
    "top": 381.0,
    "width": 152.0,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-600374aa6cca",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "ACAMS Academy",
    "left": 34.0,
    "top": 398.0,
    "width": 152.0,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-600374aa6cca",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2021",
    "left": 34.0,
    "top": 415.0,
    "width": 152.0,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-600374aa6cca",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.4,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 34.0,
    "top": 439.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 455.28,
    "width": 22,
    "height": 1.0,
    "backgroundColor": "#285548",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• AML/KYC\n• Monitoring\n• CDD/EDD\n• Raporty SAR\n• Analiza transakcyjna\n• Screening PEP\n• Sanctions\n• SQL",
    "left": 34.0,
    "top": 460.0,
    "width": 152.0,
    "height": 97.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.4,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 34.0,
    "top": 569.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 585.28,
    "width": 22,
    "height": 1.0,
    "backgroundColor": "#285548",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nNiemiecki - B2\nFrancuski - A2",
    "left": 34.0,
    "top": 590.0,
    "width": 152.0,
    "height": 49.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "CERTYFIKATY",
    "fontSize": 9.4,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 34.0,
    "top": 651.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 667.28,
    "width": 22,
    "height": 1.0,
    "backgroundColor": "#285548",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• ACAMS AML Foundations\n• ICA Certificate in Compliance\n• Szkolenie CDD/EDD",
    "left": 34.0,
    "top": 672.0,
    "width": 152.0,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 245.0,
    "top": 190.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 208.6,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#D3CCBC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 245.0,
    "top": 217.6,
    "width": 300.0,
    "height": 56,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 10.2,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 245.0,
    "top": 294.6,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 313.20000000000005,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#D3CCBC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 245.0,
    "top": 322.20000000000005,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ea941cf96873",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 245.0,
    "top": 341.20000000000005,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ea941cf96873",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 245.0,
    "top": 357.20000000000005,
    "width": 300.0,
    "height": 83,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ea941cf96873",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 245.0,
    "top": 450.20000000000005,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ea3f96055df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 245.0,
    "top": 469.20000000000005,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ea3f96055df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 245.0,
    "top": 485.20000000000005,
    "width": 300.0,
    "height": 56,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ea3f96055df",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 245.0,
    "top": 551.2,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92ae0b29a70e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 245.0,
    "top": 570.2,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92ae0b29a70e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 245.0,
    "top": 586.2,
    "width": 300.0,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-92ae0b29a70e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Asystentka ds. zgodności",
    "left": 245.0,
    "top": 624.2,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2823cc5ee311",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Operations   ·   Kraków   ·   2014 – 2016",
    "left": 245.0,
    "top": 643.2,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#666C65",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2823cc5ee311",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Przygotowywała dokumentację klientów i wspierała kontrole jakości danych.\n• Koordynowała odpowiedzi na zapytania operacyjne zespołów sprzedaży i ryzyka.",
    "left": 245.0,
    "top": 659.2,
    "width": 300.0,
    "height": 56,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#252823",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2823cc5ee311",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 806.0,
    "width": 152.0,
    "height": 1.0,
    "backgroundColor": "#D3CCBC",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 34.0,
    "top": 798.0,
    "width": 7.0,
    "height": 7.0,
    "backgroundColor": "#285548",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 210.0,
    "top": 92.0,
    "width": 385.0,
    "height": 38.0,
    "backgroundColor": "#1E4037",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead",
    "titleDecoration": "identity-band",
    "mastheadRole": "title-decoration",
    "mastheadBandId": "linden-masthead"
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 245.0,
    "top": 39.0,
    "width": 300.0,
    "height": 32,
    "fontSize": 29.0,
    "lineHeight": 31.49,
    "letterSpacing": 2.6,
    "color": "#1E4037",
    "fontFamily": "CormorantGaramond",
    "zIndex": 5,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "linden-masthead",
    "textTransform": "uppercase"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 245.0,
    "top": 104.0,
    "width": 300.0,
    "height": 13,
    "fontSize": 9.2,
    "lineHeight": 12.5,
    "letterSpacing": 1.25,
    "color": "#FBFAF6",
    "fontFamily": "Montserrat",
    "zIndex": 5,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "linden-masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "linden-masthead",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 245.0,
          "top": 104.0,
          "width": 300.0,
          "height": 13,
          "fontSizePt": 9.2,
          "lineHeight": 12.5,
          "fontFamily": "Montserrat",
          "colorHex": "#FBFAF6",
          "letterSpacing": 1.25,
          "align": "left",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "none",
          "bold": false,
          "italic": true,
          "underline": false,
          "zIndex": 5
        },
        "blockPt": 0.0,
        "present": true,
        "decorations": [
          {
            "category": "rectangle",
            "left": 210.0,
            "top": 92.0,
            "width": 385.0,
            "height": 38.0,
            "backgroundColor": "#1E4037",
            "borderWidth": 1,
            "borderRadius": null,
            "filled": true,
            "zIndex": 2,
            "page": 1,
            "flowRole": "masthead",
            "titleDecoration": "identity-band"
          }
        ],
        "reclaimPt": 0.0
      },
      "contactBandId": null
    },
    "mastheadBandId": "linden-masthead",
    "mainFlowStart": 190.0
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/linden/phone.png",
    "left": 34.0,
    "top": 216.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#666C65",
    "left": 48.0,
    "top": 216.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "linden-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/linden/email.png",
    "left": 34.0,
    "top": 231.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#666C65",
    "left": 48.0,
    "top": 231.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "linden-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/linden/linkedin.png",
    "left": 34.0,
    "top": 246.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#666C65",
    "left": 48.0,
    "top": 246.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "linden-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/linden/location.png",
    "left": 34.0,
    "top": 261.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.5,
    "fontFamily": "Montserrat",
    "color": "#666C65",
    "left": 48.0,
    "top": 261.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "linden-contact",
      "mode": "stacked",
      "anchor": {
        "startX": 34.0,
        "startY": 216.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 7.5,
        "colorHex": "#666C65"
      },
      "icon": {
        "sizePt": 9.5,
        "theme": "linden"
      },
      "metrics": {
        "iconGap": 14.0,
        "itemPad": 14.0,
        "lineStep": 15.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ],
      "sidebarSectionGap": 32.0,
      "photoHidden": {
        "mode": "stacked",
        "anchor": {
          "startX": 34.0,
          "startY": 64.0
        }
      }
    },
    "contactBandId": "linden-contact"
  },
  {
    "category": "text",
    "content": "DANE KONTAKTOWE",
    "fontSize": 9.5,
    "fontFamily": "CormorantGaramond",
    "color": "#1E4037",
    "left": 34.0,
    "top": 190.0,
    "zIndex": 5,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.55,
    "flowRole": "masthead",
    "profilePhotoHiddenTop": 38.0
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 204.0,
    "width": 56.0,
    "height": 1.0,
    "backgroundColor": "#285548",
    "zIndex": 4,
    "page": 1,
    "flowRole": "masthead",
    "profilePhotoHiddenTop": 52.0
  },
  {
    "category": "rectangle",
    "left": 41.0,
    "top": 31.0,
    "width": 126.0,
    "height": 144.0,
    "backgroundColor": "#F8F5ED",
    "borderWidth": 1,
    "filled": true,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "linden-photo-well",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 41.0,
    "top": 31.0,
    "width": 126.0,
    "height": 144.0,
    "backgroundColor": "#285548",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 4,
    "page": 1,
    "id": "linden-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/linden/portrait.png",
    "left": 89.0,
    "top": 88.0,
    "width": 30.0,
    "height": 30.0,
    "zIndex": 5,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "linden-photo-glyph",
    "photoSlot": "glyph"
  }
];

export const lindenTemplate = LINDEN_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
