/**
 * Manifest template (`layouts: ["sidebar"]`).
 *
 * A flat, architectural two-column layout adapted from the "Modernist" Claude
 * Design system: near-mono red (#EC3013) on ink/paper, zero corner radius,
 * strong 2px rules, a dark inverted header band, and a light sidebar rail
 * separated from the main column by a solid divider. Proportions carry the
 * source design's own A4 CSS-px page over to this app's A4 canvas (points)
 * via the standard 0.75 (72/96 dpi) ratio.
 *
 * Font note: the source design specifies Archivo throughout; Roboto stands
 * in (a different registered grotesk than Blueprint's Inter, so the two
 * read as distinct) — see the backend generator's module docstring for the
 * full font-substitution rationale.
 *
 * Packer-safety note: the source design's per-record oversized ordinal
 * number and per-language five-segment proficiency bar are both same-row,
 * multi-element patterns that would corrupt under this app's structural
 * packer exactly like Blueprint's reverted same-row date/tag/badge rows did
 * (see blueprint.py's module docstring for the discovery). Both were adapted
 * to safe, one-element-per-row shapes here: the ordinal is folded into the
 * title text ("01 · Senior AML Analyst…") and language level into a
 * plain bulleted "Name — Level" sidebar line.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/manifest.py`) for
 * representative demo content (Jan Kowalski — three roles, two degrees, nine
 * skills, four languages, and a Certyfikaty extra section in the sidebar, so
 * the picker preview shows every section type this template supports), so
 * the picker preview matches what `/ai/fill_template` produces
 * pixel-for-pixel. No images are drawn, so no API_BASE_URL rewrite is
 * needed. Exported array `manifestTemplate`.
 */
const MANIFEST_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F3F2F2",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 180,
    "height": 842,
    "backgroundColor": "#F8F4F4",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 180,
    "top": 0,
    "width": 2,
    "height": 842,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Roboto",
    "color": "#605D5D",
    "left": 539,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 140.79,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "CURRICULUM VITAE",
    "fontSize": 8.3,
    "fontFamily": "Roboto",
    "color": "#EC3013",
    "left": 42,
    "top": 36,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.2,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 42,
    "top": 54.79,
    "width": 321,
    "height": 35,
    "fontSize": 33,
    "lineHeight": 35,
    "letterSpacing": 0,
    "color": "#F3F2F2",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "left": 42,
    "top": 95.78999999999999,
    "width": 321,
    "height": 15,
    "fontSize": 11.25,
    "lineHeight": 14.625,
    "letterSpacing": 1.4,
    "color": "#EC3013",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 439.7294921875,
    "top": 52.364999999999995,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 476.1900634765625,
    "top": 71.83999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 505.6287841796875,
    "top": 91.31499999999998,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 170.79,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 185.82999999999998,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 42,
    "top": 195.82999999999998,
    "width": 114,
    "height": 126,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 345.83,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 360.87,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Niemiecki — B2\n• Francuski — A2",
    "left": 42,
    "top": 366.83,
    "width": 114,
    "height": 54.16,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "CERTYFIKATY",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 432.99,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 448.03000000000003,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• PMP – Project Management Professional\n• PRINCE2 Practitioner",
    "left": 42,
    "top": 453.99,
    "width": 114,
    "height": 42.12,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 508.11,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 523.15,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania\nSGH Warszawa\n2011 – 2016\n\nLicencjat Ekonomii\nUniwersytet Warszawski\nWarszawa   ·   2008 – 2011\n• Specjalizacja: ekonomia międzynarodowa.",
    "left": 42,
    "top": 529.11,
    "width": 114,
    "height": 114.36,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 15,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 212,
    "top": 170.79,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 212,
    "top": 192.54,
    "width": 341,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "01 · Dyrektor Strategii",
    "left": 212,
    "top": 202.54,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-868d4d6946f1"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners",
    "left": 212,
    "top": 222.54,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-868d4d6946f1"
  },
  {
    "category": "textarea",
    "content": "2021 – OBECNIE",
    "left": 212,
    "top": 239.54,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-868d4d6946f1"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 212,
    "top": 255.54,
    "width": 341,
    "height": 56,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-868d4d6946f1"
  },
  {
    "category": "textarea",
    "content": "02 · Menedżer Rozwoju",
    "left": 212,
    "top": 321.53999999999996,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2e5b59c4928"
  },
  {
    "category": "textarea",
    "content": "Meridian Group",
    "left": 212,
    "top": 341.53999999999996,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2e5b59c4928"
  },
  {
    "category": "textarea",
    "content": "2016 – 2021",
    "left": 212,
    "top": 358.53999999999996,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2e5b59c4928"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 212,
    "top": 374.53999999999996,
    "width": 341,
    "height": 42,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2e5b59c4928"
  },
  {
    "category": "textarea",
    "content": "03 · Konsultant Strategiczny",
    "left": 212,
    "top": 426.53999999999996,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-da8cf7307f38"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków",
    "left": 212,
    "top": 446.53999999999996,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-da8cf7307f38"
  },
  {
    "category": "textarea",
    "content": "2013 – 2016",
    "left": 212,
    "top": 463.53999999999996,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-da8cf7307f38"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.\n• Opracowywał analizy rynkowe i modele finansowe wspierające decyzje zarządu.",
    "left": 212,
    "top": 479.53999999999996,
    "width": 341,
    "height": 56,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-da8cf7307f38"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 15,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 212,
    "top": 556.54,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 212,
    "top": 578.29,
    "width": 341,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna  ·  Zarządzanie zmianą  ·  Budowanie zespołów  ·  Analiza rynku  ·  Fuzje i przejęcia",
    "left": 212,
    "top": 588.29,
    "width": 341,
    "height": 42,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-350d8d37dee6"
  }
];

export const manifestTemplate = MANIFEST_ELEMENTS;
