/**
 * Manifest template (`layouts: ["sidebar"]`).
 *
 * Architectural two-column layout with inverted header and red accent.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/manifest.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MANIFEST_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F3F2F2",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 180,
    "height": 842,
    "backgroundColor": "#F8F4F4",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 180,
    "top": 0,
    "width": 2,
    "height": 842,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Roboto",
    "color": "#605D5D",
    "left": 539,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 140.79,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "CURRICULUM VITAE",
    "fontSize": 8.3,
    "fontFamily": "Roboto",
    "color": "#EC3013",
    "left": 42,
    "top": 36,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.2,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 42,
    "top": 54.79,
    "width": 321,
    "height": 35,
    "fontSize": 33,
    "lineHeight": 35,
    "letterSpacing": 0,
    "color": "#F3F2F2",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "left": 42,
    "top": 95.78999999999999,
    "width": 321,
    "height": 15,
    "fontSize": 11.25,
    "lineHeight": 14.625,
    "letterSpacing": 1.4,
    "color": "#EC3013",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 439.7294921875,
    "top": 52.364999999999995,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 476.1900634765625,
    "top": 71.83999999999999,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 10.25,
    "fontFamily": "Roboto",
    "color": "#F3F2F2",
    "left": 505.6287841796875,
    "top": 91.31499999999998,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 170.79,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 185.82999999999998,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 42,
    "top": 195.82999999999998,
    "width": 114,
    "height": 126,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 345.83,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 360.87,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nFrancuski - B2",
    "left": 42,
    "top": 366.83,
    "width": 114,
    "height": 42.12,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.2,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 42,
    "top": 420.95,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 42,
    "top": 435.99,
    "width": 114,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 1,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 42,
    "top": 441.95,
    "width": 114,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f532e868f295",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 42,
    "top": 458.95,
    "width": 114,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f532e868f295",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 42,
    "top": 475.95,
    "width": 114,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f532e868f295",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Specjalizacja: ekonomia międzynarodowa.",
    "left": 42,
    "top": 491.95,
    "width": 114,
    "height": 25,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f532e868f295",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 15,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 212,
    "top": 170.79,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 212,
    "top": 192.54,
    "width": 341,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "01 · Dyrektor Strategii",
    "left": 212,
    "top": 202.54,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5c84832116ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa",
    "left": 212,
    "top": 222.54,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5c84832116ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021 – OBECNIE",
    "left": 212,
    "top": 239.54,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5c84832116ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 212,
    "top": 255.54,
    "width": 341,
    "height": 56,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5c84832116ae",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "02 · Menedżer Rozwoju",
    "left": 212,
    "top": 321.53999999999996,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5bcb369dcb75",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków",
    "left": 212,
    "top": 341.53999999999996,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5bcb369dcb75",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2016 – 2021",
    "left": 212,
    "top": 358.53999999999996,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5bcb369dcb75",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 212,
    "top": 374.53999999999996,
    "width": 341,
    "height": 42,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5bcb369dcb75",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "03 · Konsultant Strategiczny",
    "left": 212,
    "top": 426.53999999999996,
    "width": 341,
    "height": 16,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4e0a7c2c7a1d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków",
    "left": 212,
    "top": 446.53999999999996,
    "width": 341,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#AE1800",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4e0a7c2c7a1d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2013 – 2016",
    "left": 212,
    "top": 463.53999999999996,
    "width": 341,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0.6,
    "color": "#605D5D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4e0a7c2c7a1d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 212,
    "top": 479.53999999999996,
    "width": 341,
    "height": 28,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4e0a7c2c7a1d",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 15,
    "fontFamily": "Roboto",
    "color": "#201E1D",
    "left": 212,
    "top": 528.54,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 212,
    "top": 550.29,
    "width": 341,
    "height": 2,
    "backgroundColor": "#201E1D",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 212,
    "top": 560.29,
    "width": 341,
    "height": 14,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#201E1D",
    "fontFamily": "Roboto",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-75c061903613",
    "flowRole": "content"
  }
];

export const manifestTemplate = MANIFEST_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
