/**
 * Meridian template (`layouts: ["single", "icons"]`).
 *
 * Premium navy/steel-blue single column with a compact serif summary
 * and an accent-blue tick under every section rule.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/meridian.py`) for
 * representative demo content (Alexandra Nowak — strategy consultant with three roles, one degree, four skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MERIDIAN_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#3D5A80",
    "left": 510,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Alexandra Nowak",
    "left": 62,
    "top": 47.0,
    "width": 471,
    "height": 37,
    "fontSize": 34,
    "lineHeight": 37,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "textarea",
    "content": "Strategy Consultant",
    "left": 62,
    "top": 90.0,
    "width": 471,
    "height": 13,
    "fontSize": 9,
    "lineHeight": 12.5,
    "letterSpacing": 2.0,
    "color": "#3D5A80",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/phone.png",
    "left": 78.32400000000001,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 89.32400000000001,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/email.png",
    "left": 173.844,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "alexandra@example.com",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 184.844,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/linkedin.png",
    "left": 302.988,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/alexandra-nowak",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 313.988,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/location.png",
    "left": 464.396,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 475.396,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "line",
    "left": 62,
    "top": 131.0,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "meridian-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 117.0,
        "maxWidth": 471.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 8.0,
        "colorHex": "#7A8699"
      },
      "icon": {
        "sizePt": 10.0,
        "theme": "regent"
      },
      "metrics": {
        "iconGap": 11.0,
        "itemPad": 16.0,
        "lineStep": 13.5,
        "charWidth": 5.0
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ]
    },
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Strategy Consultant",
          "left": 62,
          "top": 90.0,
          "width": 471,
          "height": 13,
          "fontSizePt": 9,
          "lineHeight": 12.5,
          "fontFamily": "Montserrat",
          "colorHex": "#3D5A80",
          "letterSpacing": 2.0,
          "align": "left",
          "autoHeight": true,
          "textTransform": "uppercase",
          "bold": false
        },
        "blockPt": 27.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "meridian-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 155.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 168.7,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 168.7,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Przekształcam złożone strategie w decyzje, które porządkują organizacje i budują mierzalny wzrost.",
    "left": 62,
    "top": 177.5,
    "width": 471,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "CormorantGaramond",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 210.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 224.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 224.2,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Senior Strategy Consultant",
    "left": 62,
    "top": 233.0,
    "width": 471,
    "height": 15,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5ec23e5c2b39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Advisory   ·   2021 – obecnie",
    "left": 62,
    "top": 252.0,
    "width": 471,
    "height": 12,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5ec23e5c2b39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę projekty transformacyjne dla zespołów zarządzających.\n• Tworzę rekomendacje łączące dane z perspektywą biznesową.",
    "left": 62,
    "top": 268.0,
    "width": 471,
    "height": 24,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5ec23e5c2b39",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Business Analyst",
    "left": 62,
    "top": 302.0,
    "width": 471,
    "height": 15,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35366772259e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   2018 – 2021",
    "left": 62,
    "top": 321.0,
    "width": 471,
    "height": 12,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35366772259e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Analizowałam modele operacyjne i przygotowywałam materiały dla zarządu.\n• Projektowałam modele działania dla zespołów w fazie wzrostu.",
    "left": 62,
    "top": 337.0,
    "width": 471,
    "height": 24,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-35366772259e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Project Analyst",
    "left": 62,
    "top": 371.0,
    "width": 471,
    "height": 15,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dea86a393c4a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Civic Partners   ·   2016 – 2018",
    "left": 62,
    "top": 390.0,
    "width": 471,
    "height": 12,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dea86a393c4a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam wdrożenia strategiczne i analizę efektywności inicjatyw.",
    "left": 62,
    "top": 406.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dea86a393c4a",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 439.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 452.7,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 452.7,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister ekonomii",
    "left": 62,
    "top": 461.5,
    "width": 471,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5e7f5501159",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Szkoła Główna Handlowa",
    "left": 62,
    "top": 478.5,
    "width": 471,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5e7f5501159",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2013 – 2018",
    "left": 62,
    "top": 495.5,
    "width": 471,
    "height": 11,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e5e7f5501159",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 527.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 541.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 541.2,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Transformacja  ·  Analiza biznesowa  ·  Facylitacja",
    "left": 62,
    "top": 550.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-750fa7d0cb80",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 583.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 596.7,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 596.7,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 62.0,
    "top": 605.5,
    "width": 109.75,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#3D5A80"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d52ef854e4b7"
  },
  {
    "category": "textarea",
    "content": "Angielski — C2",
    "left": 179.75,
    "top": 605.5,
    "width": 109.75,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#3D5A80"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d52ef854e4b7"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 297.5,
    "top": 605.5,
    "width": 109.75,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#3D5A80"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d52ef854e4b7"
  }
];

export const meridianTemplate = MERIDIAN_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
