/**
 * Meridian template (`layouts: ["single", "icons"]`).
 *
 * Premium navy/steel-blue single column with a compact Montserrat summary
 * and an accent-blue tick under every section rule.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/meridian.py`) for
 * representative demo content (Aleksandra — strategy & operations manager with three roles, two degrees, ten skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MERIDIAN_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#3D5A80",
    "left": 510,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Aleksandra",
    "left": 62,
    "top": 47.0,
    "width": 471,
    "height": 37,
    "fontSize": 34,
    "lineHeight": 37,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "textarea",
    "content": "Strategy & Operations Manager",
    "left": 62,
    "top": 90.0,
    "width": 471,
    "height": 13,
    "fontSize": 9,
    "lineHeight": 12.5,
    "letterSpacing": 2.0,
    "color": "#3D5A80",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/phone.png",
    "left": 80.09999999999997,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "+48 000 000 000",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 91.09999999999997,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/email.png",
    "left": 176.04399999999998,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "aleksandra.nowak@example.com",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 187.04399999999998,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/linkedin.png",
    "left": 338.26,
    "top": 117.0,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/aleksandra-nowak-demo",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 349.26,
    "top": 117.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/location.png",
    "left": 256.304,
    "top": 130.5,
    "width": 10.0,
    "height": 10.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "Warszawa, Polska",
    "fontSize": 8.0,
    "fontFamily": "Montserrat",
    "color": "#7A8699",
    "left": 267.304,
    "top": 130.5,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "meridian-contact"
  },
  {
    "category": "line",
    "left": 62,
    "top": 144.5,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "meridian-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 117.0,
        "maxWidth": 471.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 8.0,
        "colorHex": "#7A8699"
      },
      "icon": {
        "sizePt": 10.0,
        "theme": "regent"
      },
      "metrics": {
        "iconGap": 11.0,
        "itemPad": 16.0,
        "lineStep": 13.5,
        "charWidth": 5.0
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ]
    },
    "contactBandId": "meridian-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Strategy & Operations Manager",
          "left": 62,
          "top": 90.0,
          "width": 471,
          "height": 13,
          "fontSizePt": 9,
          "lineHeight": 12.5,
          "fontFamily": "Montserrat",
          "colorHex": "#3D5A80",
          "letterSpacing": 2.0,
          "align": "left",
          "autoHeight": true,
          "textTransform": "uppercase",
          "bold": false
        },
        "blockPt": 27.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "meridian-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 168.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 182.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 182.2,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Managerka strategii i operacji z ponad 7-letnim doświadczeniem w doradztwie oraz transformacji biznesowej. Specjalizuję się w analizie procesów, projektowaniu modeli operacyjnych i prowadzeniu inicjatyw zwiększających efektywność organizacji. Łączę analityczne podejście z umiejętnością przekładania danych na konkretne decyzje biznesowe.",
    "left": 62,
    "top": 191.0,
    "width": 471,
    "height": 44,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 256.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 269.7,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 269.7,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategy & Operations Manager",
    "left": 62,
    "top": 278.5,
    "width": 329.0,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-846a03709a1c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Advisory",
    "left": 62,
    "top": 295.5,
    "width": 329.0,
    "height": 11,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-846a03709a1c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę projekty transformacyjne dla klientów z sektora finansowego, technologicznego i usług profesjonalnych.\n• Projektuję modele operacyjne, identyfikuję obszary optymalizacji i przygotowuję rekomendacje dla kadry zarządzającej.\n• Koordynuję zespoły projektowe oraz odpowiadam za prezentację wyników i wdrożenie uzgodnionych działań.",
    "left": 62,
    "top": 310.5,
    "width": 471,
    "height": 66,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-846a03709a1c",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "01/2023 – obecnie",
    "left": 403.0,
    "top": 278.5,
    "width": 130.0,
    "height": 10.8,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-846a03709a1c"
  },
  {
    "category": "textarea",
    "content": "Senior Business Analyst",
    "left": 62,
    "top": 386.5,
    "width": 329.0,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41b8ceb99e8a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Vantage Partners",
    "left": 62,
    "top": 403.5,
    "width": 329.0,
    "height": 11,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41b8ceb99e8a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Analizowałam procesy biznesowe i dane operacyjne, identyfikując możliwości automatyzacji oraz redukcji kosztów.\n• Tworzyłam modele finansowe, dashboardy KPI i materiały decyzyjne dla klientów oraz zespołów projektowych.",
    "left": 62,
    "top": 418.5,
    "width": 471,
    "height": 44,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41b8ceb99e8a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "06/2020 – 12/2022",
    "left": 403.0,
    "top": 386.5,
    "width": 130.0,
    "height": 10.8,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-41b8ceb99e8a"
  },
  {
    "category": "textarea",
    "content": "Business Analyst",
    "left": 62,
    "top": 472.5,
    "width": 329.0,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13.0,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-efc74063cb57",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Orion Consulting Group",
    "left": 62,
    "top": 489.5,
    "width": 329.0,
    "height": 11,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-efc74063cb57",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam projekty strategiczne poprzez analizę rynku, benchmarking konkurencji i przygotowywanie rekomendacji.\n• Opracowywałam raporty zarządcze oraz prezentacje wykorzystywane podczas warsztatów z klientami.",
    "left": 62,
    "top": 504.5,
    "width": 471,
    "height": 33,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-efc74063cb57",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "09/2017 – 05/2020",
    "left": 403.0,
    "top": 472.5,
    "width": 130.0,
    "height": 10.8,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-efc74063cb57"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 558.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 572.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 572.2,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Uniwersytet Ekonomiczny w Krakowie",
    "left": 62,
    "top": 581.0,
    "width": 329.0,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2be2e6c184e8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Magister zarządzania",
    "left": 62,
    "top": 598.0,
    "width": 329.0,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2be2e6c184e8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Specjalizacja: strategia przedsiębiorstwa i zarządzanie zmianą.",
    "left": 62,
    "top": 615.0,
    "width": 471,
    "height": 11,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2be2e6c184e8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2015 – 2017",
    "left": 403.0,
    "top": 598.0,
    "width": 130.0,
    "height": 10.8,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-2be2e6c184e8"
  },
  {
    "category": "textarea",
    "content": "Uniwersytet Ekonomiczny w Krakowie",
    "left": 62,
    "top": 636.0,
    "width": 329.0,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-50e6caf50cb8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Licencjat ekonomii",
    "left": 62,
    "top": 653.0,
    "width": 329.0,
    "height": 13,
    "fontSize": 9.8,
    "lineHeight": 12.5,
    "letterSpacing": 0,
    "color": "#1B2A41",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-50e6caf50cb8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2015",
    "left": 403.0,
    "top": 653.0,
    "width": 130.0,
    "height": 10.8,
    "fontSize": 7.9,
    "lineHeight": 10.8,
    "letterSpacing": 0,
    "color": "#7A8699",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-50e6caf50cb8"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#1B2A41",
    "left": 62,
    "top": 687.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.6,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 700.7,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#D7DEE6",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 700.7,
    "width": 18.0,
    "height": 1.6,
    "backgroundColor": "#3D5A80",
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia biznesowa  ·  Business Analysis  ·  Optymalizacja procesów  ·  Operating Model  ·  Analiza danych  ·  Financial Modeling  ·  Power BI  ·  Excel  ·  SQL  ·  Stakeholder Management",
    "left": 62,
    "top": 709.5,
    "width": 471,
    "height": 22,
    "fontSize": 8.6,
    "lineHeight": 11.0,
    "letterSpacing": 0,
    "color": "#33475A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-950fc0b3cbcf",
    "flowRole": "content"
  }
];

export const meridianTemplate = MERIDIAN_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
