/**
 * Monument template (`layouts: ["single"]`).
 *
 * Monochrome editorial single column with strong rules and plates.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/monument.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MONUMENT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F7F7",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 34,
    "top": 32,
    "width": 527,
    "height": 778,
    "backgroundColor": "#C8C8C8",
    "borderWidth": 0.8,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 51,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 529,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#E8E8E8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 66,
    "top": 779,
    "width": 463,
    "height": 1,
    "backgroundColor": "#C8C8C8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 66,
    "top": 792,
    "width": 28,
    "height": 8,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6D6D6D",
    "left": 512,
    "top": 787,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 33,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 74,
    "top": 59,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii i Rozwoju",
    "left": 76,
    "top": 104,
    "width": 337,
    "height": 20,
    "fontSize": 12.5,
    "lineHeight": 16,
    "letterSpacing": 1.1,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa · linkedin.com/in/jkowalski…",
    "left": 76,
    "top": 136,
    "width": 337,
    "height": 16,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 54,
    "width": 84,
    "height": 84,
    "backgroundColor": "#111111",
    "borderWidth": 1.5,
    "zIndex": 3,
    "page": 1,
    "id": "monument-masthead-frame",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 70,
    "width": 52,
    "height": 11,
    "backgroundColor": "#111111",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 88,
    "width": 34,
    "height": 11,
    "backgroundColor": "#343434",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 106,
    "width": 52,
    "height": 11,
    "backgroundColor": "#C8C8C8",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 184.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 184.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 199.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty.",
    "left": 102,
    "top": 228.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 277.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "02",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 285.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 277.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 285.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 292.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 102,
    "top": 325.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-355e821ed8a9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.",
    "left": 102,
    "top": 341.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-355e821ed8a9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 102,
    "top": 383.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d7f89654a288",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 102,
    "top": 399.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d7f89654a288",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 102,
    "top": 441.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e9a163f617e5",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 102,
    "top": 457.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e9a163f617e5",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 492.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "03",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 500.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 492.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 500.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 507.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 102,
    "top": 536.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-63901f41dc69",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 102,
    "top": 553.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-63901f41dc69",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 102,
    "top": 570.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-63901f41dc69",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 603.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "04",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 611.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 603.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 611.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 618.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 102,
    "top": 647.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-34e8524ffc75",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 682.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "05",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 690.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 682.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 690.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 697.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 102,
    "top": 726.0,
    "width": 427,
    "height": 42,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const monumentTemplate = MONUMENT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
