/**
 * Monument template (`layouts: ["single"]`).
 *
 * Monochrome editorial single column with strong rules and plates.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/monument.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MONUMENT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F7F7",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 34,
    "top": 32,
    "width": 527,
    "height": 778,
    "backgroundColor": "#C8C8C8",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 51,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 529,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#E8E8E8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 66,
    "top": 779,
    "width": 463,
    "height": 1,
    "backgroundColor": "#C8C8C8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 66,
    "top": 792,
    "width": 28,
    "height": 8,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6D6D6D",
    "left": 512,
    "top": 787,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 33,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 74,
    "top": 59,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii i Rozwoju",
    "left": 76,
    "top": 104,
    "width": 337,
    "height": 20,
    "fontSize": 12.5,
    "lineHeight": 16,
    "letterSpacing": 1.1,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa · linkedin.com/in/jkowalski…",
    "left": 76,
    "top": 136,
    "width": 337,
    "height": 16,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 54,
    "width": 84,
    "height": 84,
    "backgroundColor": "#111111",
    "borderWidth": 1.5,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "monument-masthead-frame",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 70,
    "width": 52,
    "height": 11,
    "backgroundColor": "#111111",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 88,
    "width": 34,
    "height": 11,
    "backgroundColor": "#343434",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 106,
    "width": 52,
    "height": 11,
    "backgroundColor": "#C8C8C8",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 184.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 184.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 199.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty.",
    "left": 102,
    "top": 228.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 277.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "02",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 285.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 277.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 285.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 292.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 102,
    "top": 321.0,
    "width": 427,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-51eb8d8929f7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 102,
    "top": 339.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-51eb8d8929f7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.",
    "left": 102,
    "top": 355.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-51eb8d8929f7",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 102,
    "top": 379.0,
    "width": 427,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f10d1ccd7cff",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 102,
    "top": 397.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f10d1ccd7cff",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.",
    "left": 102,
    "top": 413.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f10d1ccd7cff",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 102,
    "top": 437.0,
    "width": 427,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-42130cf099fb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 102,
    "top": 455.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-42130cf099fb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 102,
    "top": 471.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-42130cf099fb",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 506.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "03",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 514.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 506.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 514.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 521.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 102,
    "top": 550.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9af7fd4b4724",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 102,
    "top": 567.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9af7fd4b4724",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 102,
    "top": 584.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9af7fd4b4724",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 617.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "04",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 625.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 617.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 625.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 632.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 102,
    "top": 661.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-28e94f1be11c",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 696.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "05",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 704.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 696.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 704.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 711.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 102.0,
    "top": 740.0,
    "width": 98.75,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#111111"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d3871694fe84"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 208.75,
    "top": 740.0,
    "width": 98.75,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#111111"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d3871694fe84"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 315.5,
    "top": 740.0,
    "width": 98.75,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#111111"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-d3871694fe84"
  }
];

export const monumentTemplate = MONUMENT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
