/**
 * Monument template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/monument.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const MONUMENT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F7F7",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 34,
    "top": 32,
    "width": 527,
    "height": 778,
    "backgroundColor": "#C8C8C8",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 51,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 529,
    "top": 54,
    "width": 8,
    "height": 111,
    "backgroundColor": "#E8E8E8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "line",
    "left": 66,
    "top": 779,
    "width": 463,
    "height": 1,
    "backgroundColor": "#C8C8C8",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 66,
    "top": 792,
    "width": 28,
    "height": 8,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6D6D6D",
    "left": 512,
    "top": 787,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F7F7",
    "zIndex": 0,
    "page": 2,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 34,
    "top": 32,
    "width": 527,
    "height": 778,
    "backgroundColor": "#C8C8C8",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 2,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 66,
    "top": 779,
    "width": 463,
    "height": 1,
    "backgroundColor": "#C8C8C8",
    "zIndex": 2,
    "page": 2,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 66,
    "top": 792,
    "width": 28,
    "height": 8,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 2,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "02",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6D6D6D",
    "left": 512,
    "top": 787,
    "zIndex": 3,
    "page": 2,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Katarzyna Wysocka",
    "fontSize": 33,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 74,
    "top": 59,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Security Analyst",
    "left": 76,
    "top": 104,
    "width": 337,
    "height": 20,
    "fontSize": 12.5,
    "lineHeight": 16,
    "letterSpacing": 1.1,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "k.wysocka.sec@gmail.com · +48 663 550 291 · Wrocław ·…",
    "left": 76,
    "top": 136,
    "width": 337,
    "height": 16,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "rectangle",
    "left": 425,
    "top": 54,
    "width": 84,
    "height": 84,
    "backgroundColor": "#111111",
    "borderWidth": 1.5,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "monument-masthead-frame",
    "photoSlot": "frame",
    "photoShape": "ornament-frame",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 70,
    "width": 52,
    "height": 11,
    "backgroundColor": "#111111",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 88,
    "width": 34,
    "height": 11,
    "backgroundColor": "#343434",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 441,
    "top": 106,
    "width": 52,
    "height": 11,
    "backgroundColor": "#C8C8C8",
    "zIndex": 3,
    "page": 1,
    "photoSlot": "ornament",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 184.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 184.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 192.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 199.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Security Analyst z doświadczeniem w audytach bezpieczeństwa i zarządzaniu podatnościami dla klientów korporacyjnych. Łączę wiedzę techniczną z podejściem procesowym — prowadzę skany podatności, priorytetyzuję ryzyka i współpracuję z zespołami deweloperskimi nad remediacją.",
    "left": 102,
    "top": 228.0,
    "width": 427,
    "height": 56,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 305.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "02",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 313.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 305.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 313.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 320.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Security Analyst",
    "left": 102,
    "top": 349.0,
    "width": 427,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-04002455951b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian IT Services   ·   Wrocław   ·   Kwiecień 2022 – obecnie",
    "left": 102,
    "top": 367.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-04002455951b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę cykliczne skany podatności (Nessus, Qualys) dla infrastruktury klientów.\n• Priorytetyzuję ryzyka i przygotowuję raporty dla zespołów technicznych i zarządu.\n• Współpracuję z deweloperami nad remediacją podatności w aplikacjach webowych.\n• Prowadzę podstawowe testy penetracyjne aplikacji wewnętrznych.",
    "left": 102,
    "top": 383.0,
    "width": 427,
    "height": 56,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-04002455951b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Junior Network Administrator",
    "left": 102,
    "top": 449.0,
    "width": 427,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20350dd11a57",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Quantera Networks   ·   Wrocław   ·   Wrzesień 2020 – Marzec 2022",
    "left": 102,
    "top": 467.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20350dd11a57",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Administrowałam sieciami LAN/WAN i urządzeniami brzegowymi (Cisco, Fortinet).\n• Wspierałam wdrożenie segmentacji sieci zgodnie z wymogami audytu bezpieczeństwa.",
    "left": 102,
    "top": 483.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-20350dd11a57",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 532.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "03",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 540.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 532.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 540.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 547.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister inżynier informatyki — specjalność: Sieci komputerowe",
    "left": 102,
    "top": 576.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c81fe304eaf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Politechnika Wrocławska",
    "left": 102,
    "top": 593.0,
    "width": 427,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#111111",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c81fe304eaf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Wrocław   ·   ukończono czerwiec 2020",
    "left": 102,
    "top": 610.0,
    "width": 427,
    "height": 12,
    "fontSize": 9,
    "lineHeight": 12,
    "letterSpacing": 0,
    "color": "#6D6D6D",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c81fe304eaf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Praca magisterska: ocena skuteczności skanerów podatności open-source.",
    "left": 102,
    "top": 626.0,
    "width": 427,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4c81fe304eaf",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 661.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "04",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 669.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 661.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 669.0,
    "zIndex": 5,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 676.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "zarządzanie podatnościami  ·  Nessus  ·  Qualys  ·  OWASP Top 10  ·  Burp Suite  ·  Nmap  ·  Wireshark  ·  Cisco IOS  ·  Fortinet  ·  Python  ·  SQL",
    "left": 102,
    "top": 705.0,
    "width": 427,
    "height": 28,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cb5ec28b27c1",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 66,
    "top": 72.0,
    "width": 32,
    "height": 32,
    "backgroundColor": "#111111",
    "zIndex": 2,
    "page": 2,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "05",
    "fontSize": 11,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 74,
    "top": 80.0,
    "zIndex": 5,
    "page": 2,
    "bold": true,
    "italic": false,
    "isDecorativeChromeText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 106,
    "top": 72.0,
    "width": 251,
    "height": 32,
    "backgroundColor": "#111111",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 2,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 12.5,
    "fontFamily": "CormorantGaramond",
    "color": "#111111",
    "left": 118,
    "top": 80.0,
    "zIndex": 5,
    "page": 2,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.35,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 369,
    "top": 87.0,
    "width": 160,
    "height": 2,
    "backgroundColor": "#C8C8C8",
    "zIndex": 1,
    "page": 2,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "angielski — B2",
    "left": 102.0,
    "top": 116.0,
    "width": 98.75,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 2,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#111111"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-f352a06bb9d7"
  },
  {
    "category": "textarea",
    "content": "francuski — A2",
    "left": 208.75,
    "top": 116.0,
    "width": 98.75,
    "height": 14,
    "fontSize": 9.0,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#343434",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 2,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#111111"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-f352a06bb9d7"
  }
];

export const monumentTemplate = MONUMENT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
