/**
 * Nimbus template (`layouts: ["single"]`).
 *
 * Light minimal single column with soft blue accents,
 * set entirely in Lora (name 32 / headings & roles 14 /
 * body 12 dark grey / meta 11). Clean masthead (no rail/
 * mark chips), 3 px rules, 56 px under the header divider.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/nimbus.py`) for
 * representative demo content (Jan Kowalski — two roles, one degree, four
 * skills, and two languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const NIMBUS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 3,
    "backgroundColor": "#B9D2E5",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 52,
    "top": 207.0,
    "width": 490,
    "height": 3,
    "backgroundColor": "#B9D2E5",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 401,
    "top": 35,
    "width": 141,
    "height": 153,
    "backgroundColor": "#B9D2E5",
    "borderWidth": 1.1,
    "zIndex": 3,
    "page": 1,
    "id": "nimbus-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/nimbus-finance-accent.png",
    "width": 129,
    "height": 141,
    "left": 407,
    "top": 41,
    "zIndex": 2,
    "page": 1,
    "id": "nimbus-photo-image",
    "photoSlot": "image",
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 32,
    "fontFamily": "Lora",
    "color": "#2B3D4C",
    "left": 80,
    "top": 52,
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "letterSpacing": 1.2
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 11,
    "fontFamily": "Lora",
    "color": "#72818C",
    "left": 80,
    "top": 153,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 266.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 284.9,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania.",
    "left": 80,
    "top": 295.9,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 333.9,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 352.79999999999995,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 80,
    "top": 363.79999999999995,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c40748a13f36",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 80,
    "top": 385.79999999999995,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c40748a13f36",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.",
    "left": 80,
    "top": 404.79999999999995,
    "width": 462,
    "height": 34,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c40748a13f36",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 80,
    "top": 448.79999999999995,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3ab4c88fc85a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 80,
    "top": 470.79999999999995,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3ab4c88fc85a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.",
    "left": 80,
    "top": 489.79999999999995,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3ab4c88fc85a",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 527.8,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 546.6999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 80,
    "top": 557.6999999999999,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d2f3e82e82b6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 80,
    "top": 579.6999999999999,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d2f3e82e82b6",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 80,
    "top": 601.6999999999999,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d2f3e82e82b6",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 637.6999999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 656.5999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje",
    "left": 80,
    "top": 667.5999999999999,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-76c10a64c2c1",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 705.5999999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 724.4999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1",
    "left": 80,
    "top": 735.4999999999999,
    "width": 462,
    "height": 34,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const nimbusTemplate = NIMBUS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
