/**
 * Nimbus template (`layouts: ["single"]`).
 *
 * Light minimal single column with soft blue accents,
 * set entirely in Lora (name 32 / headings & roles 14 /
 * body 12 dark grey / meta 11). Masthead keeps the name
 * accent bar, square photo slot, contact under the photo,
 * 3 px rules, 56 px under the header divider.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/nimbus.py`) for
 * representative demo content (Jan Kowalski — two roles, one degree, four
 * skills, and two languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const NIMBUS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 3,
    "backgroundColor": "#B9D2E5",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 52,
    "top": 192,
    "width": 490,
    "height": 3,
    "backgroundColor": "#B9D2E5",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 52,
    "top": 44,
    "width": 4,
    "height": 78,
    "backgroundColor": "#5F8EAD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 430,
    "top": 38,
    "width": 106,
    "height": 106,
    "backgroundColor": "#DFEBF4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead",
    "id": "nimbus-photo-fill",
    "photoSlot": "ornament"
  },
  {
    "category": "rectangle",
    "left": 424,
    "top": 32,
    "width": 118,
    "height": 118,
    "backgroundColor": "#B9D2E5",
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "id": "nimbus-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/nimbus-finance-accent.png",
    "width": 106,
    "height": 106,
    "left": 430,
    "top": 38,
    "zIndex": 2,
    "page": 1,
    "id": "nimbus-photo-image",
    "photoSlot": "image",
    "alignWithText": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 32,
    "fontFamily": "Lora",
    "color": "#2B3D4C",
    "left": 78,
    "top": 48,
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 92,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "letterSpacing": 1.2
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 11,
    "fontFamily": "Lora",
    "color": "#72818C",
    "left": 80,
    "top": 166,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 251.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 269.9,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania.",
    "left": 80,
    "top": 280.9,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 318.9,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 337.79999999999995,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 80,
    "top": 348.79999999999995,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ed52f6b041b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 80,
    "top": 370.79999999999995,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ed52f6b041b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.",
    "left": 80,
    "top": 389.79999999999995,
    "width": 462,
    "height": 34,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4ed52f6b041b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 80,
    "top": 433.79999999999995,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c49cff410836",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 80,
    "top": 455.79999999999995,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c49cff410836",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.",
    "left": 80,
    "top": 474.79999999999995,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c49cff410836",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 512.8,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 531.6999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 80,
    "top": 542.6999999999999,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-12aa1397f85d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 80,
    "top": 564.6999999999999,
    "width": 462,
    "height": 18,
    "fontSize": 14,
    "lineHeight": 18,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-12aa1397f85d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 80,
    "top": 586.6999999999999,
    "width": 462,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-12aa1397f85d",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 622.6999999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 641.5999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje",
    "left": 80,
    "top": 652.5999999999999,
    "width": 462,
    "height": 17,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4fa2a0781189",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 14,
    "fontFamily": "Lora",
    "color": "#5F8EAD",
    "left": 80,
    "top": 690.5999999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 709.4999999999999,
    "width": 462,
    "height": 3,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1",
    "left": 80,
    "top": 720.4999999999999,
    "width": 462,
    "height": 34,
    "fontSize": 12,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#3A3A3A",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const nimbusTemplate = NIMBUS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
