/**
 * Nimbus template (`layouts: ["single"]`).
 *
 * Light minimal single column with soft blue accents.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/nimbus.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const NIMBUS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 4,
    "backgroundColor": "#B9D2E5",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 52,
    "top": 207,
    "width": 490,
    "height": 1,
    "backgroundColor": "#B9D2E5",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 401,
    "top": 35,
    "width": 141,
    "height": 153,
    "backgroundColor": "#B9D2E5",
    "borderWidth": 1.1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/nimbus-finance-accent.png",
    "width": 129,
    "height": 141,
    "left": 407,
    "top": 41,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 52,
    "top": 48,
    "width": 4,
    "height": 112,
    "backgroundColor": "#5F8EAD",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 29,
    "fontFamily": "Times-Roman",
    "color": "#2B3D4C",
    "left": 78,
    "top": 55,
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9.3,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 99,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "letterSpacing": 1.5
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#72818C",
    "left": 80,
    "top": 153,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 80,
    "top": 176,
    "width": 14,
    "height": 14,
    "backgroundColor": "#5F8EAD",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "id": "nimbus-mark-one",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 114,
    "top": 176,
    "width": 14,
    "height": 14,
    "backgroundColor": "#B9D2E5",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "id": "nimbus-mark-two",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 148,
    "top": 176,
    "width": 14,
    "height": 14,
    "backgroundColor": "#B9D2E5",
    "borderWidth": 1.2,
    "zIndex": 2,
    "page": 1,
    "id": "nimbus-mark-three",
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 94,
    "top": 182,
    "width": 20,
    "height": 1,
    "backgroundColor": "#B9D2E5",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 128,
    "top": 182,
    "width": 20,
    "height": 1,
    "backgroundColor": "#B9D2E5",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 244.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 255.745,
    "width": 462,
    "height": 1,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 80,
    "top": 263.745,
    "width": 462,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 313.745,
    "width": 2,
    "height": 12,
    "backgroundColor": "#DFEBF4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 45,
    "top": 312.745,
    "width": 12,
    "height": 12,
    "backgroundColor": "#5F8EAD",
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 311.745,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 323.49,
    "width": 462,
    "height": 1,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 80,
    "top": 335.49,
    "width": 462,
    "height": 12,
    "fontSize": 8.8,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-172220d6c12d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 80,
    "top": 351.49,
    "width": 462,
    "height": 41,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-172220d6c12d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 80,
    "top": 406.49,
    "width": 462,
    "height": 12,
    "fontSize": 8.8,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-191cdcabaa63",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 80,
    "top": 422.49,
    "width": 462,
    "height": 27,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-191cdcabaa63",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 80,
    "top": 463.49,
    "width": 462,
    "height": 12,
    "fontSize": 8.8,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-af612d64f896",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 80,
    "top": 479.49,
    "width": 462,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-af612d64f896",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 516.49,
    "width": 2,
    "height": 12,
    "backgroundColor": "#DFEBF4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 45,
    "top": 515.49,
    "width": 12,
    "height": 12,
    "backgroundColor": "#5F8EAD",
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 514.49,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 526.235,
    "width": 462,
    "height": 1,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 80,
    "top": 534.235,
    "width": 462,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4551f2d5701",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 80,
    "top": 551.235,
    "width": 462,
    "height": 13,
    "fontSize": 10.3,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4551f2d5701",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 80,
    "top": 568.235,
    "width": 462,
    "height": 12,
    "fontSize": 8.7,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#72818C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c4551f2d5701",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 603.235,
    "width": 2,
    "height": 12,
    "backgroundColor": "#DFEBF4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 45,
    "top": 602.235,
    "width": 12,
    "height": 12,
    "backgroundColor": "#5F8EAD",
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 601.235,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 612.98,
    "width": 462,
    "height": 1,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 80,
    "top": 620.98,
    "width": 462,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-61551a5881d9",
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 52,
    "top": 657.98,
    "width": 2,
    "height": 12,
    "backgroundColor": "#DFEBF4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 45,
    "top": 656.98,
    "width": 12,
    "height": 12,
    "backgroundColor": "#5F8EAD",
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.7,
    "fontFamily": "Inter",
    "color": "#5F8EAD",
    "left": 80,
    "top": 655.98,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 80,
    "top": 667.725,
    "width": 462,
    "height": 1,
    "backgroundColor": "#E9EEF1",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 80,
    "top": 675.725,
    "width": 462,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#2B3D4C",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const nimbusTemplate = NIMBUS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
