/**
 * Portico template (`layouts: ["icons"]`).
 *
 * Centered masthead with icon contact chrome; left-aligned body with
 * icon-in-gutter section headings.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/portico.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const PORTICO_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 76,
    "top": 800,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 504,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 76,
    "top": 58.0,
    "width": 443,
    "height": 33,
    "fontSize": 29,
    "lineHeight": 33,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii i Rozwoju",
    "left": 76,
    "top": 101.0,
    "width": 443,
    "height": 14,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 2.0,
    "color": "#7C6A52",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/phone.png",
    "left": 128.07373046875,
    "top": 129.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 141.07373046875,
    "top": 129.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/email.png",
    "left": 227.94462890625002,
    "top": 129.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 240.94462890625002,
    "top": 129.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/linkedin.png",
    "left": 354.19677734375,
    "top": 129.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 367.19677734375,
    "top": 129.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/github.png",
    "left": 171.38212890625,
    "top": 144.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 184.38212890625,
    "top": 144.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/website.png",
    "left": 284.41904296875,
    "top": 144.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 297.41904296875,
    "top": 144.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/location.png",
    "left": 369.08134765625,
    "top": 144.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 382.08134765625,
    "top": 144.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 76,
    "top": 166.0,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/summary.png",
    "left": 54,
    "top": 203.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 203.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 216.475,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 76,
    "top": 224.475,
    "width": 443,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/experience.png",
    "left": 54,
    "top": 272.475,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 272.475,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 285.95000000000005,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 76,
    "top": 297.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-76163aec5d3a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 76,
    "top": 313.95000000000005,
    "width": 443,
    "height": 41,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-76163aec5d3a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 76,
    "top": 368.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1db74bbd57cf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 76,
    "top": 384.95000000000005,
    "width": 443,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1db74bbd57cf",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 76,
    "top": 425.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1266e6644a58",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 76,
    "top": 441.95000000000005,
    "width": 443,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-1266e6644a58",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/education.png",
    "left": 54,
    "top": 476.95000000000005,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 476.95000000000005,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 490.42500000000007,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 76,
    "top": 498.42500000000007,
    "width": 443,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-25b85508f7b9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 76,
    "top": 515.4250000000001,
    "width": 443,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-25b85508f7b9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 76,
    "top": 532.4250000000001,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-25b85508f7b9",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/skills.png",
    "left": 54,
    "top": 565.4250000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 565.4250000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 578.9000000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 76,
    "top": 586.9000000000001,
    "width": 443,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7775363c54b4",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/languages.png",
    "left": 54,
    "top": 621.9000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 621.9000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 635.3750000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 76,
    "top": 643.3750000000001,
    "width": 443,
    "height": 41,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const porticoTemplate = PORTICO_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
