/**
 * Portico template (`layouts: ["icons"]`).
 *
 * Centered masthead with icon contact chrome; left-aligned body with
 * icon-in-gutter section headings.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/portico.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const PORTICO_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 76,
    "top": 800,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 504,
    "top": 808,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 76,
    "top": 18.0,
    "width": 443,
    "height": 33,
    "fontSize": 29,
    "lineHeight": 33,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "rectangle",
    "left": 258.5,
    "top": 59.0,
    "width": 78.0,
    "height": 100.0,
    "backgroundColor": "#FCFBF8",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": 6.0,
    "zIndex": 2,
    "page": 1,
    "id": "portico-photo-well",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 258.5,
    "top": 59.0,
    "width": 78.0,
    "height": 100.0,
    "backgroundColor": "#E4DED2",
    "borderWidth": 0.75,
    "filled": false,
    "borderRadius": 6.0,
    "zIndex": 3,
    "page": 1,
    "id": "portico-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 76,
    "top": 169.0,
    "width": 443,
    "height": 14,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 2.0,
    "color": "#7C6A52",
    "fontFamily": "Inter",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/phone.png",
    "left": 84.05683593750001,
    "top": 193.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 97.05683593750001,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/email.png",
    "left": 181.01152343750002,
    "top": 193.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 194.01152343750002,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/linkedin.png",
    "left": 302.6166015625,
    "top": 193.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 315.6166015625,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/github.png",
    "left": 422.62617187500007,
    "top": 193.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 435.62617187500007,
    "top": 193.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/website.png",
    "left": 230.22412109375,
    "top": 208.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 243.22412109375,
    "top": 208.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/location.png",
    "left": 310.23935546875,
    "top": 208.0,
    "width": 12.0,
    "height": 12.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Inter",
    "color": "#83786B",
    "left": 323.23935546875,
    "top": 208.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "line",
    "left": 76,
    "top": 224.0,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 193.0,
        "maxWidth": 443.0
      },
      "text": {
        "fontFamily": "Inter",
        "fontSizePt": 8.4,
        "colorHex": "#83786B"
      },
      "icon": {
        "sizePt": 12.0,
        "theme": "portico"
      },
      "metrics": {
        "iconGap": 13.0,
        "itemPad": 16.0,
        "lineStep": 15.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 76,
          "top": 169.0,
          "width": 443,
          "height": 14,
          "fontSizePt": 10,
          "lineHeight": 14,
          "fontFamily": "Inter",
          "colorHex": "#7C6A52",
          "letterSpacing": 2.0,
          "align": "center",
          "autoHeight": true,
          "textTransform": "none",
          "bold": false
        },
        "blockPt": 24.0,
        "present": true
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/summary.png",
    "left": 54,
    "top": 261.0,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 261.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 274.475,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz.",
    "left": 76,
    "top": 282.475,
    "width": 443,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/experience.png",
    "left": 54,
    "top": 330.475,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 330.475,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 343.95000000000005,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 76,
    "top": 351.95000000000005,
    "width": 443,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e6c8707e4251",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 76,
    "top": 370.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e6c8707e4251",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.",
    "left": 76,
    "top": 386.95000000000005,
    "width": 443,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e6c8707e4251",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 76,
    "top": 410.95000000000005,
    "width": 443,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9d15020d11e9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 76,
    "top": 429.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9d15020d11e9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.",
    "left": 76,
    "top": 445.95000000000005,
    "width": 443,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9d15020d11e9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 76,
    "top": 469.95000000000005,
    "width": 443,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d92cbd913fe",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 76,
    "top": 488.95000000000005,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d92cbd913fe",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 76,
    "top": 504.95000000000005,
    "width": 443,
    "height": 14,
    "fontSize": 9.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5d92cbd913fe",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/education.png",
    "left": 54,
    "top": 539.95,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 539.95,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 553.4250000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 76,
    "top": 561.4250000000001,
    "width": 443,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f84eeefd3b96",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 76,
    "top": 578.4250000000001,
    "width": 443,
    "height": 13,
    "fontSize": 10.4,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#22221F",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f84eeefd3b96",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 76,
    "top": 595.4250000000001,
    "width": 443,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#83786B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f84eeefd3b96",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/skills.png",
    "left": 54,
    "top": 628.4250000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 628.4250000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 641.9000000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna",
    "left": 76,
    "top": 649.9000000000001,
    "width": 443,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-bccb4b5fc4cb",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/portico/languages.png",
    "left": 54,
    "top": 684.9000000000001,
    "width": 14.0,
    "height": 14.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#7C6A52",
    "left": 76,
    "top": 684.9000000000001,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.45,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 76,
    "top": 698.3750000000001,
    "width": 443,
    "height": 1,
    "backgroundColor": "#E4DED2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 76.0,
    "top": 706.3750000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#7C6A52"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-913efe06a720"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 186.75,
    "top": 706.3750000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#7C6A52"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-913efe06a720"
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 706.3750000000001,
    "width": 102.75,
    "height": 14,
    "fontSize": 9.3,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2A2A28",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#7C6A52"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-913efe06a720"
  }
];

export const porticoTemplate = PORTICO_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
