/**
 * Regent template (`layouts: ["single", "icons"]`).
 *
 * Monochrome executive editorial layout with compact serif summary copy.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/regent.py`) for
 * representative demo content (Alexandra Nowak — strategy consultant with three roles, one degree, four skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const REGENT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#6A6A6A",
    "left": 510,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Alexandra Nowak",
    "left": 62,
    "top": 47.0,
    "width": 471,
    "height": 41,
    "fontSize": 38,
    "lineHeight": 41,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "textarea",
    "content": "Strategy Consultant",
    "left": 62,
    "top": 97.0,
    "width": 471,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 13,
    "letterSpacing": 2.0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/phone.png",
    "left": 104.8372,
    "top": 128.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "regent-contact"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#6A6A6A",
    "left": 115.8372,
    "top": 128.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "regent-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/email.png",
    "left": 203.78320000000002,
    "top": 128.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "regent-contact"
  },
  {
    "category": "text",
    "content": "alexandra@example.com",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#6A6A6A",
    "left": 214.78320000000002,
    "top": 128.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "regent-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/linkedin.png",
    "left": 338.0344,
    "top": 128.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "regent-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/alexandra-nowak",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#6A6A6A",
    "left": 349.0344,
    "top": 128.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "regent-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/regent/location.png",
    "left": 270.328,
    "top": 143.0,
    "width": 10.5,
    "height": 10.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "regent-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#6A6A6A",
    "left": 281.328,
    "top": 143.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "regent-contact"
  },
  {
    "category": "line",
    "left": 62,
    "top": 163.0,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "regent-contact",
      "mode": "centered",
      "anchor": {
        "centerX": 297.5,
        "startY": 128.0,
        "maxWidth": 471.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 8.4,
        "colorHex": "#6A6A6A"
      },
      "icon": {
        "sizePt": 10.5,
        "theme": "regent"
      },
      "metrics": {
        "iconGap": 11.0,
        "itemPad": 16.0,
        "lineStep": 15.0,
        "charWidth": 5.0
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "location"
      ]
    },
    "contactBandId": "regent-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Strategy Consultant",
          "left": 62,
          "top": 97.0,
          "width": 471,
          "height": 13,
          "fontSizePt": 9.5,
          "lineHeight": 13,
          "fontFamily": "Montserrat",
          "colorHex": "#151515",
          "letterSpacing": 2.0,
          "align": "left",
          "autoHeight": true,
          "textTransform": "uppercase",
          "bold": false
        },
        "blockPt": 31.0,
        "present": true
      },
      "contactBandId": "regent-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Montserrat",
    "color": "#151515",
    "left": 62,
    "top": 200.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.75,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 214.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Przekształcam złożone strategie w decyzje, które porządkują organizacje i budują mierzalny wzrost.",
    "left": 62,
    "top": 223.0,
    "width": 471,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "CormorantGaramond",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.7,
    "fontFamily": "Montserrat",
    "color": "#151515",
    "left": 62,
    "top": 258.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.75,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 272.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Senior Strategy Consultant",
    "left": 62,
    "top": 281.0,
    "width": 471,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e206a2f0bc86",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Advisory   ·   2021 – obecnie",
    "left": 62,
    "top": 300.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6A6A6A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e206a2f0bc86",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę projekty transformacyjne dla zespołów zarządzających.\n• Tworzę rekomendacje łączące dane z perspektywą biznesową.",
    "left": 62,
    "top": 316.0,
    "width": 471,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e206a2f0bc86",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Business Analyst",
    "left": 62,
    "top": 354.0,
    "width": 471,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5e9ad4f9249b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   2018 – 2021",
    "left": 62,
    "top": 373.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6A6A6A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5e9ad4f9249b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Analizowałam modele operacyjne i przygotowywałam materiały dla zarządu.\n• Projektowałam modele działania dla zespołów w fazie wzrostu.",
    "left": 62,
    "top": 389.0,
    "width": 471,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5e9ad4f9249b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Project Analyst",
    "left": 62,
    "top": 427.0,
    "width": 471,
    "height": 15,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a1082e72041b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Civic Partners   ·   2016 – 2018",
    "left": 62,
    "top": 446.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6A6A6A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a1082e72041b",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam wdrożenia strategiczne i analizę efektywności inicjatyw.",
    "left": 62,
    "top": 462.0,
    "width": 471,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a1082e72041b",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.7,
    "fontFamily": "Montserrat",
    "color": "#151515",
    "left": 62,
    "top": 497.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.75,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 511.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister ekonomii",
    "left": 62,
    "top": 520.0,
    "width": 471,
    "height": 14,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-07cb400bd424",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Szkoła Główna Handlowa",
    "left": 62,
    "top": 538.0,
    "width": 471,
    "height": 14,
    "fontSize": 10.5,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#151515",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-07cb400bd424",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2013 – 2018",
    "left": 62,
    "top": 556.0,
    "width": 471,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.5,
    "letterSpacing": 0,
    "color": "#6A6A6A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-07cb400bd424",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.7,
    "fontFamily": "Montserrat",
    "color": "#151515",
    "left": 62,
    "top": 589.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.75,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 603.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Transformacja  ·  Analiza biznesowa  ·  Facylitacja",
    "left": 62,
    "top": 612.0,
    "width": 471,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-dae9548ca675",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.7,
    "fontFamily": "Montserrat",
    "color": "#151515",
    "left": 62,
    "top": 647.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.75,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 62,
    "top": 661.2,
    "width": 471,
    "height": 0.8,
    "backgroundColor": "#CFCFCF",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 62.0,
    "top": 670.0,
    "width": 109.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#151515"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7d5f04a23a1a"
  },
  {
    "category": "textarea",
    "content": "Angielski — C2",
    "left": 179.75,
    "top": 670.0,
    "width": 109.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#151515"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7d5f04a23a1a"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 297.5,
    "top": 670.0,
    "width": 109.75,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#242424",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#151515"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-7d5f04a23a1a"
  }
];

export const regentTemplate = REGENT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
