/**
 * Regent template (`layouts: ["single"]`).
 *
 * Executive single column with a personalized oxblood seal.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/regent.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const REGENT_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCFBF8",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 46,
    "top": 36,
    "width": 3,
    "height": 770,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "rectangle",
    "left": 56,
    "top": 36,
    "width": 483,
    "height": 770,
    "backgroundColor": "#D6CCC3",
    "borderWidth": 0.7,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 88,
    "top": 783,
    "width": 411,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 88,
    "top": 796,
    "width": 6,
    "height": 6,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Inter",
    "color": "#756F6B",
    "left": 484,
    "top": 791,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "Jan Kowalski",
    "fontSize": 33,
    "fontFamily": "CormorantGaramond",
    "color": "#211D1B",
    "left": 88,
    "top": 61,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.15,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Dyrektor Strategii i Rozwoju",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 90,
    "top": 105,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.65,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa ·…",
    "fontSize": 8.5,
    "fontFamily": "Inter",
    "color": "#756F6B",
    "left": 90,
    "top": 130,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 88,
    "top": 154,
    "width": 418,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "ellipse",
    "left": 445,
    "top": 54,
    "width": 58,
    "height": 46,
    "backgroundColor": "#733B43",
    "filled": false,
    "borderWidth": 0.9,
    "zIndex": 3,
    "page": 1,
    "id": "regent-seal",
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 461,
    "top": 64,
    "width": 26,
    "height": 26,
    "backgroundColor": "#A66B5B",
    "filled": false,
    "borderWidth": 0.8,
    "zIndex": 3,
    "page": 1,
    "id": "regent-signet",
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "JK",
    "fontSize": 9.5,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 466,
    "top": 72,
    "zIndex": 4,
    "page": 1,
    "bold": true,
    "italic": false,
    "id": "regent-initials",
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 454,
    "top": 105,
    "width": 40,
    "height": 1,
    "backgroundColor": "#A66B5B",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 75,
    "top": 191.5,
    "width": 7,
    "height": 7,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 96,
    "top": 190.0,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.5,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 96,
    "top": 202.15,
    "width": 44,
    "height": 1.25,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 148,
    "top": 202.15,
    "width": 358,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 96,
    "top": 210.15,
    "width": 410,
    "height": 42,
    "fontSize": 9.6,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 75,
    "top": 274.65,
    "width": 7,
    "height": 7,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 96,
    "top": 273.15,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.5,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 96,
    "top": 285.29999999999995,
    "width": 44,
    "height": 1.25,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 148,
    "top": 285.29999999999995,
    "width": 358,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 96,
    "top": 293.29999999999995,
    "width": 410,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7ad767b17641",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 96,
    "top": 312.29999999999995,
    "width": 410,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#756F6B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7ad767b17641",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 96,
    "top": 328.29999999999995,
    "width": 410,
    "height": 42,
    "fontSize": 9.6,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7ad767b17641",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 96,
    "top": 380.29999999999995,
    "width": 410,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b04fc42310c1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 96,
    "top": 399.29999999999995,
    "width": 410,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#756F6B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b04fc42310c1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 96,
    "top": 415.29999999999995,
    "width": 410,
    "height": 28,
    "fontSize": 9.6,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b04fc42310c1",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 96,
    "top": 453.29999999999995,
    "width": 410,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-40b90e3c6b21",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 96,
    "top": 472.29999999999995,
    "width": 410,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#756F6B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-40b90e3c6b21",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 96,
    "top": 488.29999999999995,
    "width": 410,
    "height": 14,
    "fontSize": 9.6,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-40b90e3c6b21",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 75,
    "top": 524.8,
    "width": 7,
    "height": 7,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 96,
    "top": 523.3,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.5,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 96,
    "top": 535.4499999999999,
    "width": 44,
    "height": 1.25,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 148,
    "top": 535.4499999999999,
    "width": 358,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 96,
    "top": 543.4499999999999,
    "width": 410,
    "height": 14,
    "fontSize": 10.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7041f3ff78d2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 96,
    "top": 561.4499999999999,
    "width": 410,
    "height": 14,
    "fontSize": 10.6,
    "lineHeight": 13.5,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7041f3ff78d2",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 96,
    "top": 579.4499999999999,
    "width": 410,
    "height": 12,
    "fontSize": 8.5,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#756F6B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-7041f3ff78d2",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 75,
    "top": 613.9499999999999,
    "width": 7,
    "height": 7,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 96,
    "top": 612.4499999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.25,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 96,
    "top": 624.5999999999999,
    "width": 44,
    "height": 1.25,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 148,
    "top": 624.5999999999999,
    "width": 358,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 96,
    "top": 632.5999999999999,
    "width": 410,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f571fa5543cf",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 75,
    "top": 669.0999999999999,
    "width": 7,
    "height": 7,
    "backgroundColor": "#733B43",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.0,
    "fontFamily": "Inter",
    "color": "#733B43",
    "left": 96,
    "top": 667.5999999999999,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "letterSpacing": 1.5,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 96,
    "top": 679.7499999999999,
    "width": 44,
    "height": 1.25,
    "backgroundColor": "#733B43",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 148,
    "top": 679.7499999999999,
    "width": 358,
    "height": 1,
    "backgroundColor": "#D6CCC3",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 96.0,
    "top": 687.7499999999999,
    "width": 94.5,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 9,
        "end": 17,
        "italic": true,
        "color": "#733B43"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-2cab1f4d5038"
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 198.5,
    "top": 687.7499999999999,
    "width": 94.5,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#733B43"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-2cab1f4d5038"
  },
  {
    "category": "textarea",
    "content": "Francuski — B2",
    "left": 301.0,
    "top": 687.7499999999999,
    "width": 94.5,
    "height": 14,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#211D1B",
    "fontFamily": "Inter",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "runs": [
      {
        "start": 12,
        "end": 14,
        "italic": true,
        "color": "#733B43"
      }
    ],
    "flowRole": "grid-member",
    "flowGroup": "record-2cab1f4d5038"
  }
];

export const regentTemplate = REGENT_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
