/**
 * Slate template (`layouts: ["sidebar", "icons"]`).
 *
 * Steel blueprint sidebar with rectangular photo and grid chrome.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/slate.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const SLATE_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 178,
    "height": 842,
    "backgroundColor": "#F1F4F8",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 178,
    "top": 0,
    "width": 2,
    "height": 842,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 218,
    "top": 798,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 514,
    "top": 802,
    "width": 20,
    "height": 15,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 519,
    "top": 805,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 24,
    "top": 800,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#E7ECF2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 39,
    "top": 46,
    "width": 112,
    "height": 126,
    "backgroundColor": "#D3DAE2",
    "borderWidth": 0.9,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#1C2530",
    "borderWidth": 1.3,
    "zIndex": 3,
    "page": 1,
    "id": "slate-photo-frame",
    "photoSlot": "frame",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/portrait.png",
    "left": 66.0,
    "top": 80.0,
    "width": 46,
    "height": 46,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "slate-photo-glyph",
    "photoSlot": "glyph",
    "fixedToPage": true,
    "locked": true,
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 29,
    "top": 36,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 140,
    "top": 161,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 33,
    "top": 170,
    "width": 112,
    "height": 4,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 194.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/references.png",
    "left": 27,
    "top": 196.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "KONTAKT",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 210.0,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/phone.png",
    "left": 25,
    "top": 222.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 223.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/email.png",
    "left": 25,
    "top": 241.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 242.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/linkedin.png",
    "left": 25,
    "top": 260.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 261.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/github.png",
    "left": 25,
    "top": 279.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 280.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/website.png",
    "left": 25,
    "top": 298.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 299.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate-accent/location.png",
    "left": 25,
    "top": 317.0,
    "width": 11,
    "height": 11,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.3,
    "fontFamily": "Montserrat",
    "color": "#3A424C",
    "left": 42,
    "top": 318.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 356.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/skills.png",
    "left": 27,
    "top": 358.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 359.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 372.0,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Strategia\n• Leadership\n• P&L\n• Negocjacje\n• Transformacja organizacyjna",
    "left": 25,
    "top": 377.0,
    "width": 128,
    "height": 66.2,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 455.2,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/languages.png",
    "left": 27,
    "top": 457.2,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 458.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 471.2,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 25,
    "top": 476.2,
    "width": 128,
    "height": 42.12,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 530.32,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/education.png",
    "left": 27,
    "top": 532.32,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 533.32,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 546.32,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 25,
    "top": 551.32,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c296a1dcaf55",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 25,
    "top": 568.32,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c296a1dcaf55",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 25,
    "top": 585.32,
    "width": 128,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#7A8794",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c296a1dcaf55",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JAN KOWALSKI",
    "fontSize": 24,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 218,
    "top": 48,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.4,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 86,
    "width": 175.20000000000002,
    "height": 20,
    "backgroundColor": "#3E5C76",
    "zIndex": 1,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 230,
    "top": 92,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.15,
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 218,
    "top": 119,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 141,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 505,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 514,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 523,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 505,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 514,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 523,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 505,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 514,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 523,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 177.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/summary.png",
    "left": 221,
    "top": 180.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 244,
    "top": 181.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 244,
    "top": 198.0,
    "width": 303,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 218,
    "top": 206.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 267.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/slate/experience.png",
    "left": 221,
    "top": 270.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 244,
    "top": 271.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 244,
    "top": 288.0,
    "width": 303,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 218,
    "top": 300.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#3E5C76",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0a8bce4c4b53",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 218,
    "top": 316.0,
    "width": 329,
    "height": 53,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0a8bce4c4b53",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 218,
    "top": 383.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#3E5C76",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f467d5a2b0cd",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 218,
    "top": 399.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f467d5a2b0cd",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 218,
    "top": 453.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#3E5C76",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3f5ee18d0d78",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 218,
    "top": 469.0,
    "width": 329,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3f5ee18d0d78",
    "flowRole": "content"
  }
];

export const slateTemplate = SLATE_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
