/**
 * Slate template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/slate.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const SLATE_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 178,
    "height": 842,
    "backgroundColor": "#F1F4F8",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 178,
    "top": 0,
    "width": 2,
    "height": 842,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 218,
    "top": 798,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 514,
    "top": 802,
    "width": 20,
    "height": 15,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 519,
    "top": 805,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 24,
    "top": 800,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#E7ECF2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 39,
    "top": 46,
    "width": 112,
    "height": 126,
    "backgroundColor": "#D3DAE2",
    "borderWidth": 0.9,
    "filled": false,
    "borderRadius": null,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#1C2530",
    "borderWidth": 1.3,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "slate-photo-frame",
    "photoSlot": "frame",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/portrait.png",
    "left": 66.0,
    "top": 80.0,
    "width": 46,
    "height": 46,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "slate-photo-glyph",
    "photoSlot": "glyph",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 29,
    "top": 36,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 140,
    "top": 161,
    "width": 9,
    "height": 9,
    "backgroundColor": "#3E5C76",
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 33,
    "top": 170,
    "width": 112,
    "height": 4,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 194.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate/skills.png",
    "left": 27,
    "top": 196.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 210.0,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• ISO 27001\n• RODO/GDPR\n• audyt wewnętrzny\n• ocena ryzyka\n• zarządzanie politykami bezpieczeństwa\n• podstawy SIEM\n• MS Office\n• SQL",
    "left": 25,
    "top": 215.0,
    "width": 128,
    "height": 109.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 336.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate/languages.png",
    "left": 27,
    "top": 338.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 339.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 352.0,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nangielski - C1\nfrancuski - B1",
    "left": 25,
    "top": 357.0,
    "width": 128,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 406.0,
    "width": 16,
    "height": 16,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate/education.png",
    "left": 27,
    "top": 408.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 49,
    "top": 409.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 49,
    "top": 422.0,
    "width": 46,
    "height": 1,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister prawa — specjalność: Prawo nowych technologii",
    "left": 25,
    "top": 427.0,
    "width": 128,
    "height": 37,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-eb09f00ee090",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "UMCS Lublin",
    "left": 25,
    "top": 468.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-eb09f00ee090",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Lublin   ·   ukończono czerwiec 2020",
    "left": 25,
    "top": 485.0,
    "width": 128,
    "height": 24,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#7A8794",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-eb09f00ee090",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Praca magisterska dotycząca ochrony danych osobowych w chmurze obliczeniowej.",
    "left": 25,
    "top": 513.0,
    "width": 128,
    "height": 37,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-eb09f00ee090",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "AGNIESZKA KACZMAREK",
    "fontSize": 24,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 218,
    "top": 48,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.4,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 86,
    "width": 153.60000000000002,
    "height": 20,
    "backgroundColor": "#3E5C76",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "GRC & COMPLIANCE ANALYST",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#FFFFFF",
    "left": 230,
    "top": 92,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.15,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/phone.png",
    "left": 218.0,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 574 331 809",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 233.0,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/email.png",
    "left": 324.0,
    "top": 119.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "agnieszka.kaczmarek.grc@outlook.com",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 339.0,
    "top": 119.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/linkedin.png",
    "left": 218.0,
    "top": 135.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/agnieszka-kaczmarek",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 233.0,
    "top": 135.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/github.png",
    "left": 218.0,
    "top": 151.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/akaczmarek",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 233.0,
    "top": 151.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/website.png",
    "left": 354.0,
    "top": 151.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "agnieszkakaczmarek.pl",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 369.0,
    "top": 151.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate-accent/location.png",
    "left": 218.0,
    "top": 167.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Lublin",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#7A8794",
    "left": 233.0,
    "top": 167.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 189.0,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 505,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 523,
    "top": 39,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 505,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 523,
    "top": 48,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 505,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 514,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 523,
    "top": 57,
    "width": 5,
    "height": 5,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 226.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate/summary.png",
    "left": 221,
    "top": 229.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 244,
    "top": 230.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 244,
    "top": 247.0,
    "width": 303,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka GRC wspierająca organizacje w utrzymaniu zgodności z ISO 27001 i RODO. Prowadzę audyty wewnętrzne, oceny ryzyka i szkolenia świadomościowe dla pracowników. Łączę wiedzę prawną z podstawami technicznymi bezpieczeństwa.",
    "left": 218,
    "top": 255.0,
    "width": 329,
    "height": 53,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 329.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#3E5C76",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/slate/experience.png",
    "left": 221,
    "top": 332.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#1C2530",
    "left": 244,
    "top": 333.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 244,
    "top": 350.0,
    "width": 303,
    "height": 1,
    "backgroundColor": "#D3DAE2",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "GRC & Compliance Analyst",
    "left": 218,
    "top": 358.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ed3502501062",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian IT Services   ·   Lublin   ·   Wrzesień 2022 – obecnie",
    "left": 218,
    "top": 377.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#3E5C76",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ed3502501062",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzę audyty wewnętrzne zgodności z ISO 27001 i RODO.\n• Przygotowuję rejestry ryzyka oraz plany działań naprawczych.\n• Organizuję szkolenia świadomościowe z zakresu bezpieczeństwa dla pracowników.\n• Współpracuję z zespołem IT nad wdrażaniem polityk bezpieczeństwa.",
    "left": 218,
    "top": 393.0,
    "width": 329,
    "height": 66,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-ed3502501062",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka ds. Zgodności",
    "left": 218,
    "top": 469.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#1C2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e68600d16a85",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Cascade Retail Group   ·   Lublin   ·   Styczeń 2021 – Sierpień 2022",
    "left": 218,
    "top": 488.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#3E5C76",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e68600d16a85",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Wspierałam dział prawny w ocenie zgodności procesów z RODO.\n• Prowadziłam rejestr czynności przetwarzania danych osobowych.",
    "left": 218,
    "top": 504.0,
    "width": 329,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#3A424C",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e68600d16a85",
    "flowRole": "content"
  }
];

export const slateTemplate = SLATE_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
