/**
 * Sterling template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/sterling.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const STERLING_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F8FA",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 210.0,
    "height": 842,
    "backgroundColor": "#EDF1F6",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 0,
    "width": 1.0,
    "height": 842,
    "backgroundColor": "#C7CFDA",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 158.0,
    "backgroundColor": "#EDF1F6",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6B7684",
    "left": 531.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Krawczyk",
    "left": 67.5,
    "top": 46.0,
    "width": 460.0,
    "height": 34,
    "fontSize": 30.0,
    "lineHeight": 34.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "SECURITY OPERATIONS SPECIALIST",
    "left": 67.5,
    "top": 86.0,
    "width": 460.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 2.0,
    "color": "#4A6FA5",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "julia.krawczyk.secops@gmail.com · +48 692 517 843 · Toruń · linkedin.com/in/julia-krawc… · github.com/jkrawczyk · juliakrawczyk.pl",
    "left": 67.5,
    "top": 111.0,
    "width": 460.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0.3,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 158.0,
    "width": 511.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 188.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 204.28,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Specjalistka ds. operacji bezpieczeństwa łącząca monitorowanie alertów z zarządzaniem podatnościami. Pracuję w rozproszonym zespole SOC obsługującym klientów z sektora finansowego i produkcyjnego.",
    "left": 34.0,
    "top": 215.68,
    "width": 152.0,
    "height": 97,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 338.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 354.96,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• analiza SIEM/logów\n• zarządzanie podatnościami\n• Nessus\n• Wireshark\n• MITRE ATT&CK\n• Active Directory\n• Python\n• SQL\n• Linux\n• Windows Server",
    "left": 34.0,
    "top": 359.68,
    "width": 152.0,
    "height": 121.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 492.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 508.96,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nangielski - C1\nhiszpański - A2",
    "left": 34.0,
    "top": 513.6800000000001,
    "width": 152.0,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 14.0,
    "fontFamily": "Montserrat",
    "color": "#26313F",
    "left": 245.0,
    "top": 188.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 208.7,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Security Operations Specialist",
    "left": 245.0,
    "top": 217.7,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5aef13c6c3cd"
  },
  {
    "category": "textarea",
    "content": "SecuraNet Sp. z o.o.   ·   Toruń   ·   Czerwiec 2022 – obecnie",
    "left": 245.0,
    "top": 236.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5aef13c6c3cd"
  },
  {
    "category": "textarea",
    "content": "• Monitoruję alerty bezpieczeństwa i prowadzę triage w narzędziu SIEM.\n• Prowadzę cykliczne skanowanie podatności i priorytetyzację ryzyk.\n• Koordynuję komunikację z klientami w trakcie obsługi incydentów.\n• Rozwijam dokumentację procedur SOC i playbooki reagowania.",
    "left": 245.0,
    "top": 252.7,
    "width": 300.0,
    "height": 111,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-5aef13c6c3cd"
  },
  {
    "category": "textarea",
    "content": "Specjalistka ds. Wsparcia IT",
    "left": 245.0,
    "top": 373.7,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ce52fea21a5"
  },
  {
    "category": "textarea",
    "content": "Cascade Retail Group   ·   Toruń   ·   Styczeń 2021 – Maj 2022",
    "left": 245.0,
    "top": 392.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ce52fea21a5"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwałam zgłoszenia serwisowe i administrowałam kontami użytkowników.",
    "left": 245.0,
    "top": 408.7,
    "width": 300.0,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0ce52fea21a5"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 14.0,
    "fontFamily": "Montserrat",
    "color": "#26313F",
    "left": 245.0,
    "top": 457.7,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 478.4,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister informatyki — specjalność: Bezpieczeństwo systemów",
    "left": 245.0,
    "top": 487.4,
    "width": 300.0,
    "height": 28,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8eace8cd934"
  },
  {
    "category": "textarea",
    "content": "UMK Toruń",
    "left": 245.0,
    "top": 519.4,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8eace8cd934"
  },
  {
    "category": "textarea",
    "content": "Toruń   ·   ukończono czerwiec 2020",
    "left": 245.0,
    "top": 537.4,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8eace8cd934"
  },
  {
    "category": "textarea",
    "content": "• Praca magisterska dotycząca automatyzacji reguł korelacyjnych SIEM.",
    "left": 245.0,
    "top": 553.4,
    "width": 300.0,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c8eace8cd934"
  }
];

export const sterlingTemplate = STERLING_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
