/**
 * Sterling template (`layouts: ["sidebar"]`).
 *
 * Institutional two-column layout with wide sidebar rail.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/sterling.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const STERLING_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#F7F8FA",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 158.0,
    "backgroundColor": "#EDF1F6",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 158.0,
    "width": 210.0,
    "height": 684.0,
    "backgroundColor": "#EDF1F6",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 158.0,
    "width": 1.0,
    "height": 684.0,
    "backgroundColor": "#C7CFDA",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#6B7684",
    "left": 531.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 67.5,
    "top": 46.0,
    "width": 460.0,
    "height": 34,
    "fontSize": 30.0,
    "lineHeight": 34.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "left": 67.5,
    "top": 86.0,
    "width": 460.0,
    "height": 15,
    "fontSize": 11.5,
    "lineHeight": 15.0,
    "letterSpacing": 2.0,
    "color": "#4A6FA5",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "textarea",
    "content": "jan.kowalski@email.com · +48 600 000 000 · Warszawa · linkedin.com/in/jkowalski · github.com/jkowalski · jankowalski.pl",
    "left": 67.5,
    "top": 111.0,
    "width": 460.0,
    "height": 27,
    "fontSize": 9.4,
    "lineHeight": 13.5,
    "letterSpacing": 0.3,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "center",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 158.0,
    "width": 511.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 188.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 204.28,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 34.0,
    "top": 215.68,
    "width": 152.0,
    "height": 73,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 314.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 330.96,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Strategia\n• Leadership\n• P&L\n• Negocjacje\n• Transformacja organizacyjna",
    "left": 34.0,
    "top": 335.68,
    "width": 152.0,
    "height": 66.2,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 9.4,
    "fontFamily": "Montserrat",
    "color": "#33517A",
    "left": 34.0,
    "top": 413.88,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 34.0,
    "top": 430.15999999999997,
    "width": 22,
    "height": 1.4,
    "backgroundColor": "#4A6FA5",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nFrancuski - B2",
    "left": 34.0,
    "top": 434.88,
    "width": 152.0,
    "height": 42.12,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 14.0,
    "fontFamily": "Montserrat",
    "color": "#26313F",
    "left": 245.0,
    "top": 188.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 208.7,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 245.0,
    "top": 217.7,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2e527a1f8186",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 245.0,
    "top": 236.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2e527a1f8186",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 245.0,
    "top": 252.7,
    "width": 300.0,
    "height": 83,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2e527a1f8186",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 245.0,
    "top": 345.7,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-86410ff658ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 245.0,
    "top": 364.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-86410ff658ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 245.0,
    "top": 380.7,
    "width": 300.0,
    "height": 42,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-86410ff658ba",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 245.0,
    "top": 432.7,
    "width": 300.0,
    "height": 15,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db6132e305b3",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 245.0,
    "top": 451.7,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db6132e305b3",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 245.0,
    "top": 467.7,
    "width": 300.0,
    "height": 28,
    "fontSize": 9.5,
    "lineHeight": 13.8,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-db6132e305b3",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 14.0,
    "fontFamily": "Montserrat",
    "color": "#26313F",
    "left": 245.0,
    "top": 516.7,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 245.0,
    "top": 537.4000000000001,
    "width": 300.0,
    "height": 1,
    "backgroundColor": "#C7CFDA",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 245.0,
    "top": 546.4000000000001,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-acbb1b827f4e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 245.0,
    "top": 564.4000000000001,
    "width": 300.0,
    "height": 14,
    "fontSize": 11.2,
    "lineHeight": 14.0,
    "letterSpacing": 0,
    "color": "#26313F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-acbb1b827f4e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 245.0,
    "top": 582.4000000000001,
    "width": 300.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 11.8,
    "letterSpacing": 0,
    "color": "#6B7684",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-acbb1b827f4e",
    "flowRole": "content"
  }
];

export const sterlingTemplate = STERLING_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
