/**
 * Tessera template (`layouts: ["sidebar", "icons"]`).
 *
 * Mosaic sidebar with rectangular photo and coral accent tiles.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/tessera.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const TESSERA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCF8F2",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 178,
    "height": 842,
    "backgroundColor": "#F2DDD2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 178,
    "top": 0,
    "width": 4,
    "height": 842,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 218,
    "top": 798,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 524,
    "top": 807,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 24,
    "top": 800,
    "width": 8,
    "height": 8,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 42,
    "top": 797,
    "width": 44,
    "height": 10,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 20,
    "top": 25,
    "width": 138,
    "height": 80,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1.1,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 136,
    "top": 26,
    "width": 19,
    "height": 19,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 26,
    "top": 48,
    "width": 112,
    "height": 126,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "tessera-photo-frame",
    "photoSlot": "frame",
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/portrait.png",
    "left": 65.0,
    "top": 79.0,
    "width": 48,
    "height": 48,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "content",
    "id": "tessera-photo-glyph",
    "photoSlot": "glyph",
    "fixedToPage": true,
    "locked": true,
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 28,
    "top": 158,
    "width": 12,
    "height": 12,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 192.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 194.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/education.png",
    "left": 29,
    "top": 196.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 210.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 25,
    "top": 215.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2f1375673851",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 25,
    "top": 232.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2f1375673851",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 25,
    "top": 249.0,
    "width": 128,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#806F78",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-2f1375673851",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 271.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 273.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/skills.png",
    "left": 29,
    "top": 275.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 276.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 289.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Strategia\n• Leadership\n• P&L\n• Negocjacje\n• Transformacja organizacyjna",
    "left": 25,
    "top": 294.0,
    "width": 128,
    "height": 66.2,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 370.2,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 372.2,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/languages.png",
    "left": 29,
    "top": 374.2,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 375.2,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 388.2,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nFrancuski - B2",
    "left": 25,
    "top": 393.2,
    "width": 128,
    "height": 42.12,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JAN KOWALSKI",
    "fontSize": 24,
    "fontFamily": "PlayfairDisplay",
    "color": "#4A2347",
    "left": 218,
    "top": 48,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.2,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 88,
    "width": 164,
    "height": 22,
    "backgroundColor": "#E15D4F",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "DYREKTOR STRATEGII I ROZWOJU",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#FFFDFC",
    "left": 228,
    "top": 94,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.15,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/phone.png",
    "left": 218.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 600 000 000",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/email.png",
    "left": 324.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jan.kowalski@email.com",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 339.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/linkedin.png",
    "left": 218.0,
    "top": 137.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jkowalski",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 137.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/github.png",
    "left": 374.0,
    "top": 137.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/jkowalski",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 389.0,
    "top": 137.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/website.png",
    "left": 218.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "jankowalski.pl",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/location.png",
    "left": 319.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 334.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 175.0,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 491,
    "top": 42,
    "width": 41,
    "height": 41,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 499,
    "top": 50,
    "width": 41,
    "height": 41,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 506,
    "top": 58,
    "width": 13,
    "height": 13,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "ellipse",
    "left": 487,
    "top": 90,
    "width": 56,
    "height": 15,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 210.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 212.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 209.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/summary.png",
    "left": 223,
    "top": 215.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 215.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 233.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty bez utraty jakości relacji.",
    "left": 218,
    "top": 241.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 300.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 302.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 299.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/experience.png",
    "left": 223,
    "top": 305.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 305.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 323.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii",
    "left": 218,
    "top": 331.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c450e0a74d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 218,
    "top": 350.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c450e0a74d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.\n• Prowadzi mentoring liderów odpowiedzialnych za kluczowe programy.",
    "left": 218,
    "top": 366.0,
    "width": 329,
    "height": 53,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-67c450e0a74d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Menedżer Rozwoju",
    "left": 218,
    "top": 429.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6f27bbf91191",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 218,
    "top": 448.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6f27bbf91191",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 218,
    "top": 464.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6f27bbf91191",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Konsultant Strategiczny",
    "left": 218,
    "top": 514.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8206b7dbaacb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 218,
    "top": 533.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8206b7dbaacb",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 218,
    "top": 549.0,
    "width": 329,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8206b7dbaacb",
    "flowRole": "content"
  }
];

export const tesseraTemplate = TESSERA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
