/**
 * Tessera template (auto-generated demo content).
 *
 * Landing-page / picker preview content, generated from the backend
 * template's own output (`backend/app/services/cv_templates/templates/tessera.py`)
 * for representative demo content, so the picker preview matches what
 * `/ai/fill_template` produces pixel-for-pixel. Image `src` values are stored
 * relative and get the API base prepended at load time. The array already
 * carries `flowRole` / `flowGroup` / `preserveInitialLayout` from the
 * generator, so it is exported as-is (only the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const TESSERA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCF8F2",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 178,
    "height": 842,
    "backgroundColor": "#F2DDD2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 178,
    "top": 0,
    "width": 4,
    "height": 842,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 218,
    "top": 798,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 524,
    "top": 807,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 24,
    "top": 800,
    "width": 8,
    "height": 8,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 42,
    "top": 797,
    "width": 44,
    "height": 10,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 20,
    "top": 25,
    "width": 138,
    "height": 80,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1.1,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 136,
    "top": 26,
    "width": 19,
    "height": 19,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 26,
    "top": 48,
    "width": 112,
    "height": 126,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "tessera-photo-frame",
    "photoSlot": "frame",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/portrait.png",
    "left": 65.0,
    "top": 79.0,
    "width": 48,
    "height": 48,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "content",
    "id": "tessera-photo-glyph",
    "photoSlot": "glyph",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 28,
    "top": 158,
    "width": 12,
    "height": 12,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 192.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 194.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/education.png",
    "left": 29,
    "top": 196.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 210.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Inżynier teleinformatyki",
    "left": 25,
    "top": 215.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-369812bba2a2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Zachodniopomorski Uniwersytet Technologiczny",
    "left": 25,
    "top": 232.0,
    "width": 128,
    "height": 25,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-369812bba2a2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Szczecin   ·   ukończono lipiec 2020",
    "left": 25,
    "top": 261.0,
    "width": 128,
    "height": 24,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#806F78",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-369812bba2a2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Specjalizacja w projektowaniu i zabezpieczaniu sieci komputerowych.",
    "left": 25,
    "top": 289.0,
    "width": 128,
    "height": 37,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-369812bba2a2",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 336.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 338.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/skills.png",
    "left": 29,
    "top": 340.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 341.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 354.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• Palo Alto\n• Fortinet\n• Cisco IOS\n• VPN\n• segmentacja sieci\n• Wireshark\n• Nmap\n• podstawy IDS/firewall\n• Python\n• Linux",
    "left": 25,
    "top": 359.0,
    "width": 128,
    "height": 121.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 490.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 492.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/languages.png",
    "left": 29,
    "top": 494.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 495.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 508.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nangielski - B2\nniemiecki - B1",
    "left": 25,
    "top": 513.0,
    "width": 128,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "TOMASZ LEWANDOWSKI",
    "fontSize": 24,
    "fontFamily": "PlayfairDisplay",
    "color": "#4A2347",
    "left": 218,
    "top": 48,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.2,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 88,
    "width": 164,
    "height": 22,
    "backgroundColor": "#E15D4F",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "NETWORK SECURITY ENGINEER",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#FFFDFC",
    "left": 228,
    "top": 94,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.15,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/phone.png",
    "left": 218.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "+48 601 774 528",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/email.png",
    "left": 324.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "tomasz.lewandowski.net@gmail.com",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 339.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/linkedin.png",
    "left": 218.0,
    "top": 137.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/tomasz-lewandowski",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 137.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/github.png",
    "left": 218.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "github.com/tlewandowski",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/website.png",
    "left": 364.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "tomekl.dev",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 379.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/location.png",
    "left": 445.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Szczecin",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 460.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 175.0,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 491,
    "top": 42,
    "width": 41,
    "height": 41,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 499,
    "top": 50,
    "width": 41,
    "height": 41,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 506,
    "top": 58,
    "width": 13,
    "height": 13,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "ellipse",
    "left": 487,
    "top": 90,
    "width": 56,
    "height": 15,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 218,
    "top": 210.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 212.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 209.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/summary.png",
    "left": 223,
    "top": 215.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 215.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 233.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Inżynier bezpieczeństwa sieci z doświadczeniem w konfiguracji firewalli, VPN oraz segmentacji sieci dla klientów korporacyjnych. Wcześniej pracowałem jako administrator sieci, co daje mi solidne podstawy infrastrukturalne.",
    "left": 218,
    "top": 241.0,
    "width": 329,
    "height": 53,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 313.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 315.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 312.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "http://localhost:8000/template-assets/iconic/tessera/experience.png",
    "left": 223,
    "top": 318.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 318.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 336.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Network Security Engineer",
    "left": 218,
    "top": 344.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cb5333c6c77f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Quantera Networks   ·   Szczecin   ·   Marzec 2022 – obecnie",
    "left": 218,
    "top": 363.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cb5333c6c77f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Konfiguruję i utrzymuję firewalle nowej generacji (Palo Alto, Fortinet).\n• Wdrażam segmentację sieci oraz polityki dostępu zgodnie z zasadą least privilege.\n• Monitoruję ruch sieciowy pod kątem anomalii i podejrzanej aktywności.\n• Prowadzę dokumentację architektury sieci i procedur bezpieczeństwa.",
    "left": 218,
    "top": 379.0,
    "width": 329,
    "height": 66,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-cb5333c6c77f",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Administrator Sieci",
    "left": 218,
    "top": 455.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6b5499cce2ee",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Vantis Systems   ·   Szczecin   ·   Lipiec 2020 – Luty 2022",
    "left": 218,
    "top": 474.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6b5499cce2ee",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Administrowałem infrastrukturą sieciową LAN/WAN dla oddziałów firmy.\n• Konfigurowałem urządzenia Cisco i monitorowałem dostępność usług.",
    "left": 218,
    "top": 490.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-6b5499cce2ee",
    "flowRole": "content"
  }
];

export const tesseraTemplate = TESSERA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
