/**
 * Tessera template (`layouts: ["sidebar", "icons"]`).
 *
 * Mosaic sidebar with rectangular photo and coral accent tiles.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/tessera.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const TESSERA_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FCF8F2",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 178,
    "height": 842,
    "backgroundColor": "#F2DDD2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 178,
    "top": 0,
    "width": 4,
    "height": 842,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 218,
    "top": 798,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 524,
    "top": 807,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 24,
    "top": 800,
    "width": 8,
    "height": 8,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 42,
    "top": 797,
    "width": 44,
    "height": 10,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "ellipse",
    "left": 20,
    "top": 25,
    "width": 138,
    "height": 80,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1.1,
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 136,
    "top": 26,
    "width": 19,
    "height": 19,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 26,
    "top": 48,
    "width": 112,
    "height": 126,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 33,
    "top": 40,
    "width": 112,
    "height": 126,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.2,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "tessera-photo-frame",
    "photoSlot": "frame",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/portrait.png",
    "left": 65.0,
    "top": 79.0,
    "width": 48,
    "height": 48,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "content",
    "id": "tessera-photo-glyph",
    "photoSlot": "glyph",
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowLane": "sidebar"
  },
  {
    "category": "circle",
    "left": 28,
    "top": 158,
    "width": 12,
    "height": 12,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 4,
    "page": 1,
    "fixedToPage": true,
    "locked": true,
    "repeatOnContinuation": false,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 192.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 194.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/education.png",
    "left": 29,
    "top": 196.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 197.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 210.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 25,
    "top": 215.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b940f44d5397",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 25,
    "top": 232.0,
    "width": 128,
    "height": 13,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b940f44d5397",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 25,
    "top": 249.0,
    "width": 128,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 11.54,
    "letterSpacing": 0,
    "color": "#806F78",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b940f44d5397",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 271.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 273.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/skills.png",
    "left": 29,
    "top": 275.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 276.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 289.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• AML/KYC\n• Monitoring\n• CDD/EDD\n• Raporty SAR\n• Analiza transakcyjna",
    "left": 25,
    "top": 294.0,
    "width": 128,
    "height": 61.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 25,
    "top": 365.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#FFFDFC",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "rectangle",
    "left": 27,
    "top": 367.0,
    "width": 18,
    "height": 18,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/languages.png",
    "left": 29,
    "top": 369.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.6,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 51,
    "top": 370.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.85,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 51,
    "top": 383.0,
    "width": 50,
    "height": 1,
    "backgroundColor": "#E15D4F",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nNiemiecki - B2",
    "left": 25,
    "top": 388.0,
    "width": 128,
    "height": 37.0,
    "fontSize": 8.3,
    "lineHeight": 12.04,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "Julia Bernat",
    "fontSize": 24,
    "fontFamily": "PlayfairDisplay",
    "color": "#4A2347",
    "left": 218,
    "top": 48,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.2,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "line",
    "left": 218,
    "top": 88,
    "width": 164,
    "height": 22,
    "backgroundColor": "#E15D4F",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "Analityczka AML i Compliance",
    "fontSize": 8.2,
    "fontFamily": "Montserrat",
    "color": "#FFFDFC",
    "left": 228,
    "top": 94,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.15,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/phone.png",
    "left": 218.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/email.png",
    "left": 324.0,
    "top": 121.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 339.0,
    "top": 121.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/linkedin.png",
    "left": 218.0,
    "top": 137.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 137.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/github.png",
    "left": 364.0,
    "top": 137.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 379.0,
    "top": 137.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/website.png",
    "left": 218.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 233.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "contact-main"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/location.png",
    "left": 319.0,
    "top": 153.0,
    "width": 11.0,
    "height": 11.0,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.8,
    "fontFamily": "Montserrat",
    "color": "#806F78",
    "left": 334.0,
    "top": 153.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "contact-main"
  },
  {
    "category": "line",
    "left": 218,
    "top": 175.0,
    "width": 329,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 491,
    "top": 42,
    "width": 41,
    "height": 41,
    "backgroundColor": "#4A2347",
    "borderWidth": 1.1,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "line",
    "left": 499,
    "top": 50,
    "width": 41,
    "height": 41,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 506,
    "top": 58,
    "width": 13,
    "height": 13,
    "backgroundColor": "#E15D4F",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "ellipse",
    "left": 487,
    "top": 90,
    "width": 56,
    "height": 15,
    "backgroundColor": "#DCA65A",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "contact-main",
      "mode": "wrapping",
      "anchor": {
        "startX": 218.0,
        "startY": 121.0,
        "rightLimit": 547.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 7.8,
        "colorHex": "#806F78"
      },
      "icon": {
        "sizePt": 11.0,
        "theme": "tessera"
      },
      "metrics": {
        "iconGap": 15.0,
        "itemPad": 16.0,
        "lineStep": 16.0,
        "charWidth": 5.0
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "contact-main"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "text",
          "content": "Analityczka AML i Compliance",
          "left": 228,
          "top": 94.0,
          "width": null,
          "height": null,
          "fontSizePt": 8.2,
          "lineHeight": null,
          "fontFamily": "Montserrat",
          "colorHex": "#FFFDFC",
          "letterSpacing": 1.15,
          "align": null,
          "autoHeight": false,
          "textTransform": "uppercase",
          "bold": true
        },
        "blockPt": 27.0,
        "present": true
      },
      "contactBandId": "contact-main"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "line",
    "left": 218,
    "top": 210.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 212.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 209.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/summary.png",
    "left": 224,
    "top": 216.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 215.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 233.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 218,
    "top": 241.0,
    "width": 329,
    "height": 40,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 218,
    "top": 300.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#F7E9DF",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "rectangle",
    "left": 220,
    "top": 302.0,
    "width": 20,
    "height": 20,
    "backgroundColor": "#E15D4F",
    "borderWidth": 0.8,
    "filled": false,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "circle",
    "left": 234,
    "top": 299.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#DCA65A",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/tessera/experience.png",
    "left": 224,
    "top": 306.0,
    "width": 12,
    "height": 12,
    "zIndex": 3,
    "page": 1,
    "alignWithText": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 8.1,
    "fontFamily": "Montserrat",
    "color": "#4A2347",
    "left": 248,
    "top": 305.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.0,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 248,
    "top": 323.0,
    "width": 299,
    "height": 1,
    "backgroundColor": "#D8C5C7",
    "zIndex": 1,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 218,
    "top": 331.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e901185cb22a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 218,
    "top": 350.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e901185cb22a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 218,
    "top": 366.0,
    "width": 329,
    "height": 66,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e901185cb22a",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 218,
    "top": 442.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b0a6ba51429",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 218,
    "top": 461.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b0a6ba51429",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 218,
    "top": 477.0,
    "width": 329,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-9b0a6ba51429",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 218,
    "top": 514.0,
    "width": 329,
    "height": 15,
    "fontSize": 10.4,
    "lineHeight": 13.4,
    "letterSpacing": 0,
    "color": "#2D2530",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c3b9ae5e5b49",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 218,
    "top": 533.0,
    "width": 329,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 11.4,
    "letterSpacing": 0,
    "color": "#E15D4F",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c3b9ae5e5b49",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 218,
    "top": 549.0,
    "width": 329,
    "height": 27,
    "fontSize": 9.0,
    "lineHeight": 13.2,
    "letterSpacing": 0,
    "color": "#463E47",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-c3b9ae5e5b49",
    "flowRole": "content"
  }
];

export const tesseraTemplate = TESSERA_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
