/**
 * Vellum template (`layouts: ["single", "icons"]`).
 *
 * White-paper, portrait-led editorial with an adaptive summary field, six
 * semantic palettes, tracked labels, and Meridian/Cadenza's exact date rail.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/vellum.py`) for
 * representative demo content (Julia Bernat — four roles, two degrees, eight skills, and four languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const VELLUM_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true,
    "appearanceTemplateId": "vellum",
    "appearanceSettings": {
      "palette": "sage",
      "textSize": "M"
    }
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 796,
    "width": 479.0,
    "height": 0.7,
    "backgroundColor": "#D4DCD7",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 7.2,
    "fontFamily": "Montserrat",
    "color": "#8A5E47",
    "left": 517.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 58.0,
    "top": 43.0,
    "width": 348.0,
    "height": 32,
    "fontSize": 28.5,
    "lineHeight": 32.0,
    "letterSpacing": 3.3,
    "color": "#202623",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML i Compliance",
    "left": 58.0,
    "top": 80.0,
    "width": 348.0,
    "height": 11,
    "fontSize": 8.0,
    "lineHeight": 11.0,
    "letterSpacing": 2.2,
    "color": "#8A5E47",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "appearanceTypographyRole": "job",
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "masthead-main",
    "textTransform": "uppercase"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/phone.png",
    "left": 58.0,
    "top": 102.0,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "+48 512 340 780",
    "left": 68.0,
    "top": 102.0,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "phone",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/email.png",
    "left": 58.0,
    "top": 114.5,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "julia.bernat@email.com",
    "left": 68.0,
    "top": 114.5,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "email",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/linkedin.png",
    "left": 58.0,
    "top": 127.0,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "linkedin.com/in/jbernat",
    "left": 68.0,
    "top": 127.0,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "linkedin",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/github.png",
    "left": 58.0,
    "top": 139.5,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "github.com/jbernat",
    "left": 68.0,
    "top": 139.5,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "github",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/website.png",
    "left": 58.0,
    "top": 152.0,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "juliabernat.pl",
    "left": 68.0,
    "top": 152.0,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "website",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/location.png",
    "left": 58.0,
    "top": 164.5,
    "width": 8.6,
    "height": 8.6,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 68.0,
    "top": 164.5,
    "width": 338.0,
    "height": 10,
    "fontSize": 6.9,
    "lineHeight": 10.0,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "appearanceTypographyRole": "contact",
    "contactChannel": "location",
    "contactBandId": "vellum-contact"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 188.5,
    "width": 348.0,
    "height": 0.8,
    "backgroundColor": "#D4DCD7",
    "zIndex": 2,
    "page": 1,
    "id": "vellum-masthead-divider",
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 429.0,
    "top": 32.0,
    "width": 112.0,
    "height": 112.0,
    "backgroundColor": "#B47B5B",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 2,
    "page": 1,
    "photoSlot": "ornament",
    "appearanceColorRole": "ornament",
    "fixedToPage": true,
    "repeatOnContinuation": false,
    "flowRole": "masthead"
  },
  {
    "category": "circle",
    "left": 433.0,
    "top": 36.0,
    "width": 104.0,
    "height": 104.0,
    "backgroundColor": "#E5ECE8",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "id": "vellum-photo-frame",
    "photoSlot": "frame",
    "photoShape": "circle",
    "appearanceColorRole": "photo",
    "fixedToPage": true,
    "repeatOnContinuation": false,
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vellum-sage/portrait.png",
    "left": 465.0,
    "top": 68.0,
    "width": 40.0,
    "height": 40.0,
    "zIndex": 4,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "vellum-photo-glyph",
    "photoSlot": "glyph",
    "photoShape": "circle",
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "vellum-contact",
      "mode": "bounded-stack",
      "anchor": {
        "startX": 58.0,
        "startY": 102.0,
        "maxWidth": 348.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 6.9,
        "colorHex": "#66706B",
        "lineHeightPt": 10.0
      },
      "icon": {
        "sizePt": 8.6,
        "theme": "vellum-sage"
      },
      "metrics": {
        "iconGap": 10.0,
        "itemPad": 0.0,
        "lineStep": 12.5,
        "charWidth": 3.5880000000000005
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ],
      "flow": {
        "dividerId": "vellum-masthead-divider",
        "dividerGap": 24.0,
        "bodyGap": 12.0,
        "minimumRows": 2,
        "minimumBodyTop": 152.0,
        "bodyTop": 200.5,
        "spacing": {
          "stack": 4.0,
          "record": 10.0,
          "section": 21.0,
          "after_rule": 8.0
        }
      }
    },
    "contactBandId": "vellum-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "masthead-main",
      "name": {
        "defaultUppercase": true
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "Analityczka AML i Compliance",
          "left": 58.0,
          "top": 80.0,
          "width": 348.0,
          "height": 11,
          "fontSizePt": 8.0,
          "lineHeight": 11.0,
          "fontFamily": "Montserrat",
          "colorHex": "#8A5E47",
          "letterSpacing": 2.2,
          "align": "left",
          "autoHeight": true,
          "preserveInitialLayout": true,
          "textTransform": "uppercase",
          "bold": false,
          "italic": false,
          "underline": false,
          "zIndex": 3
        },
        "blockPt": 22.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": "vellum-contact"
    },
    "mastheadBandId": "masthead-main"
  },
  {
    "category": "line",
    "left": 0,
    "top": 200.5,
    "width": 595,
    "height": 20.0,
    "backgroundColor": "#EDF2EF",
    "zIndex": 1,
    "page": 1,
    "appearanceColorRole": "field",
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263B33",
    "left": 58.0,
    "top": 206.7,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.1,
    "appearanceColorRole": "headingOnField",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 0,
    "top": 220.5,
    "width": 595,
    "height": 31.0,
    "backgroundColor": "#EDF2EF",
    "zIndex": 1,
    "page": 1,
    "id": "vellum-summary-background",
    "flowRole": "section-background",
    "appearanceColorRole": "field",
    "flowGroup": "record-982ae43b7357"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 58.0,
    "top": 220.5,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "appearanceColorRole": "summaryText",
    "flowGroup": "record-982ae43b7357",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263B33",
    "left": 58.0,
    "top": 264.5,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.1,
    "appearanceColorRole": "headingOnPaper",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 277.5,
    "width": 24.0,
    "height": 1.2,
    "backgroundColor": "#B47B5B",
    "zIndex": 3,
    "page": 1,
    "appearanceColorRole": "ornament",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 92.0,
    "top": 277.7,
    "width": 445.0,
    "height": 0.8,
    "backgroundColor": "#D4DCD7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "AML/KYC  ·  Monitoring  ·  CDD/EDD  ·  Raporty SAR  ·  Analiza transakcyjna  ·  Screening PEP  ·  Sanctions  ·  SQL",
    "left": 58.0,
    "top": 286.7,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-90320703e5a5",
    "flowRole": "content"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263B33",
    "left": 58.0,
    "top": 319.7,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.1,
    "appearanceColorRole": "headingOnPaper",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 332.7,
    "width": 24.0,
    "height": 1.2,
    "backgroundColor": "#B47B5B",
    "zIndex": 3,
    "page": 1,
    "appearanceColorRole": "ornament",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 92.0,
    "top": 332.9,
    "width": 445.0,
    "height": 0.8,
    "backgroundColor": "#D4DCD7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 58.0,
    "top": 341.9,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4a3c06f2c320",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory",
    "left": 58.0,
    "top": 358.9,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4a3c06f2c320",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 58.0,
    "top": 373.9,
    "width": 479.0,
    "height": 34,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4a3c06f2c320",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2022 – obecnie",
    "left": 407.0,
    "top": 341.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-4a3c06f2c320"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 358.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-4a3c06f2c320"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 58.0,
    "top": 417.9,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41aa1dffe187",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank",
    "left": 58.0,
    "top": 434.9,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41aa1dffe187",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 58.0,
    "top": 449.9,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-41aa1dffe187",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2019 – 2022",
    "left": 407.0,
    "top": 417.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-41aa1dffe187"
  },
  {
    "category": "textarea",
    "content": "Warszawa",
    "left": 407.0,
    "top": 434.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-41aa1dffe187"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 58.0,
    "top": 482.9,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2958c3aab77",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services",
    "left": 58.0,
    "top": 499.9,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2958c3aab77",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 58.0,
    "top": 514.9,
    "width": 479.0,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-a2958c3aab77",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2016 – 2019",
    "left": 407.0,
    "top": 482.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-a2958c3aab77"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 499.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-a2958c3aab77"
  },
  {
    "category": "textarea",
    "content": "Asystentka ds. zgodności",
    "left": 58.0,
    "top": 536.9,
    "width": 337.0,
    "height": 13,
    "fontSize": 9.7,
    "lineHeight": 12.4,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-46ba2d99a548",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Northline Operations",
    "left": 58.0,
    "top": 553.9,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-46ba2d99a548",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Przygotowywała dokumentację klientów i wspierała kontrole jakości danych.\n• Koordynowała odpowiedzi na zapytania operacyjne zespołów sprzedaży i ryzyka.",
    "left": 58.0,
    "top": 568.9,
    "width": 479.0,
    "height": 23,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-46ba2d99a548",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2014 – 2016",
    "left": 407.0,
    "top": 536.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-46ba2d99a548"
  },
  {
    "category": "textarea",
    "content": "Kraków",
    "left": 407.0,
    "top": 553.9,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-46ba2d99a548"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263B33",
    "left": 58.0,
    "top": 612.9,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.1,
    "appearanceColorRole": "headingOnPaper",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 625.9,
    "width": 24.0,
    "height": 1.2,
    "backgroundColor": "#B47B5B",
    "zIndex": 3,
    "page": 1,
    "appearanceColorRole": "ornament",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 92.0,
    "top": 626.1,
    "width": 445.0,
    "height": 0.8,
    "backgroundColor": "#D4DCD7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 58.0,
    "top": 635.1,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8a87a7306bbd",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 58.0,
    "top": 651.1,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-8a87a7306bbd",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 407.0,
    "top": 635.1,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-8a87a7306bbd"
  },
  {
    "category": "textarea",
    "content": "Certyfikat AML Foundations",
    "left": 58.0,
    "top": 672.1,
    "width": 337.0,
    "height": 12,
    "fontSize": 9.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#202623",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-78e0190d337d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "ACAMS Academy",
    "left": 58.0,
    "top": 688.1,
    "width": 337.0,
    "height": 11,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-78e0190d337d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2021",
    "left": 407.0,
    "top": 672.1,
    "width": 130.0,
    "height": 10.2,
    "fontSize": 7.5,
    "lineHeight": 10.2,
    "letterSpacing": 0,
    "color": "#66706B",
    "fontFamily": "Lora",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "right",
    "bulletList": false,
    "autoHeight": false,
    "preserveInitialLayout": true,
    "flowRole": "record-overlay",
    "flowGroup": "record-78e0190d337d"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 7.4,
    "fontFamily": "Montserrat",
    "color": "#263B33",
    "left": 58.0,
    "top": 720.1,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 2.1,
    "appearanceColorRole": "headingOnPaper",
    "flowRole": "section-chrome",
    "editorSectionLayout": "grid",
    "editorGridColumns": 4,
    "editorGridRecordWidth": 479.0,
    "editorGridBodyLeft": 58.0,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0,
    "gridKind": "languages"
  },
  {
    "category": "line",
    "left": 58.0,
    "top": 733.1,
    "width": 24.0,
    "height": 1.2,
    "backgroundColor": "#B47B5B",
    "zIndex": 3,
    "page": 1,
    "appearanceColorRole": "ornament",
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 92.0,
    "top": 733.3000000000001,
    "width": 445.0,
    "height": 0.8,
    "backgroundColor": "#D4DCD7",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Polski — ojczysty",
    "left": 58.0,
    "top": 742.3000000000001,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-e2501dba2248",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  },
  {
    "category": "textarea",
    "content": "Angielski — C1",
    "left": 177.75,
    "top": 742.3000000000001,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-e2501dba2248",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  },
  {
    "category": "textarea",
    "content": "Niemiecki — B2",
    "left": 297.5,
    "top": 742.3000000000001,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-e2501dba2248",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  },
  {
    "category": "textarea",
    "content": "Francuski — A2",
    "left": 417.25,
    "top": 742.3000000000001,
    "width": 111.75,
    "height": 12,
    "fontSize": 8.35,
    "lineHeight": 11.2,
    "letterSpacing": 0,
    "color": "#3B4540",
    "fontFamily": "Lora",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "grid-member",
    "gridKind": "languages",
    "flowGroup": "record-e2501dba2248",
    "editorGridEntry": true,
    "gridColumns": 4,
    "gridGutter": 8.0,
    "gridWidth": 479.0,
    "gridLeft": 58.0
  }
];

export const vellumTemplate = VELLUM_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
