/**
 * Vestige template (`layouts: ["sidebar", "icons"]`).
 *
 * Narrow neutral-gray sidebar with a classical editorial main column.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/vestige.py`) for
 * representative demo content (Julia Bernat — three roles, one degree, five skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const VESTIGE_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 174.0,
    "height": 842,
    "backgroundColor": "#F4F4F2",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 174.0,
    "top": 0,
    "width": 1.0,
    "height": 842,
    "backgroundColor": "#D7D7D4",
    "zIndex": 1,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 174.0,
    "top": 0,
    "width": 421.0,
    "height": 160.5,
    "backgroundColor": "#FFFFFF",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true,
    "repeatOnContinuation": false
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 9,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 531.0,
    "top": 806,
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Julia Bernat",
    "left": 210.0,
    "top": 46.0,
    "width": 335.0,
    "height": 38,
    "fontSize": 34.0,
    "lineHeight": 38.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "CormorantGaramond",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "name",
    "mastheadBandId": "vestige-masthead"
  },
  {
    "category": "textarea",
    "content": "ANALITYCZKA AML I COMPLIANCE",
    "left": 210.0,
    "top": 86.0,
    "width": 335.0,
    "height": 13,
    "fontSize": 9.5,
    "lineHeight": 13.0,
    "letterSpacing": 1.8,
    "color": "#3E3E3C",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "masthead",
    "mastheadRole": "title",
    "mastheadBandId": "vestige-masthead",
    "textTransform": "uppercase"
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 111.0,
    "width": 335.0,
    "height": 1,
    "backgroundColor": "#D7D7D4",
    "zIndex": 1,
    "page": 1,
    "flowRole": "masthead"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#262625",
    "left": 27.0,
    "top": 141.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 27.0,
    "top": 157.28,
    "width": 16.0,
    "height": 1.4,
    "backgroundColor": "#3E3E3C",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML łącząca wiedzę regulacyjną z dyscypliną wykonania. Prowadzę monitoring transakcji i raporty SAR, dbając o jakość analiz oraz terminowość decyzji bez utraty dokładności.",
    "left": 27.0,
    "top": 168.68,
    "width": 121.60000000000001,
    "height": 96,
    "fontSize": 8.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#262625",
    "left": 27.0,
    "top": 290.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 27.0,
    "top": 306.96,
    "width": 16.0,
    "height": 1.4,
    "backgroundColor": "#3E3E3C",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Licencjat Prawa",
    "left": 27.0,
    "top": 311.68,
    "width": 121.60000000000001,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-221a8dafe22e",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "UW Warszawa",
    "left": 27.0,
    "top": 327.68,
    "width": 121.60000000000001,
    "height": 12,
    "fontSize": 8.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-221a8dafe22e",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "2012 – 2016",
    "left": 27.0,
    "top": 343.68,
    "width": 121.60000000000001,
    "height": 12,
    "fontSize": 7.5,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#747472",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-221a8dafe22e",
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#262625",
    "left": 27.0,
    "top": 367.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 27.0,
    "top": 383.96,
    "width": 16.0,
    "height": 1.4,
    "backgroundColor": "#3E3E3C",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "• AML/KYC\n• Monitoring\n• CDD/EDD\n• Raporty SAR\n• Analiza transakcyjna",
    "left": 27.0,
    "top": 388.68,
    "width": 121.60000000000001,
    "height": 60,
    "fontSize": 8.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 8.4,
    "fontFamily": "Montserrat",
    "color": "#262625",
    "left": 27.0,
    "top": 460.68,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 1.3,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "line",
    "left": 27.0,
    "top": 476.96,
    "width": 16.0,
    "height": 1.4,
    "backgroundColor": "#3E3E3C",
    "zIndex": 2,
    "page": 1,
    "flowRole": "sidebar-chrome",
    "flowLane": "sidebar"
  },
  {
    "category": "textarea",
    "content": "Polski - ojczysty\nAngielski - C1\nNiemiecki - B2",
    "left": 27.0,
    "top": 481.68,
    "width": 121.60000000000001,
    "height": 36,
    "fontSize": 8.3,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content",
    "flowLane": "sidebar"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 13.0,
    "fontFamily": "Montserrat",
    "color": "#1B1B1A",
    "left": 210.0,
    "top": 141.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "letterSpacing": 0.8,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 210.0,
    "top": 161.7,
    "width": 335.0,
    "height": 1,
    "backgroundColor": "#D7D7D4",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Analityczka AML",
    "left": 210.0,
    "top": 170.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 11.2,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f0d39c38171e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Crestmont Advisory   ·   Warszawa   ·   2022 – obecnie",
    "left": 210.0,
    "top": 186.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#747472",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f0d39c38171e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadzi monitoring transakcji i analizę alertów AML dla klientów firmowych.\n• Realizuje CDD/EDD oraz przygotowuje dokumentację zgodną z wymogami FIU.\n• Wspiera zespół L2 przy eskalacjach spraw o podwyższonym ryzyku AML.",
    "left": 210.0,
    "top": 202.7,
    "width": 335.0,
    "height": 72,
    "fontSize": 9.5,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f0d39c38171e",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Analityczka KYC",
    "left": 210.0,
    "top": 284.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 11.2,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3b1e3f77ce8d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Baltic Trust Bank   ·   Warszawa   ·   2019 – 2022",
    "left": 210.0,
    "top": 300.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#747472",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3b1e3f77ce8d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Weryfikowała profile klientów oraz screening PEP, sanctions i media.\n• Utrzymywała jakość raportów SAR oraz terminowość odpowiedzi na RFI.",
    "left": 210.0,
    "top": 316.7,
    "width": 335.0,
    "height": 36,
    "fontSize": 9.5,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-3b1e3f77ce8d",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Specjalistka Obsługi Klienta",
    "left": 210.0,
    "top": 362.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 11.2,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f77d8e6f8495",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Helios Services   ·   Kraków   ·   2016 – 2019",
    "left": 210.0,
    "top": 378.7,
    "width": 335.0,
    "height": 12,
    "fontSize": 8.6,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#747472",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f77d8e6f8495",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Obsługiwała zamówienia i weryfikację danych klientów na rynkach DACH.",
    "left": 210.0,
    "top": 394.7,
    "width": 335.0,
    "height": 24,
    "fontSize": 9.5,
    "lineHeight": 12.0,
    "letterSpacing": 0,
    "color": "#1B1B1A",
    "fontFamily": "Montserrat",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-f77d8e6f8495",
    "flowRole": "content"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/phone.png",
    "left": 27.0,
    "top": 46.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "+48 512 340 780",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 46.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "phone",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/email.png",
    "left": 27.0,
    "top": 62.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "julia.bernat@email.com",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 62.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "email",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/linkedin.png",
    "left": 27.0,
    "top": 78.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "linkedin.com/in/jbernat",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 78.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "linkedin",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/github.png",
    "left": 27.0,
    "top": 94.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "github.com/jbernat",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 94.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "github",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/website.png",
    "left": 27.0,
    "top": 110.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "juliabernat.pl",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 110.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "website",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/location.png",
    "left": 27.0,
    "top": 126.0,
    "width": 9.5,
    "height": 9.5,
    "zIndex": 3,
    "page": 1,
    "alignWithText": true,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "Warszawa",
    "fontSize": 7.7,
    "fontFamily": "Montserrat",
    "color": "#747472",
    "left": 40.0,
    "top": 126.0,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "flowRole": "masthead",
    "contactChannel": "location",
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "contactBand": {
      "id": "vestige-contact",
      "mode": "stacked",
      "anchor": {
        "startX": 27.0,
        "startY": 46.0
      },
      "text": {
        "fontFamily": "Montserrat",
        "fontSizePt": 7.7,
        "colorHex": "#747472"
      },
      "icon": {
        "sizePt": 9.5,
        "theme": "vestige"
      },
      "metrics": {
        "iconGap": 13.0,
        "itemPad": 14.0,
        "lineStep": 16.0,
        "charWidth": 5.2
      },
      "order": [
        "phone",
        "email",
        "linkedin",
        "github",
        "website",
        "location"
      ]
    },
    "contactBandId": "vestige-contact"
  },
  {
    "category": "text",
    "content": "",
    "left": 0,
    "top": 0,
    "width": 0,
    "height": 0,
    "fontSize": 1,
    "fontFamily": "Inter",
    "color": "#000000",
    "zIndex": 0,
    "page": 1,
    "flowRole": "masthead-anchor",
    "mastheadIdentity": {
      "id": "vestige-masthead",
      "name": {
        "defaultUppercase": false
      },
      "title": {
        "spec": {
          "category": "textarea",
          "content": "ANALITYCZKA AML I COMPLIANCE",
          "left": 210.0,
          "top": 86.0,
          "width": 335.0,
          "height": 13,
          "fontSizePt": 9.5,
          "lineHeight": 13.0,
          "fontFamily": "Montserrat",
          "colorHex": "#3E3E3C",
          "letterSpacing": 1.8,
          "align": "left",
          "autoHeight": true,
          "textTransform": "uppercase",
          "bold": false
        },
        "blockPt": 0.0,
        "present": true,
        "decorations": []
      },
      "contactBandId": null
    },
    "mastheadBandId": "vestige-masthead"
  },
  {
    "category": "rectangle",
    "left": 505.0,
    "top": 25.0,
    "width": 60.0,
    "height": 74.4,
    "backgroundColor": "#F4F4F2",
    "borderWidth": 0,
    "filled": true,
    "borderRadius": null,
    "zIndex": 2,
    "page": 1,
    "id": "vestige-photo-well",
    "photoSlot": "ornament",
    "flowRole": "masthead"
  },
  {
    "category": "rectangle",
    "left": 505.0,
    "top": 25.0,
    "width": 60.0,
    "height": 74.4,
    "backgroundColor": "#D7D7D4",
    "borderWidth": 1.0,
    "filled": false,
    "borderRadius": null,
    "zIndex": 3,
    "page": 1,
    "id": "vestige-photo-frame",
    "photoSlot": "frame",
    "photoShape": "rect",
    "flowRole": "masthead"
  },
  {
    "category": "image",
    "src": "/template-assets/iconic/vestige/portrait.png",
    "left": 523.0,
    "top": 50.2,
    "width": 24.0,
    "height": 24.0,
    "zIndex": 4,
    "page": 1,
    "alignWithText": false,
    "flowRole": "masthead",
    "id": "vestige-photo-glyph",
    "photoSlot": "glyph"
  }
];

export const vestigeTemplate = VESTIGE_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
