/**
 * Words template (`layouts: ["single"]`).
 *
 * Document-style single column inspired by classic word-processor CVs.
 *
 * This static starter is the backend generator's own output
 * (`backend/app/services/cv_templates/templates/words.py`) for
 * representative demo content (Jan Kowalski — three roles, one degree, five
 * skills, and three languages, sized to fit page 1 of the mockup), so the
 * picker preview matches what `/ai/fill_template` produces pixel-for-pixel.
 * Image `src` values are stored relative and get the API base prepended at
 * load time. The array already carries `flowRole` / `flowGroup` /
 * `preserveInitialLayout` from the generator, so it is exported as-is (only
 * the image src is absolutised).
 */
import API_BASE_URL from "../services/api.js";

const WORDS_ELEMENTS = [
  {
    "category": "line",
    "left": 0,
    "top": 0,
    "width": 595,
    "height": 842,
    "backgroundColor": "#FFFFFF",
    "zIndex": 0,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "line",
    "left": 72,
    "top": 783,
    "width": 451,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "circle",
    "left": 72,
    "top": 794,
    "width": 6,
    "height": 6,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "fixedToPage": true
  },
  {
    "category": "text",
    "content": "01",
    "fontSize": 10,
    "fontFamily": "Times-Roman",
    "color": "#6F6F6F",
    "left": 508,
    "top": 790,
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "fixedToPage": true
  },
  {
    "category": "textarea",
    "content": "Jan Kowalski",
    "left": 72,
    "top": 58.0,
    "width": 451,
    "height": 34,
    "fontSize": 29,
    "lineHeight": 34,
    "letterSpacing": 0,
    "color": "#202020",
    "fontFamily": "Times-Roman",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Dyrektor Strategii i Rozwoju",
    "left": 72,
    "top": 98.0,
    "width": 451,
    "height": 17,
    "fontSize": 13.5,
    "lineHeight": 17,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "jan.kowalski@email.com   ·   +48 600 000 000   ·   Warszawa   ·   linkedin.com/in/jkowalski   ·   github.com/jkowalski   ·   jankowalski.pl",
    "left": 72,
    "top": 127.0,
    "width": 451,
    "height": 26,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#6F6F6F",
    "fontFamily": "Times-Roman",
    "zIndex": 3,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 167.0,
    "width": 5,
    "height": 5,
    "backgroundColor": "#202020",
    "filled": true,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 82,
    "top": 167.0,
    "width": 5,
    "height": 5,
    "backgroundColor": "#E6E6E6",
    "filled": false,
    "borderWidth": 1,
    "zIndex": 3,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "line",
    "left": 94,
    "top": 169.0,
    "width": 429,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 209.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "PODSUMOWANIE ZAWODOWE",
    "fontSize": 12,
    "fontFamily": "Times-Roman",
    "color": "#202020",
    "left": 89,
    "top": 205.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 89,
    "top": 226.0,
    "width": 434,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Lider strategii łączący perspektywę biznesową z dyscypliną wykonania. Buduję zespoły, które podejmują czytelne decyzje i konsekwentnie dowożą mierzalne rezultaty.",
    "left": 89,
    "top": 241.0,
    "width": 434,
    "height": 30,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 296.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "DOŚWIADCZENIE ZAWODOWE",
    "fontSize": 12,
    "fontFamily": "Times-Roman",
    "color": "#202020",
    "left": 89,
    "top": 292.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 89,
    "top": 313.0,
    "width": 434,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Northbridge Partners   ·   Warszawa   ·   2021 – obecnie",
    "left": 89,
    "top": 332.0,
    "width": 434,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#6F6F6F",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b8f8ec8f3ab0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Zaprojektował model wzrostu łączący cele finansowe z inicjatywami produktowymi.\n• Uporządkował rytm decyzji zarządu oraz raportowanie strategiczne.",
    "left": 89,
    "top": 349.0,
    "width": 434,
    "height": 30,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-b8f8ec8f3ab0",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Meridian Group   ·   Kraków   ·   2016 – 2021",
    "left": 89,
    "top": 393.0,
    "width": 434,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#6F6F6F",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0af445bb60c5",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Rozwinął portfel projektów ekspansji na rynkach europejskich.\n• Wprowadził standardy współpracy między sprzedażą, produktem i finansami.",
    "left": 89,
    "top": 410.0,
    "width": 434,
    "height": 30,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-0af445bb60c5",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "Alpine Consulting   ·   Kraków   ·   2013 – 2016",
    "left": 89,
    "top": 454.0,
    "width": 434,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#6F6F6F",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": true,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4958e63b33f9",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "• Prowadził projekty doradcze dla klientów z sektora finansowego i przemysłowego.",
    "left": 89,
    "top": 471.0,
    "width": 434,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-4958e63b33f9",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 511.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "WYKSZTAŁCENIE",
    "fontSize": 12,
    "fontFamily": "Times-Roman",
    "color": "#202020",
    "left": 89,
    "top": 507.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 89,
    "top": 528.0,
    "width": 434,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Magister Zarządzania",
    "left": 89,
    "top": 543.0,
    "width": 434,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#202020",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": true,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d4972d6d4ec8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "SGH Warszawa",
    "left": 89,
    "top": 561.0,
    "width": 434,
    "height": 14,
    "fontSize": 11,
    "lineHeight": 14,
    "letterSpacing": 0,
    "color": "#202020",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d4972d6d4ec8",
    "flowRole": "content"
  },
  {
    "category": "textarea",
    "content": "2011 – 2016",
    "left": 89,
    "top": 579.0,
    "width": 434,
    "height": 13,
    "fontSize": 10,
    "lineHeight": 13,
    "letterSpacing": 0,
    "color": "#6F6F6F",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-d4972d6d4ec8",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 617.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "UMIEJĘTNOŚCI",
    "fontSize": 12,
    "fontFamily": "Times-Roman",
    "color": "#202020",
    "left": 89,
    "top": 613.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 89,
    "top": 634.0,
    "width": 434,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "Strategia  ·  Leadership  ·  P&L  ·  Negocjacje  ·  Transformacja organizacyjna",
    "left": 89,
    "top": 649.0,
    "width": 434,
    "height": 15,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": false,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowGroup": "record-e6291db90e48",
    "flowRole": "content"
  },
  {
    "category": "circle",
    "left": 72,
    "top": 689.0,
    "width": 7,
    "height": 7,
    "backgroundColor": "#202020",
    "filled": false,
    "borderWidth": 1.2,
    "zIndex": 3,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "text",
    "content": "JĘZYKI",
    "fontSize": 12,
    "fontFamily": "Times-Roman",
    "color": "#202020",
    "left": 89,
    "top": 685.0,
    "zIndex": 3,
    "page": 1,
    "bold": true,
    "italic": false,
    "flowRole": "section-chrome"
  },
  {
    "category": "line",
    "left": 89,
    "top": 706.0,
    "width": 434,
    "height": 1,
    "backgroundColor": "#BEBEBE",
    "zIndex": 2,
    "page": 1,
    "flowRole": "section-chrome"
  },
  {
    "category": "textarea",
    "content": "• Polski — ojczysty\n• Angielski — C1\n• Francuski — B2",
    "left": 89,
    "top": 721.0,
    "width": 434,
    "height": 45,
    "fontSize": 10.5,
    "lineHeight": 15,
    "letterSpacing": 0,
    "color": "#383838",
    "fontFamily": "Times-Roman",
    "zIndex": 2,
    "page": 1,
    "bold": false,
    "italic": false,
    "align": "left",
    "bulletList": true,
    "autoHeight": true,
    "preserveInitialLayout": true,
    "flowRole": "content"
  }
];

export const wordsTemplate = WORDS_ELEMENTS.map((element) => (
  element.category === "image" && typeof element.src === "string" && element.src.startsWith("/template-assets")
    ? { ...element, src: `${API_BASE_URL}${element.src}` }
    : element
));
