/** Public privacy policy reflecting the application's implemented data flows. */
import { Link } from 'react-router-dom';
import SiteLayout from '../../components/common/SiteLayout/SiteLayout';
import classes from '../../components/common/SiteLayout/SiteLayout.module.css';

export default function PrivacyPage() {
  return <SiteLayout title="Polityka prywatności" intro="Obowiązuje od 10 września 2026 r. Wyjaśnia, jakie dane CV Studio przetwarza, po co, jak długo i jakie prawa przysługują użytkownikowi.">
    <aside className={classes.notice} aria-labelledby="privacy-summary"><h2 id="privacy-summary">Najważniejsze informacje</h2><p>Administratorem jest Kamil Wrzochalski. CV Studio nie korzysta z reklamowych plików cookie ani z zewnętrznych narzędzi analitycznych. Treść CV jest prywatna, ale wybrane funkcje przekazują potrzebne dane dostawcom hostingu, płatności, poczty i modeli AI opisanym poniżej.</p><p>Nie wpisuj do CV ani poleceń AI danych szczególnych kategorii, w szczególności danych o zdrowiu, pochodzeniu rasowym lub etnicznym, poglądach politycznych, religii, seksualności, danych genetycznych ani biometrycznych.</p></aside>

    <nav className={classes.privacyToc} aria-label="Spis treści polityki"><a href="#administrator">Administrator</a><a href="#dane">Dane i cele</a><a href="#ai">AI i import</a><a href="#odbiorcy">Odbiorcy</a><a href="#retencja">Retencja</a><a href="#prawa">Twoje prawa</a></nav>

    <section id="administrator" className={classes.section}><h2>1. Administrator i kontakt</h2><p>Administratorem danych osobowych jest <strong>Kamil Wrzochalski</strong>, osoba prywatna, adres: Kordeckiego 56/58 m. 56, 04-355 Warszawa, Polska.</p><p>W sprawach prywatności napisz na <a href="mailto:kwrzochalski@gmail.com">kwrzochalski@gmail.com</a>. Korespondencję pod tym adresem obsługuje usługa Gmail firmy Google. Administrator nie wyznaczył inspektora ochrony danych.</p></section>

    <section id="dane" className={classes.section}><h2>2. Jakie dane przetwarzamy, po co i na jakiej podstawie</h2><div className={classes.tableWrap}><table className={classes.privacyTable}><caption>Zakres danych osobowych, cele przetwarzania i podstawy prawne</caption><thead><tr><th>Zakres danych</th><th>Cel</th><th>Podstawa</th></tr></thead><tbody>
      <tr><td>Nazwa użytkownika, e-mail, skrót hasła, status potwierdzenia adresu, identyfikator połączenia Google, data utworzenia i status konta.</td><td>Rejestracja, logowanie, zabezpieczenie i obsługa konta.</td><td>Wykonanie umowy o usługę (art. 6 ust. 1 lit. b RODO) oraz uzasadniony interes w ochronie usługi (lit. f).</td></tr>
      <tr><td>Treść i układ CV, dane kontaktowe wpisane do CV, zdjęcia, zapisane projekty, wygenerowane PDF-y, szkice profilu i historia importów.</td><td>Tworzenie, zapis, edycja, import i eksport dokumentów.</td><td>Wykonanie umowy (art. 6 ust. 1 lit. b RODO).</td></tr>
      <tr><td>Polecenia, wybrany fragment albo pełna treść CV, odpowiedzi AI, treść ogłoszenia oraz publiczny adres URL ogłoszenia.</td><td>Import, dostosowanie CV i wykonanie wybranej operacji AI.</td><td>Wykonanie umowy na żądanie użytkownika (art. 6 ust. 1 lit. b RODO); uzasadniony interes w diagnozie błędów bez ujawniania treści w logach (lit. f).</td></tr>
      <tr><td>Plan, limity i użycie funkcji, identyfikatory sesji i zdarzenia Stripe, kwota, waluta, status oraz dane zdarzenia płatniczego. CV Studio nie otrzymuje pełnego numeru karty.</td><td>Uruchomienie płatności, aktywacja planu, zapobieganie podwójnemu rozliczeniu i rozpatrywanie reklamacji.</td><td>Wykonanie umowy (art. 6 ust. 1 lit. b), obowiązki prawne przy płatnościach Live (lit. c) i obrona roszczeń (lit. f).</td></tr>
      <tr><td>Adres IP, nagłówki żądania, czas, ścieżka, kod odpowiedzi, błędy techniczne i skróty używane do limitowania prób logowania.</td><td>Dostarczenie usługi, ochrona przed nadużyciami, diagnostyka i dostępność.</td><td>Uzasadniony interes administratora w bezpiecznym działaniu usługi (art. 6 ust. 1 lit. f RODO).</td></tr>
      <tr><td>Adres e-mail i treść korespondencji.</td><td>Odpowiedź na pytanie, żądanie dotyczące danych lub reklamację.</td><td>Art. 6 ust. 1 lit. b, c lub f RODO — zależnie od treści sprawy.</td></tr>
    </tbody></table></div><p>Podanie danych konta jest dobrowolne, ale konieczne do zapisu i pobierania dokumentów. Dane w CV podajesz samodzielnie; niektóre dane konta otrzymujemy od Google, a informacje o płatności — od Stripe.</p><p>Jeżeli umieszczasz w CV dane innej osoby, na przykład osoby udzielającej referencji, upewnij się, że możesz zgodnie z prawem z nich korzystać i ogranicz je do informacji potrzebnych w rekrutacji.</p></section>

    <section id="przegladarka" className={classes.section}><h2>3. Dane w przeglądarce</h2><p>Bez logowania szkic CV i szkic kreatora mogą być zapisane wyłącznie w pamięci lokalnej przeglądarki. Po zalogowaniu w tej samej pamięci znajduje się token sesji i pomocnicza nazwa użytkownika. Osoba używająca tego samego profilu przeglądarki może uzyskać do nich dostęp, dlatego po pracy na współdzielonym urządzeniu wyloguj się i usuń dane witryny.</p><p>CV Studio nie zapisuje anonimowej kolejki zdarzeń marketingowych, nie używa Google Analytics ani piksela reklamowego. Technicznie niezbędne mechanizmy pamięci przeglądarki działają bez banera zgody, ponieważ służą wyłącznie żądanej funkcji i bezpieczeństwu sesji.</p></section>

    <section id="ai" className={classes.section}><h2>4. Import PDF, AI i ogłoszenia</h2><p>Oryginalny plik PDF jest odczytywany na potrzeby importu i nie jest przechowywany jako plik po zakończeniu operacji. Zachowany może zostać ustrukturyzowany wynik importu, nazwa i rozmiar pliku, status oraz bezpieczny kod błędu. Zależnie od funkcji strony PDF mogą zostać zamienione na obrazy i przekazane do Cloudflare Workers AI albo — gdy skonfigurowano odpowiednią funkcję — do OpenAI.</p><p>Asystent AI przekazuje OpenAI polecenie oraz zakres dokumentu potrzebny do odpowiedzi. Dostosowanie do oferty może pobrać treść publicznej strony wskazanej przez użytkownika; właściciel tej strony otrzyma wtedy żądanie z infrastruktury serwera CV Studio. Wyniki AI mogą zawierać błędy i wymagają weryfikacji przez użytkownika.</p><p><strong>Zakaz danych szczególnych kategorii:</strong> usługa nie jest przeznaczona do przetwarzania takich danych. Nie przesyłaj ich w dokumentach, zdjęciach, ogłoszeniach ani poleceniach AI. Jeżeli CV zawodowe wymaga informacji o dostosowaniach lub zdrowiu, dodaj je poza CV Studio do ostatecznego dokumentu.</p><p>AI nie podejmuje decyzji wywołujących skutki prawne ani podobnie istotnie wpływających na użytkownika. Dobór treści, akceptacja zmian i wysłanie CV zawsze należą do użytkownika.</p></section>

    <section id="odbiorcy" className={classes.section}><h2>5. Odbiorcy i podmioty przetwarzające</h2><ul>
      <li><strong>Render Services, Inc.</strong> — hosting frontendu i backendu, PostgreSQL oraz logi techniczne.</li>
      <li><strong>Amazon Web Services, Inc.</strong> — prywatny magazyn S3 dla zdjęć i wygenerowanych PDF-ów, gdy S3 jest włączone.</li>
      <li><strong>Cloudflare, Inc.</strong> — Workers AI używane w domyślnym procesie odczytu CV.</li>
      <li><strong>OpenAI, L.L.C.</strong> — asystent AI, operacje na CV i opcjonalny mechanizm odczytu dokumentu.</li>
      <li><strong>Google</strong> — Google Identity Services przy logowaniu lub połączeniu konta oraz Gmail przy korespondencji z administratorem.</li>
      <li><strong>Resend, Inc.</strong> — dostarczenie wiadomości potwierdzającej rejestrację z adresu accounts@cvstudio.com.pl.</li>
      <li><strong>Stripe</strong> — Checkout i obsługa płatności. Stripe może działać również jako niezależny administrator danych wymaganych przez prawo płatnicze.</li>
      <li><strong>home.pl S.A.</strong> — rejestracja domeny i obsługa DNS.</li>
      <li><strong>Operator publicznej strony z ofertą pracy</strong> — tylko gdy użytkownik poleci CV Studio pobrać treść wskazanego adresu.</li>
    </ul><p>Dane mogą zostać ujawnione organom publicznym wyłącznie, gdy wymaga tego prawo. Administrator nie sprzedaje danych osobowych.</p><p className={classes.providerLinks}>Informacje dostawców: <a href="https://render.com/privacy">Render</a>, <a href="https://aws.amazon.com/privacy/">AWS</a>, <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>, <a href="https://openai.com/policies/privacy-policy/">OpenAI</a>, <a href="https://policies.google.com/privacy">Google</a>, <a href="https://resend.com/legal/privacy-policy">Resend</a>, <a href="https://stripe.com/privacy">Stripe</a> i <a href="https://home.pl/polityka-prywatnosci/">home.pl</a>.</p></section>

    <section id="transfery" className={classes.section}><h2>6. Przekazywanie poza EOG</h2><p>Usługa jest dostępna na całym świecie, a część dostawców ma siedzibę lub infrastrukturę poza Europejskim Obszarem Gospodarczym, w szczególności w Stanach Zjednoczonych. Gdy dane są przekazywane poza EOG, podstawą są odpowiednie mechanizmy z rozdziału V RODO, takie jak decyzja stwierdzająca odpowiedni stopień ochrony, standardowe klauzule umowne albo Ramy Ochrony Danych UE–USA, jeśli dany odbiorca i transfer spełniają ich warunki. Kopię informacji o właściwym zabezpieczeniu można uzyskać pod adresem kontaktowym administratora.</p><p>Dokładny region chmury zależy od aktywnej konfiguracji produkcyjnej. Administrator nie obiecuje przechowywania wyłącznie w Polsce; konfiguracja wdrożeniowa powinna wybierać regiony europejskie, gdy są dostępne.</p></section>

    <section id="retencja" className={classes.section}><h2>7. Jak długo przechowujemy dane</h2><ul>
      <li>Konto, projekty, elementy CV, zdjęcia, szkice profilu, wyniki importów, liczniki użycia i zapisane odpowiedzi AI — do usunięcia ich przez użytkownika lub usunięcia konta. Obecnie odpowiedzi AI nie mają dodatkowego automatycznego terminu czyszczenia.</li>
      <li>Token sesji standardowo wygasa po 7 dniach. Jednorazowy link potwierdzający e-mail wygasa po 24 godzinach; w bazie zapisywany jest jego nieodwracalny skrót.</li>
      <li>Rekordy Stripe, w tym surowa treść zdarzenia webhook, są przechowywane do usunięcia konta. Po uruchomieniu płatności Live część danych rozliczeniowych może być zachowana dłużej, gdy wymagają tego przepisy podatkowe, rachunkowe albo obrona roszczeń.</li>
      <li>Logi techniczne są przechowywane według aktywnego planu i ustawień Render. Administrator ogranicza treść logów i nie powinien zapisywać w nich dokumentów ani sekretów.</li>
      <li>Korespondencja — przez czas obsługi sprawy, a następnie do upływu terminów dochodzenia lub obrony roszczeń.</li>
      <li>Po usunięciu wpisy mogą pozostawać przez ograniczony czas w rotujących kopiach zapasowych dostawców. Nie są używane operacyjnie i znikają zgodnie z cyklem kopii.</li>
    </ul><p>Usunięcie konta od razu usuwa powiązania i rekordy z aktywnej bazy. Fizyczne pliki prywatne są usuwane poprzez kolejkę z ponawianiem operacji, aby chwilowa awaria magazynu nie przywróciła dostępu do konta. Usunięcie nie obejmuje danych, które niezależni administratorzy, tacy jak Stripe lub Google, muszą zachować na własnej podstawie prawnej.</p></section>

    <section id="bezpieczenstwo" className={classes.section}><h2>8. Bezpieczeństwo</h2><p>Hasła są przechowywane jako skróty Argon2id, a starsze rekordy są migrowane z bcrypt. API weryfikuje token i właściciela dokumentu przed udostępnieniem pliku, obiekty S3 są prywatne, nazwy plików nie wyznaczają ścieżki magazynu, a próby logowania i rozmiary żądań są ograniczane. Połączenia produkcyjne używają HTTPS. Żaden system nie daje jednak absolutnej gwarancji bezpieczeństwa.</p></section>

    <section id="prawa" className={classes.section}><h2>9. Twoje prawa</h2><p>W granicach RODO możesz żądać dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przeniesienia oraz wnieść sprzeciw wobec przetwarzania opartego na uzasadnionym interesie. Jeśli podstawą jest zgoda, możesz ją wycofać bez wpływu na zgodność wcześniejszego przetwarzania.</p><p>Zalogowany użytkownik może pobrać dane i usunąć konto w sekcji <Link to="/app/account">Konto i plan</Link>. Eksport nie zawiera haseł, tokenów, identyfikatora Google ani prywatnych kluczy magazynu. W pozostałych sprawach napisz na <a href="mailto:kwrzochalski@gmail.com">kwrzochalski@gmail.com</a>; administrator może poprosić o potwierdzenie tożsamości.</p><p>Możesz złożyć skargę do <a href="https://uodo.gov.pl/pl/493/155">Prezesa Urzędu Ochrony Danych Osobowych</a>, ul. Stanisława Moniuszki 1A, 00-014 Warszawa.</p></section>

    <section id="dzieci" className={classes.section}><h2>10. Wiek użytkownika i zasięg</h2><p>CV Studio jest przeznaczone wyłącznie dla osób, które ukończyły 18 lat. Usługa jest kierowana do konsumentów i może być używana na całym świecie, z zastrzeżeniem dostępności technicznej i lokalnego prawa.</p></section>

    <section id="zmiany" className={classes.section}><h2>11. Zmiany polityki</h2><p>Polityka może zostać zmieniona, gdy zmieniają się funkcje, dostawcy lub przepisy. Data obowiązywania znajduje się na początku strony. O istotnych zmianach dotyczących aktywnego konta administrator poinformuje w aplikacji lub e-mailem, jeżeli będzie to wymagane.</p></section>
  </SiteLayout>;
}
