import { createContext } from "react";

//create the context value
// value that is produced by createContext() will be an object that contains a React component
// export = providing context to the APP, then wrap components (PdfGenerator Page) with PdfContext 

export const PdfContext = createContext({
    A4_Elements : [],
    groupMoveDelta: null,
    isTwoPageView: false,
    toggleTwoPageView: () => {},
    setPageCanvasRef: () => {},
    addImage: () => {},
    addText: () => {},
    addLine: () => {},
    addRectangle: () => {},
    addCircle: () => {},
    addEllipse: () => {},
    addConnector: () => {},
    showDeckPanel: () => {},
    showArticlePanel: () => {},
    isBioCvModal: false,
    showBioCvModal: () => {},
    clonePage: () => {},
    movePage: () => {},
    undo: () => {},
    redo: () => {},
    canUndo: false,
    canRedo: false,
    resetHistory: () => {},
    activePdfId: null,
    flushAutosave: async () => {},
    discardActiveDocument: () => {},
    pageSize: { preset: "a4-portrait", width: 595, height: 842 },
    setPageSize: () => {},
    setPagePreset: () => {},
    selectElement: () => {},
    moveElement: () => {},
    moveSelectedElements: () => {},
    selectMoveElement: () => {},
    isGallery: false,
    isDropzone: false,
    createPdf: () => {},
    showDropzone:() => {},
    showGallery: () => {},
    editElementValues: () => {},
    editSelectedElementValues: () => {},
    applyStructureOperation: () => {},
    applyDeleteOperation: () => {},
    fitTextareaToContent: () => {},
    alignElement: () => {},
    deleteElement: () => {},
    deleteSelectedElements: () => {},
    duplicateSelectedElements: () => {},
    setA4_Elements: () => {},
    valueImageUpload: 0,
    setValueImageUpload: () => {},
    addTitle: () => {},
    isVisibleModal: false,
    setIsModalPdfs: () => {},
    resizeElement: () => {},
    updatePdf: () => {},
    handlePdfId: () => {},
    handleSetTitle: () => {},
    title: undefined,
    clearA4modalDelete: () => {},
    clearA4: () => {},
    logout: () => {},
    isPdfLoading: false,
    setA4_Elements_deleted: () =>{},
    structurePreviewGroup: null,
    setStructurePreviewGroup: () => {},
    deletionPreviewIds: [],
    setDeletionPreviewIds: () => {},
    setPDFdownloadData: () => {},
    PDFdownloadData: []
})